CREATE TABLE `users` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`account` VARCHAR(50) NULL DEFAULT NULL,
	`user_id` BIGINT(20) NOT NULL,
	PRIMARY KEY (`id`)
)
COMMENT='user表'
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
