spring:
  redis:
    host: 127.0.0.1
  #    password: 123456
  coordinate:
    zookeeper:
#      zk-servers: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
logging:
  level:
    com.baomidou: debug
lock4j:
  acquire-timeout: 3000 #默认值，可不设置
  expire: 30000 #默认值，可不设置
  primary-executor: com.baomidou.lock.executor.RedisTemplateLockExecutor #默认redisson>redisTemplate>zookeeper
