package io.github.wujun728.record.model;

import io.github.wujun728.record.model.base.BaseBlog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Blog extends BaseBlog<Blog> {
	
}
