package org.service.query;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7 2018-02-02T12:34:20.911+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://query.service.org/", name = "QueryServiceInter")
public interface QueryServiceInter {

	@WebMethod
	@RequestWrapper(localName = "queryCarInfomation", targetNamespace = "http://query.service.org/", className = "org.service.query.QueryCarInfomation")
	@ResponseWrapper(localName = "queryCarInfomationResponse", targetNamespace = "http://query.service.org/", className = "org.service.query.QueryCarInfomationResponse")
	@WebResult(name = "return", targetNamespace = "")
	public java.lang.String queryCarInfomation(
			@WebParam(name = "carParam", targetNamespace = "") java.lang.String carParam);

	@WebMethod
	@RequestWrapper(localName = "queryPersonnelInformation", targetNamespace = "http://query.service.org/", className = "org.service.query.QueryPersonnelInformation")
	@ResponseWrapper(localName = "queryPersonnelInformationResponse", targetNamespace = "http://query.service.org/", className = "org.service.query.QueryPersonnelInformationResponse")
	@WebResult(name = "return", targetNamespace = "")
	public java.lang.String queryPersonnelInformation(
			@WebParam(name = "peopleParam", targetNamespace = "") java.lang.String peopleParam);
}
