/*
 * This file is generated by jOOQ.
*/
package com.mycompany.myproject.jooq.tables.records;


import com.mycompany.myproject.jooq.tables.Welcome;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WelcomeRecord extends UpdatableRecordImpl<WelcomeRecord> implements Record6<Integer, String, String, Timestamp, String, Timestamp> {

    private static final long serialVersionUID = -334328241;

    /**
     * Setter for <code>barry.welcome.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>barry.welcome.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>barry.welcome.welcome_msg</code>.
     */
    public void setWelcomeMsg(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>barry.welcome.welcome_msg</code>.
     */
    public String getWelcomeMsg() {
        return (String) get(1);
    }

    /**
     * Setter for <code>barry.welcome.create_by</code>.
     */
    public void setCreateBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>barry.welcome.create_by</code>.
     */
    public String getCreateBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>barry.welcome.create_date</code>. 创建时间
     */
    public void setCreateDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>barry.welcome.create_date</code>. 创建时间
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>barry.welcome.update_by</code>.
     */
    public void setUpdateBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>barry.welcome.update_by</code>.
     */
    public String getUpdateBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>barry.welcome.update_date</code>. 修改时间
     */
    public void setUpdateDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>barry.welcome.update_date</code>. 修改时间
     */
    public Timestamp getUpdateDate() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Timestamp, String, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Timestamp, String, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Welcome.WELCOME.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Welcome.WELCOME.WELCOME_MSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Welcome.WELCOME.CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Welcome.WELCOME.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Welcome.WELCOME.UPDATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Welcome.WELCOME.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getWelcomeMsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getWelcomeMsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WelcomeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WelcomeRecord value2(String value) {
        setWelcomeMsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WelcomeRecord value3(String value) {
        setCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WelcomeRecord value4(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WelcomeRecord value5(String value) {
        setUpdateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WelcomeRecord value6(Timestamp value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WelcomeRecord values(Integer value1, String value2, String value3, Timestamp value4, String value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WelcomeRecord
     */
    public WelcomeRecord() {
        super(Welcome.WELCOME);
    }

    /**
     * Create a detached, initialised WelcomeRecord
     */
    public WelcomeRecord(Integer id, String welcomeMsg, String createBy, Timestamp createDate, String updateBy, Timestamp updateDate) {
        super(Welcome.WELCOME);

        set(0, id);
        set(1, welcomeMsg);
        set(2, createBy);
        set(3, createDate);
        set(4, updateBy);
        set(5, updateDate);
    }
}
