<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://server.webservice.camel.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://server.cxf.camel.com/" name="CamelCXFServiceImplService" targetNamespace="http://server.webservice.camel.com/">
	<wsdl:import location="http://localhost:9022/camel-cxf/greeter-service?wsdl=CamelCXFServiceInter.wsdl" namespace="http://server.cxf.camel.com/"> </wsdl:import>
	<wsdl:binding name="CamelCXFServiceImplServiceSoapBinding" type="ns1:CamelCXFServiceInter">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="queryInfomation">
			<soap:operation soapAction="" style="document"/>
			<wsdl:input name="queryInfomation">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="queryInfomationResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="sayHello">
			<soap:operation soapAction="" style="document"/>
			<wsdl:input name="sayHello">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="sayHelloResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="CamelCXFServiceImplService">
		<wsdl:port binding="tns:CamelCXFServiceImplServiceSoapBinding" name="CamelCXFServiceImplPort">
			<soap:address location="http://localhost:9022/camel-cxf/greeter-service"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>