package sample

import sample.bean.Message

function String stringAdd(String s1,String s2){
	return s1 + s2;
}


function boolean testEval(String s1,String s2){return s1 == s2;}

rule "handle message0"
    when
        $message : Message( Message.num == Message.THREAD0)
    then
        System.out.println("000");
 end      
 

 rule "handle message1"
    when
        $message : Message( Message.num == Message.THREAD1)        
    then
        System.out.println("111"+ $message.getMessage());
        System.out.println("function   -----   "+ stringAdd("handle message1   ",$message.getMessage()));
 end    
 
 
 rule "handle message2"
    when
        $message : Message( Message.num == Message.THREAD2)
    then
        System.out.println("222" + $message.getMessage());
 end    
 
 
 rule "handle message3"
    when
        eval(testEval("1","2"))
        $message : Message( Message.num == Message.THREAD3)
        eval(testEval("1","1"))
    then
        System.out.println("333"+ $message.getMessage());
 end    
 
 
 
 rule "handle message4"
    when
        $message : Message( Message.num == Message.THREAD4)
    then
        System.out.println("444"+ $message.getMessage());
 end    