/*
 * This file is generated by jOOQ.
*/
package com.mycompany.myproject.jooq;


import com.mycompany.myproject.jooq.tables.Welcome;
import com.mycompany.myproject.jooq.tables.records.WelcomeRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>barry</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<WelcomeRecord, Integer> IDENTITY_WELCOME = Identities0.IDENTITY_WELCOME;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<WelcomeRecord> KEY_WELCOME_PRIMARY = UniqueKeys0.KEY_WELCOME_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<WelcomeRecord, Integer> IDENTITY_WELCOME = Internal.createIdentity(Welcome.WELCOME, Welcome.WELCOME.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<WelcomeRecord> KEY_WELCOME_PRIMARY = Internal.createUniqueKey(Welcome.WELCOME, "KEY_welcome_PRIMARY", Welcome.WELCOME.ID);
    }
}
