
CREATE TABLE `D_OPEN_SURVEY` (
  `F_ID` varchar(32) NOT NULL,
  `F_ALLOWREPORT` int(11) DEFAULT NULL,
  `F_CREATETIME` datetime DEFAULT NULL,
  `F_DESCRIPTION` varchar(255) DEFAULT NULL,
  `F_NAME` varchar(255) DEFAULT NULL,
  `F_PAGECOUNT` int(11) DEFAULT NULL,
  `F_QUESTIONCOUNT` int(11) DEFAULT NULL,
  `F_SAMPLECOUNT` int(11) DEFAULT NULL,
  `F_SAMPLESUM` int(11) DEFAULT NULL,
  `F_SHOW` int(11) DEFAULT NULL,
  `F_SURVEYURL` varchar(255) DEFAULT NULL,
  `F_TAG` varchar(255) DEFAULT NULL,
  `F_TYPE` int(11) DEFAULT NULL,
  `F_TYPENAME` varchar(255) DEFAULT NULL,
  `F_UID` varchar(255) DEFAULT NULL,
  `F_USERSURVEYCOUNT` int(11) DEFAULT NULL,
  `F_VIEWERSUM` int(11) DEFAULT NULL,
  PRIMARY KEY (`F_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `T_NEWS` (
  `ID` varchar(255) NOT NULL,
  `ADDRESS` varchar(255) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `NEWS_TIME` datetime DEFAULT NULL,
  `TITLE` varchar(255) DEFAULT NULL,
  `USER_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `T_SYS_ROLE` (
  `ID` varchar(32) NOT NULL,
  `CODE` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `REMARK` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `T_SYS_ROLE_PERMISSION` (
  `ID` varchar(32) NOT NULL,
  `PERMISSION_ID` varchar(255) DEFAULT NULL,
  `ROLE_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `T_SYS_USER` (
  `ID` varchar(32) NOT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `LAST_LOGIN_TIME` datetime DEFAULT NULL,
  `MODIFY_TIME` datetime DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `ORGANIZE_ID` varchar(255) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `SALT` varchar(255) DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL,
  `TRUE_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_g925f0fmmdswsyenhdcq80aqv` (`email`),
  UNIQUE KEY `UK_mocatd9fh3tj7mv0815baepmq` (`NAME`),
  UNIQUE KEY `UK_ar8vsmvija6p1mlnw7vkw7aql` (`TRUE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `T_SYS_USER_ROLE` (
  `ID` varchar(32) NOT NULL,
  `ROLE_ID` varchar(255) DEFAULT NULL,
  `USER_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `T_SYS_PERMISSION` (
  `ID` varchar(32) NOT NULL,
  `HIDE` int(11) DEFAULT NULL,
  `SKEY` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `PARENT_KEY` varchar(255) DEFAULT NULL,
  `SORT` int(11) DEFAULT NULL,
  `URL` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
