package io.github.wujun728.record.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlog<M extends BaseBlog<M>> extends Model<M> implements IBean {

	/**
	 * id注释
	 */
	public void setId(Integer id) {
		set("id", id);
	}
	
	/**
	 * id注释
	 */
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * title注释
	 */
	public void setTitle(String title) {
		set("title", title);
	}
	
	/**
	 * title注释
	 */
	public String getTitle() {
		return getStr("title");
	}

	/**
	 * content注释
	 */
	public void setContent(String content) {
		set("content", content);
	}
	
	/**
	 * content注释
	 */
	public String getContent() {
		return getStr("content");
	}

}
