/*
 * This file is generated by jOOQ.
*/
package com.mycompany.myproject.jooq;


import com.mycompany.myproject.jooq.tables.Welcome;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in barry
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>barry.welcome</code>.
     */
    public static final Welcome WELCOME = com.mycompany.myproject.jooq.tables.Welcome.WELCOME;
}
