/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version fusioncharts/3.3.1-sr2.19840
*/
FusionCharts(["private","modules.renderer.js-charts",function(){function Ba(a){for(var A={left:a.offsetLeft,top:a.offsetTop},a=a.offsetParent;a;)A.left+=a.offsetLeft,A.top+=a.offsetTop,a!==C.body&&a!==C.documentElement&&(A.left-=a.scrollLeft,A.top-=a.scrollTop),a=a.offsetParent;return A}function fa(a,A){for(var d=[],f=0,D=a.length;f<D;f++)d[f]=A.call(a[f],a[f],f,a);return d}function ta(a){a=(a||0)%da;return a<0?da+a:a}function Ca(a,A){return a<=w?a:A<=w?A:A>a?0:A}function La(a,A,d,f,D){return K((A-
d[1]-f.top)/D,a-d[0]-f.left)}function Da(a,A,d,f,D,b,m,t,c,p){if(typeof a==="object")A=a.y,d=a.r,f=a.innerR,D=a.radiusYFactor,b=a.depth,m=a.seriesGroup,t=a.renderer,a=a.x;if(D<0||D>=1)D=0.6;a=a||0;A=A||0;d=d||1;f=f||0;b=b||0;this.renderer=t;this.hasOnePoint=c;this.use3DLighting=p;this.cx=a;this.cy=A;this.rx=d;this.ry=d*D;this.radiusYFactor=D;this.isDoughnut=f>0;this.innerRx=f;this.innerRy=f*D;this.depth=b;this.leftX=a-d;this.rightX=a+d;this.leftInnerX=a-f;this.rightInnerX=a+f;this.depthY=A+b;this.topY=
A-this.ry;this.bottomY=this.depthY+this.ry;this.bottomBorderGroup=t.group("bottom-border",m).attr({transform:"t0,"+b});this.outerBackGroup=t.group("outer-back-Side",m);this.slicingWallsBackGroup=t.group("slicingWalls-back-Side",m);this.innerBackGroup=t.group("inner-back-Side",m);this.innerFrontGroup=t.group("inner-front-Side",m);this.slicingWallsFrontGroup=t.group("slicingWalls-front-Side",m);this.topGroup=t.group("top-Side",m);this.moveCmdArr=[e];this.lineCmdArr=[i];this.closeCmdArr=[h];this.centerPoint=
[a,A];this.leftPoint=[this.leftX,A];this.topPoint=[a,this.topY];this.rightPoint=[this.rightX,A];this.bottomPoint=[a,A+this.ry];this.leftDepthPoint=[this.leftX,this.depthY];this.rightDepthPoint=[this.rightX,this.depthY];this.leftInnerPoint=[this.leftInnerX,A];this.rightInnerPoint=[this.rightInnerX,A];this.leftInnerDepthPoint=[this.leftInnerX,this.depthY];this.rightInnerDepthPoint=[this.rightInnerX,this.depthY];this.pointElemStore=[];this.slicingWallsArr=[];a=[g,this.rx,this.ry,0,0,1,this.rightX,A];
d=[g,this.rx,this.ry,0,0,1,this.leftX,A];f=[g,this.rx,this.ry,0,0,0,this.rightX,this.depthY];D=[g,this.rx,this.ry,0,0,0,this.leftX,this.depthY];b=[g,this.innerRx,this.innerRy,0,0,0,this.rightInnerX,A];A=[g,this.innerRx,this.innerRy,0,0,0,this.leftInnerX,A];m=[g,this.innerRx,this.innerRy,0,0,1,this.rightInnerX,this.depthY];t=[g,this.innerRx,this.innerRy,0,0,1,this.leftInnerX,this.depthY];this.isDoughnut?(this.topBorderPath=this.moveCmdArr.concat(this.leftPoint,a,d,this.moveCmdArr,this.leftInnerPoint,
b,A),this.topPath=this.moveCmdArr.concat(this.leftPoint,a,d,this.lineCmdArr,this.leftInnerPoint,b,A,this.closeCmdArr),this.innerFrontPath=this.moveCmdArr.concat(this.leftInnerPoint,b,this.lineCmdArr,this.rightInnerDepthPoint,t,this.closeCmdArr),this.innerBackPath=this.moveCmdArr.concat(this.rightInnerPoint,A,this.lineCmdArr,this.leftInnerDepthPoint,m,this.closeCmdArr)):this.topBorderPath=this.topPath=this.moveCmdArr.concat(this.leftPoint,a,d,this.closeCmdArr);this.outerBackPath=this.moveCmdArr.concat(this.leftPoint,
a,this.lineCmdArr,this.rightDepthPoint,D,this.closeCmdArr);this.outerFrontPath=this.moveCmdArr.concat(this.rightPoint,d,this.lineCmdArr,this.leftDepthPoint,f,this.closeCmdArr);this.clipPathforOuter=[e,this.leftX,this.topY,i,this.rightX,this.topY,this.rightX,this.bottomY,this.leftX,this.bottomY,h];this.clipPathforInner=[e,this.leftInnerX,this.topY,i,this.rightInnerX,this.topY,this.rightInnerX,this.bottomY,this.leftInnerX,this.bottomY,h];this.clipPathforNoClip=[e,this.leftInnerX,this.topY,i,this.leftInnerX,
this.bottomY,h]}var la=this,y=la.hcLib,ea=y.Raphael,C=window.document,J=y.BLANKSTRING,Ma=y.createTrendLine,k=y.pluck,wa=y.getValidValue,l=y.pluckNumber,M=y.defaultPaletteOptions,Ea=y.getFirstValue,Qa=y.getDefinedColor,V=y.parseUnsafeString,X=y.FC_CONFIG_STRING,ua=y.extend2,Na=y.getDashStyle,Z=y.toRaphaelColor,Fa=y.toPrecision,Ga=y.stubFN,aa=y.hasSVG,ya=y.isIE,va=y.each,qa=y.hasTouch?10:3,b="rgba(192,192,192,"+(ya?0.002:1.0E-6)+")",c=document.documentMode===8?"visible":"",e="M",i="L",g="A",h="Z",S=
Math,T=S.sin,W=S.cos,K=S.atan2,B=S.round,s=S.min,ma=S.max,pa=S.abs,Q=S.PI,Oa=S.ceil,U=S.floor,R=S.sqrt,ga=Q/180,w=Math.PI,ja=w/2,da=2*w,Ta=w+ja,Y=y.graphics.getColumnColor,ca=y.getFirstColor,Aa=y.setLineHeight,Ia=y.pluckFontSize,Ha=y.getFirstAlpha,ha=y.graphics.getDarkColor,ka=y.graphics.getLightColor,ra=y.graphics.convertColor,Pa=y.COLOR_TRANSPARENT,b="rgba(192,192,192,"+(ya?0.002:1.0E-6)+")",Sa=y.POSITION_CENTER,Va=y.POSITION_TOP,Ua=y.POSITION_BOTTOM,Wa=y.POSITION_RIGHT,Xa=y.POSITION_LEFT,n=y.chartAPI,
Ya=y.titleSpaceManager,Za=y.placeLegendBlockBottom,$a=y.placeLegendBlockRight,ab=y.graphics.mapSymbolName,ya=n.singleseries,O=y.COMMASTRING,xa=y.ZEROSTRING,Ja=y.ONESTRING,za=y.HUNDREDSTRING,Ra=y.PXSTRING,bb=y.COMMASPACE,sa=!/fusioncharts\.com$/i.test(location.hostname);n("column2d",{standaloneInit:!0,creditLabel:sa,rendererId:"cartesian"},n.column2dbase);n("column3d",{defaultSeriesType:"column3d",defaultPlotShadow:1,is3D:!0,defaultZeroPlaneHighlighted:!1},n.column2d);n("bar2d",{isBar:!0,defaultSeriesType:"bar",
spaceManager:n.barbase},n.column2d);n("bar3d",{defaultSeriesType:"bar3d",defaultPlotShadow:1,is3D:!0,defaultZeroPlaneHighlighted:!1},n.bar2d);n("line",{standaloneInit:!0,creditLabel:sa,rendererId:"cartesian"},n.linebase);n("area2d",{standaloneInit:!0,creditLabel:sa,rendererId:"cartesian"},n.area2dbase);n("pie2d",{standaloneInit:!0,defaultSeriesType:"pie",defaultPlotShadow:1,sliceOnLegendClick:!0,rendererId:"pie",point:function(a,A,d,f,D){var b,m,t,c=D[X],p=c.is3d,o,r,j,e,g=0,i=0,Ka=[];t=l(f.plotborderthickness);
var h=l(t,p?0.1:1),q=(o=l(f.use3dlighting,1))?l(f.radius3d,f["3dradius"],90):100;r=l(f.showzeropies,1);var x=l(f.showpercentintooltip,1),n=l(f.showlabels,1),T=l(f.showvalues,1),w=l(f.showpercentvalues,f.showpercentagevalues,0),E=k(f.tooltipsepchar,f.hovercapsepchar,bb),v=k(f.labelsepchar,E),u=k(f.plotbordercolor,f.piebordercolor),z=D[X].numberFormatter;j=d.length;var W,s,G=l(f.plotborderdashed,0),N=l(f.plotborderdashlen,5),F=l(f.plotborderdashgap,4);q>100&&(q=100);q<0&&(q=0);if(l(f.showlegend,0))D.legend.enabled=
!0,D.legend.reversed=!Boolean(l(f.reverselegend,0)),A.showInLegend=!0;for(a=0;a<j;a+=1)m=d[a],b=z.getCleanValue(m.value,!0),b===null||!r&&b===0||(Ka.push(m),g+=b);g===0&&(Ka=[]);A.enableRotation=Ka.length>1?l(f.enablerotation,1):0;A.alphaAnimation=l(f.alphaanimation,1);A.is3D=p;A.use3DLighting=o;A.pieYScale=l(f.pieyscale,40);if(A.pieYScale<1)A.pieYScale=1;if(A.pieYScale>=100)A.pieYScale=80;A.pieYScale/=100;A.pieSliceDepth=l(f.pieslicedepth,15);if(A.pieSliceDepth<1)A.pieSliceDepth=1;A.managedPieSliceDepth=
A.pieSliceDepth;if(p&&f.showplotborder!=Ja&&!t)A.showBorderEffect=1;for(a=Ka.length-1;a>=0;a-=1){m=Ka[a];b=z.getCleanValue(m.value,!0);d=V(k(m.label,m.name,J));o=k(m.color,D.colors[a%D.colors.length]);r=k(m.alpha,f.plotfillalpha);j=k(m.bordercolor,u);e=k(m.borderalpha,f.plotborderalpha,f.pieborderalpha);if(p&&(j||e!==void 0))A.showBorderEffect=0;j=k(j,ka(o,p?90:25)).split(O)[0];e=f.showplotborder==xa?xa:k(e,r,"80");r=k(r,za);t={opacity:Math.max(r,e)/100};if(W=Boolean(l(m.issliced,f.issliced,0)))c.preSliced=
W;s=l(m.dashed,G)?Na(k(m.dashlen,N),k(m.dashgap,F),h):void 0;A.data.push({showInLegend:d!==J,y:b,name:d,shadow:t,toolText:V(wa(m.tooltext)),color:this.getPointColor(o,r,q),_3dAlpha:r,borderColor:ra(j,e),borderWidth:h,link:wa(m.link),sliced:W,dashStyle:s,doNotSlice:k(f.enableslicing,Ja)!=Ja});r=z.percentValue(b/g*100);j=z.dataLabels(b)||J;t=x===1?r:j;b=l(m.showlabel,n)===1?d:J;r=(o=l(m.showvalue,T))===1?w===1?r:j:J;m=wa(V(m.displayvalue));r=m!==void 0&&o?m:r!==J&&b!==J?b+v+r:k(b,r);d=d!=J?d+E+t:t;
m=A.data[i];m.displayValue=r;m.toolText=k(m.toolText,d);i+=1}A.valueTotal=g;D.legend.enabled=f.showlegend==Ja?!0:!1;A.startAngle=l(f.startingangle,0);D.chart.startingAngle=k(Ka.length>1?f.startingangle:0,0);return A},getPointColor:function(a,A,d){var f,b,a=ca(a),A=Ha(A);d<100&&aa?(f=Math.floor((100-0.35*d)*85)/100,f=ha(a,f),b=Math.floor((100+d)*50)/100,a=ka(a,b),A={FCcolor:{color:a+O+f,alpha:A+O+A,ratio:d+",100",radialGradient:!0,gradientUnits:"userSpaceOnUse"}}):A={FCcolor:{color:a+O+a,alpha:A+O+
A,ratio:"0,100"}};return A},configureAxis:function(a){var A=0,d=a[X],f;a.plotOptions.series.dataLabels.style=a.xAxis.labels.style;a.plotOptions.series.dataLabels.color=a.xAxis.labels.style.color;delete d.x;delete d[0];delete d[1];a.chart.plotBorderColor=a.chart.plotBackgroundColor=Pa;d=d.pieDATALabels=[];if(a.series.length===1&&(f=a.series[0].data)&&(A=a.series[0].data.length)>0&&a.plotOptions.series.dataLabels.enabled)for(;A--;)f[A]&&wa(f[A].displayValue)!==void 0&&d.push(f[A].displayValue)},spaceManager:function(a,
A,d,f){var b=a[X],c=b.is3d,m=this.name,t=b.smartLabel,ia=l(b.pieDATALabels&&b.pieDATALabels.length,0),p=0,o=A.chart,r=l(o.managelabeloverflow,0),j=!b.preSliced&&o.enableslicing==xa&&(o.showlegend!=Ja||o.interactivelegend==xa)?0:l(o.slicingdistance,20),e=l(o.pieradius,0),g=l(o.enablesmartlabels,o.enablesmartlabel,1),i=g?l(o.skipoverlaplabels,o.skipoverlaplabel,1):0,h=l(o.issmartlineslanted,1),n=l(o.labeldistance,o.nametbdistance,5),q=l(o.smartlabelclearance,5);d-=a.chart.marginRight+a.chart.marginLeft;
var x=f-(a.chart.marginTop+a.chart.marginBottom),f=Math.min(x,d),T=k(o.smartlinecolor,M.plotFillColor[a.chart.paletteIndex]),I=l(o.smartlinealpha,100),w=l(o.smartlinethickness,0.7),E=a.plotOptions.series.dataLabels,v=E.style,u=l(parseInt(v.lineHeight,10),12),z=a.series[0]||{},W=z.pieYScale,s=z.pieSliceDepth,f=e===0?f*0.15:e,G=0,G=2*f;E.connectorWidth=w;E.connectorPadding=l(o.connectorpadding,5);E.connectorColor=ra(T,I);x-=Ya(a,A,d,G<x?x-G:x/2);o.showlegend==Ja&&(k(o.legendposition,Ua).toLowerCase()!=
Wa?x-=Za(a,A,d,x/2,!0):d-=$a(a,A,d/3,x,!0));t.setStyle(v);if(ia!==1)for(;ia--;)A=t.getOriSize(b.pieDATALabels[ia]),p=Math.max(p,A.width);g&&(n=q+j);e===0&&(c?(x-=s,G=Math.min(d/2-p,(x/2-u)/W)-n):G=Math.min(d/2-p,x/2-u)-n,G>=f?f=G:n=Math.max(n-(f-G),j));if(c&&(ia=x-2*(f*W+u),s>ia))z.managedPieSliceDepth=s-ia;a.plotOptions.pie3d.slicedOffset=a.plotOptions.pie.slicedOffset=j;a.plotOptions.pie3d.size=a.plotOptions.pie.size=2*f;a.plotOptions.series.dataLabels.distance=n;a.plotOptions.series.dataLabels.isSmartLineSlanted=
h;a.plotOptions.series.dataLabels.enableSmartLabels=g;a.plotOptions.series.dataLabels.skipOverlapLabels=i;a.plotOptions.series.dataLabels.manageLabelOverflow=r;if(m==="doughnut2d"||m==="doughnut3d")if(m=l(o.doughnutradius,0),ia=l(o.use3dlighting,1)?l(o.radius3d,o["3dradius"],50):100,ia>100&&(ia=100),ia<0&&(ia=0),o=m===0||m>=f?f/2:m,a.plotOptions.pie3d.innerSize=a.plotOptions.pie.innerSize=2*o,ia>0&&aa&&(o=parseInt(o/f*100,10),m=(100-o)/2,ia=parseInt(m*ia/100,10),o=o+O+ia+O+2*(m-ia)+O+ia,a.series[0]&&
a.series[0].data)){r=a.series[0].data;a=0;for(ia=r.length;a<ia;a+=1)if(m=r[a],m.color.FCcolor)m.color.FCcolor.ratio=o}},creditLabel:sa,eiMethods:{sliceDataItem:function(a){var A=this.jsVars.hcObj,d,f,b;if(A&&A.datasets&&(d=A.datasets[0])&&(f=d.data)&&(b=f.length)&&f[a=b-a-1]&&f[a].plot)return A.plotGraphicClick.call(f[a].plot)}}},ya);n.pie2d.eiMethods.togglePieSlice=n.pie2d.eiMethods.sliceDataItem;n.pie2d.eiMethods.enableSlicingMovement=n.pie2d.eiMethods.enablelink=function(){la.raiseWarning(this,
"1301081430","run","JSRenderer~enablelink()","Method deprecated.")};n("pie3d",{defaultSeriesType:"pie3d",rendererId:"pie3d",creditLabel:sa,getPointColor:function(a){return a},defaultPlotShadow:0},n.pie2d);n("doughnut2d",{getPointColor:function(a,A,d){var f,a=ca(a),A=Ha(A);d<100&&aa?(f=ha(a,U((85-0.2*(100-d))*100)/100),a=ka(a,U((100-0.5*d)*100)/100),A={FCcolor:{color:f+","+a+","+a+","+f,alpha:A+","+A+","+A+","+A,radialGradient:!0,gradientUnits:"userSpaceOnUse",r:d}}):A={FCcolor:{color:a+","+a,alpha:A+
","+A,ratio:"0,100"}};return A}},n.pie2d);n("doughnut3d",{defaultSeriesType:"pie3d",rendererId:"pie3d",getPointColor:n.pie3d,defaultPlotShadow:0},n.doughnut2d);n("pareto2d",{standaloneInit:!0,point:function(a,A,d,f,b){var c,m,t,e,p,o,r,j,g,i,H,n,h,q,x,a=d.length,T=0;o={};h=b.chart.paletteIndex;var I=/3d$/.test(b.chart.defaultSeriesType),W=this.isBar,E=k(360-f.plotfillangle,90),v=l(f.plotborderthickness,1),u=b.chart.useRoundEdges,z=k(f.tooltipsepchar,", "),s=k(f.plotbordercolor,M.plotBorderColor[h]).split(O)[0],
w=f.showplotborder==xa?xa:k(f.plotborderalpha,f.plotfillalpha,za),G=b.xAxis,N=l(f.showcumulativeline,1),F=b[X],L=F.axisGridManager,B=F.x,S=f.showtooltip!=xa,P=[],K=[],y=l(f.use3dlighting,1),C=b[X].numberFormatter,ma=l(f.showlinevalues,f.showvalues),Q=l(f.plotborderdashed,0),R=l(f.plotborderdashlen,5),pa=l(f.plotborderdashgap,4),w=I?f.showplotborder?w:xa:w,s=I?k(f.plotbordercolor,"#FFFFFF"):s;for(n=m=0;m<a;m+=1)if(H=d[m],d[m].vline)L.addVline(G,H,n,b);else if(c=C.getCleanValue(H.value,!0),c!==null)H.value=
c,P.push(H),n+=1;a=P.length;P.sort(function(a,d){return d.value-a.value});if(N)r=l(f.linedashed,0),q=ca(k(f.linecolor,M.plotBorderColor[h])),m=k(f.linealpha,100),j=l(f.linedashlen,5),g=l(f.linedashgap,4),o=l(f.linethickness,2),i={opacity:m/100},x=l(f.drawanchors,f.showanchors),x===void 0&&(x=m!=xa),t=l(f.anchorborderthickness,1),p=l(f.anchorsides,0),e=l(f.anchorradius,3),n=ca(k(f.anchorbordercolor,q)),c=ca(k(f.anchorbgcolor,M.anchorBgColor[h])),d=Ha(k(f.anchoralpha,za)),H=Ha(k(f.anchorbgalpha,d))*
d/100,r=r?Na(j,g,o):void 0,o={yAxis:1,data:[],type:"line",color:{FCcolor:{color:q,alpha:m}},lineWidth:o,marker:{enabled:x,fillColor:{FCcolor:{color:c,alpha:H}},lineColor:{FCcolor:{color:n,alpha:d}},lineWidth:t,radius:e,symbol:ab(p),startAngle:k(f.anchorstartangle,90)}};else{if(f.showsecondarylimits!=="1")f.showsecondarylimits="0";if(f.showdivlinesecondaryvalue!=="1")f.showdivlinesecondaryvalue="0"}for(m=0;m<a;m+=1)H=P[m],c=l(H.showlabel,f.showlabels,1),d=V(!c?J:Ea(H.label,H.name)),L.addXaxisCat(G,
m,m,d),T+=c=H.value,t=k(H.color,b.colors[m%b.colors.length])+O+(l(f.useplotgradientcolor,1)?Qa(f.plotgradientcolor,M.plotGradientColor[h]):J),e=k(H.alpha,f.plotfillalpha,za),p=k(H.ratio,f.plotfillratio),n={opacity:e/100},q=k(H.alpha,w)+J,t=Y(t,e,p,E,u,s,q,W,I),A.data.push(ua(this.getPointStub(H,c,d,b),{y:c,shadow:n,color:t[0],borderColor:t[1],borderWidth:v,use3DLighting:y,dashStyle:l(H.dashed,Q)==1?Na(R,pa,v):"",tooltipConstraint:this.tooltipConstraint})),this.pointValueWatcher(b,c),N&&K.push({value:T,
dataLabel:d,tooltext:wa(H.tooltext)});B.catCount=a;F[1]||(F[1]={});F[1].stacking100Percent=!0;if(N&&T>0){m=0;for(a=K.length;m<a;m+=1)H=K[m],b=A.data[m],c=H.value/T*100,h=C.percentValue(c),f=b.displayValue!==J?h:J,ma==1&&(f=h),ma==0&&(f=J),d=H.dataLabel,h=S?H.tooltext!==void 0?H.tooltext:(d!==J?d+z:J)+h:J,o.data.push({shadow:i,color:o.color,marker:o.marker,y:c,toolText:h,displayValue:f,link:b.link,dashStyle:r});return[A,o]}else return A},defaultSeriesType:"column",isDual:!0,creditLabel:sa,rendererId:"cartesian"},
ya);n("pareto3d",{defaultSeriesType:"column3d",defaultPlotShadow:1,is3D:!0},n.pareto2d);n("mscolumn2d",{standaloneInit:!0,creditLabel:sa,rendererId:"cartesian"},n.mscolumn2dbase);n("mscolumn3d",{defaultSeriesType:"column3d",defaultPlotShadow:1,is3D:!0,defaultZeroPlaneHighlighted:!1},n.mscolumn2d);n("msbar2d",{isBar:!0,defaultSeriesType:"bar",spaceManager:n.barbase},n.mscolumn2d);n("msbar3d",{defaultSeriesType:"bar3d",defaultPlotShadow:1,is3D:!0,defaultZeroPlaneHighlighted:!1},n.msbar2d);n("msline",
{standaloneInit:!0,creditLabel:sa,rendererId:"cartesian"},n.mslinebase);n("msarea",{standaloneInit:!0,creditLabel:sa,rendererId:"cartesian"},n.msareabase);n("stackedcolumn2d",{isStacked:!0},n.mscolumn2d);n("stackedcolumn3d",{isStacked:!0},n.mscolumn3d);n("stackedbar2d",{isStacked:!0},n.msbar2d);n("stackedbar3d",{isStacked:!0},n.msbar3d);n("stackedarea2d",{isStacked:!0,areaAlpha:100,showSum:0},n.msarea);n("marimekko",{isValueAbs:!0,distributedColumns:!0,isStacked:!0,xAxisMinMaxSetter:Ga,postSeriesAddition:function(a,
b){var d=a[X],f=0,D=a.xAxis,c=100/d.marimekkoTotal,m=[],t=a.series,e=0,p=l(b.chart.plotborderthickness,1),o=a.chart.rotateValues,r=l(b.chart.rotatexaxispercentvalues,0),p=p*-0.5-(p%2+(r?0:4)),j=r?3:0,g=o?270:0,i=ua({},a.plotOptions.series.dataLabels.style),H=parseInt(i.fontSize,10),h=d[0],n=h.stacking100Percent,q=!n,x=d.inCanvasStyle,T=this.numberFormatter,I=b.categories&&b.categories[0]&&b.categories[0].category||[],k=0,E=[],v,u,z,w,s,G,N,F;d.isXYPlot=!0;d.distributedColumns=!0;D.min=0;D.max=100;
D.labels.enabled=!1;D.gridLineWidth=0;D.alternateGridColor=Pa;v=h.stack;b.chart.interactivelegend="0";h=0;for(u=a.xAxis.plotLines.length;h<u;h+=1)if(z=D.plotLines[h],z.isGrid)z.isCat=!0,m[z.value]=z,z._hideLabel=!0;for(h=u=0;h<I.length;h+=1)I[h].vline||(k+=E[u]=T.getCleanValue(I[h].widthpercent||0),u+=1);D=v.floatedcolumn&&v.floatedcolumn[0]||[];if(k===100&&(D&&D.length)!==u)for(;u--;)D[u]||(D[u]={p:null});k=B(k);if(D){w=0;for(u=D.length;w<u;){F=D[w];f+=z=F&&F.p||0;G=k===100?E[w]:z*c;s=e+G/2;N=e+
G;for(h=0;h<t.length;h+=1)if(I=a.series[h].data[w],I._FCX=e,I._FCW=G,n){if(I.y||I.y===0){v=I.y/z*100;I.y=v;if(I.showPercentValues)I.displayValue=this.numberFormatter.percentValue(v);if(I.showPercentInToolTip)I.toolText=I.toolText+parseInt(v*100,10)/100+"%"}if(I.previousY||I.previousY===0)I.previousY=I.previousY/z*100}d.showStackTotal&&a.xAxis.plotLines.push({value:s,width:0,isVline:q,isTrend:!q,_isStackSum:1,zIndex:4,label:{align:Sa,textAlign:g,rotation:o?270:0,style:i,verticalAlign:Va,offsetScale:q?
z<0?F.n:F.p:void 0,offsetScaleIndex:0,y:z<0?o===270?4:H:-4,x:0,text:T.yAxis(Fa(z,10))}});if(m[w])m[w].value=s,m[w]._weight=G,m[w]._hideLabel=!1;w+=1;d.showXAxisPercentValues&&w<u&&a.xAxis.plotLines.push({value:N,width:0,isVine:!0,label:{align:Sa,textAlign:r?Xa:Sa,rotation:r?270:0,backgroundColor:"#ffffff",backgroundOpacity:1,borderWidth:"1px",borderType:"solid",borderColor:x.color,style:{color:x.color,fontSize:x.fontSize,fontFamily:x.fontFamily,lineHeight:x.lineHeight},verticalAlign:Ua,y:p,x:j,text:this.numberFormatter.percentValue(N)},
zIndex:5});e=N}}w=0;for(u=m.length;w<u;w+=1)if(m[w]&&m[w]._hideLabel)m[w].value=null},defaultSeriesType:"floatedcolumn"},n.stackedcolumn2d);n("msstackedcolumn2d",{series:function(a,b,d){var f,D,c,m,t=b[X],e=0,p,o;p=[];var r;b.legend.enabled=Boolean(l(a.chart.showlegend,1));if(a.dataset&&a.dataset.length>0){this.categoryAdder(a,b);f=0;for(D=a.dataset.length;f<D;f+=1)if(r=a.dataset[f].dataset){c=0;for(m=r.length;c<m;c+=1,e+=1)p={visible:!!l(r.visible,1),data:[],numColumns:D,columnPosition:f},o=Math.min(t.oriCatTmp.length,
r[c].data&&r[c].data.length),p=this.point(d,p,r[c],a.chart,b,o,e,f),b.series.push(p)}if(this.isDual&&a.lineset&&a.lineset.length>0){c=0;for(m=a.lineset.length;c<m;c+=1,e+=1)p={visible:!!l(a.lineset[c].visible,1),data:[],yAxis:1,type:"line"},d=a.lineset[c],o=Math.min(t.oriCatTmp.length,d.data&&d.data.length),b.series.push(n.msline.point.call(this,"msline",p,d,a.chart,b,o,e))}this.configureAxis(b,a);a.trendlines&&Ma(a.trendlines,b.yAxis,b[X],this.isDual,this.isBar)}},postSpaceManager:function(a,b,d){var j;
var f=a[X],D,c,m;if(this.isStacked&&f.showStackTotal&&(D=a.chart,j=(b=a.xAxis)&&b.plotLines,a=j,D=d-D.marginLeft-D.marginRight,d=f.plotSpacePercent,f=f[0].stack,f=f.column&&f.column.length,b=D/(b.max-b.min),b*((1-2*d)/f)>50&&d==0.1)){b=50/b;d=a&&a.length;f=-((f-1)/2)*b;for(m=0;m<d;m+=1)if(c=a[m],c._isStackSum)D=c._catPosition+(f+b*c._stackIndex),c.value=D}}},n.stackedcolumn2d);n("mscombi2d",{standaloneInit:!0,creditLabel:sa,rendererId:"cartesian"},n.mscombibase);n("mscombi3d",{series:n.mscombi2d.series,
eiMethods:function(a){var b={};va(a.split(","),function(a){b[a]=function(){la.raiseWarning(this,"1301081430","run","JSRenderer~"+a+"()","Method not applicable.")}});return b}("view2D,view3D,resetView,rotateView,getViewAngles,fitToStage")},n.mscolumn3d);n("mscolumnline3d",{},n.mscombi3d);n("stackedcolumn2dline",{isStacked:!0,stack100percent:0},n.mscombi2d);n("stackedcolumn3dline",{isStacked:!0,stack100percent:0},n.mscombi3d);n("mscombidy2d",{isDual:!0,secondarySeriesType:void 0},n.mscombi2d);n("mscolumn3dlinedy",
{isDual:!0,secondarySeriesType:"line"},n.mscolumnline3d);n("stackedcolumn3dlinedy",{isDual:!0,secondarySeriesType:"line"},n.stackedcolumn3dline);n("msstackedcolumn2dlinedy",{isDual:!0,stack100percent:0,secondarySeriesType:"line"},n.msstackedcolumn2d);n("scrollcolumn2d",{postSeriesAddition:n.scrollbase.postSeriesAddition,tooltipConstraint:"plot",canvasborderthickness:1,avgScrollPointWidth:40},n.mscolumn2d);n("scrollline2d",{postSeriesAddition:n.scrollbase.postSeriesAddition,tooltipConstraint:"plot",
canvasborderthickness:1,avgScrollPointWidth:75},n.msline);n("scrollarea2d",{postSeriesAddition:n.scrollbase.postSeriesAddition,tooltipConstraint:"plot",canvasborderthickness:1,avgScrollPointWidth:75},n.msarea);n("scrollstackedcolumn2d",{postSeriesAddition:function(a,b,d,f){n.base.postSeriesAddition.call(this,a,b,d,f);n.scrollbase.postSeriesAddition.call(this,a,b,d,f)},canvasborderthickness:1,tooltipConstraint:"plot",avgScrollPointWidth:75},n.stackedcolumn2d);n("scrollcombi2d",{postSeriesAddition:n.scrollbase.postSeriesAddition,
tooltipConstraint:"plot",canvasborderthickness:1,avgScrollPointWidth:40},n.mscombi2d);n("scrollcombidy2d",{postSeriesAddition:n.scrollbase.postSeriesAddition,tooltipConstraint:"plot",canvasborderthickness:1,avgScrollPointWidth:40},n.mscombidy2d);n("scatter",{standaloneInit:!0,defaultSeriesType:"scatter",defaultZeroPlaneHighlighted:!1,creditLabel:sa},n.scatterbase);n("bubble",{standaloneInit:!0,standaloneInut:!0,defaultSeriesType:"bubble",rendererId:"bubble",point:function(a,b,d,f,D,c,m){if(d.data){var t,
e,p,o,r,j,g,i,h,T,w=!1,q,x,a=n[a],c=d.data,s=c.length,I=l(d.showvalues,D[X].showValues);p=l(f.bubblescale,1);var W=k(f.negativecolor,"FF0000"),E=D.plotOptions.bubble,v=this.numberFormatter,u=l(d.showregressionline,f.showregressionline,0);E.bubbleScale=p;b.name=wa(d.seriesname);if(l(d.includeinlegend)===0||b.name===void 0)b.showInLegend=!1;p=Boolean(l(d.drawanchors,d.showanchors,f.drawanchors,1));g=k(d.plotfillalpha,d.bubblefillalpha,f.plotfillalpha,za);i=l(d.showplotborder,f.showplotborder,1);h=ca(k(d.plotbordercolor,
f.plotbordercolor,"666666"));t=k(d.plotborderthickness,f.plotborderthickness,1);T=k(d.plotborderalpha,f.plotborderalpha,"95");i=i==1?t:0;m=k(d.color,d.plotfillcolor,f.plotfillcolor,D.colors[m%D.colors.length]);b.marker={enabled:p,fillColor:this.getPointColor(m,za),lineColor:{FCcolor:{color:h,alpha:T}},lineWidth:i,symbol:"circle"};if(u){b.events={hide:this.hideRLine,show:this.showRLine};var z={sumX:0,sumY:0,sumXY:0,sumXsqure:0,sumYsqure:0,xValues:[],yValues:[]},B=l(d.showyonx,f.showyonx,1),K=ca(k(d.regressionlinecolor,
f.regressionlinecolor,m)),G=l(d.regressionlinethickness,f.regressionlinethickness,1);t=Ha(l(d.regressionlinealpha,f.regressionlinealpha,100));K=ra(K,t)}for(e=0;e<s;e+=1)if(o=c[e])if(t=v.getCleanValue(o.y),q=v.getCleanValue(o.x),x=v.getCleanValue(o.z,!0),t===null)b.data.push({y:null,x:q});else{w=!0;r=ca(k(o.color,o.z<0?W:m));j=k(o.alpha,g);o=a.getPointStub(o,t,q,D,d,I);r=l(f.use3dlighting)===0?r:a.getPointColor(r,j);if(x!==null)E.zMax=E.zMax>x?E.zMax:x,E.zMin=E.zMin<x?E.zMin:x;b.data.push({y:t,x:q,
z:x,displayValue:o.displayValue,toolText:o.toolText,link:o.link,marker:{enabled:p,fillColor:r,lineColor:{FCcolor:{color:h,alpha:T}},lineWidth:i,symbol:"circle"}});this.pointValueWatcher(D,t,q,u&&z)}else b.data.push({y:null});u&&(d={type:"line",color:K,showInLegend:!1,lineWidth:G,enableMouseTracking:!1,marker:{enabled:!1},data:this.getRegressionLineSeries(z,B,s),zIndex:0},b=[b,d])}if(!w)b.showInLegend=!1;return b},postSeriesAddition:function(a,b){a.chart.clipBubbles=l(b.chart.clipbubbles,1)},getPointStub:function(a,
b,d,f,D,c){var f=f[X],b=b===null?b:f.numberFormatter.dataLabels(b),m,t=f.tooltipSepChar;f.showTooltip?wa(a.tooltext)!==void 0?D=V(a.tooltext):b===null?D=!1:(f.seriesNameInToolTip&&(m=k(D&&D.seriesname)),D=m?m+t:J,D+=d?d+t:J,D+=b,D+=a.z?t+a.z:J):D=J;d=l(a.showvalue,c,f.showValues)?k(a.displayvalue,a.name,a.label)!==void 0?V(k(a.displayvalue,a.name,a.label)):b:J;a=wa(a.link);return{displayValue:d,toolText:D,link:a}}},n.scatter);n("ssgrid",{standaloneInit:!0,defaultSeriesType:"ssgrid",rendererId:"ssgrid",
chart:function(a,b){var z;var d=this.containerElement,f=this.dataObj,D=this.chartInstance,f=ua({},f);f.chart=f.chart||f.graph||{};delete f.graph;var c,m,t,e=0,p,o,r=[],j=f.chart,g=f.data,i=g&&g.length,f=this.smartLabel,h=this.numberFormatter,T=d.offsetHeight,w=d.offsetWidth,q={},x=0,s=0,I=(j.palette>0&&j.palette<6?j.palette:l(this.paletteIndex,1))-1,d={_FCconf:{0:{stack:{}},1:{stack:{}},x:{stack:{}},noWrap:!1,marginLeftExtraSpace:0,marginRightExtraSpace:0,marginBottomExtraSpace:0,marginTopExtraSpace:0,
marimekkoTotal:0},chart:{renderTo:d,ignoreHiddenSeries:!1,events:{},spacingTop:0,spacingRight:0,spacingBottom:0,spacingLeft:0,marginTop:0,marginRight:0,marginBottom:0,marginLeft:0,borderRadius:0,borderColor:"#000000",borderWidth:1,defaultSeriesType:"ssgrid",style:{fontFamily:k(j.basefont,"Verdana"),fontSize:Ia(j.basefontsize,20)+Ra,color:k(j.basefontcolor,M.baseFontColor[I]).replace(/^#?([a-f0-9]+)/ig,"#$1")},plotBackgroundColor:Pa},labels:{smartLabel:f},colors:["AFD8F8","F6BD0F","8BBA00","FF8E46",
"008E8E","D64646","8E468E","588526","B3AA00","008ED6","9D080D","A186BE","CC6600","FDC689","ABA000","F26D7D","FFF200","0054A6","F7941C","CC3300","006600","663300","6DCFF6"],credits:{href:"http://www.fusioncharts.com?BS=FCHSEvalMark",text:y.CREDIT_STRING,enabled:this.creditLabel},legend:{enabled:!1},series:[],subtitle:{text:J},title:{text:J},tooltip:{enabled:!1},exporting:{buttons:{exportButton:{},printButton:{enabled:!1}}}},W=d[X],E=d.colors,v=d.colors.length,u=p=m=x=0,s=e=o=0;t=D.jsVars.cfgStore;
D=d.chart;Aa(d.chart.style);D.events.click=this.linkClickFN;m=D.toolbar={button:{}};p=m.button;p.scale=l(j.toolbarbuttonscale,1.15);p.width=l(j.toolbarbuttonwidth,15);p.height=l(j.toolbarbuttonheight,15);p.radius=l(j.toolbarbuttonradius,2);p.spacing=l(j.toolbarbuttonspacing,5);p.fill=ra(k(j.toolbarbuttoncolor,"ffffff"));p.labelFill=ra(k(j.toolbarlabelcolor,"cccccc"));p.symbolFill=ra(k(j.toolbarsymbolcolor,"ffffff"));p.hoverFill=ra(k(j.toolbarbuttonhovercolor,"ffffff"));p.stroke=ra(k(j.toolbarbuttonbordercolor,
"bbbbbb"));p.symbolStroke=ra(k(j.toolbarsymbolbordercolor,"9a9a9a"));p.strokeWidth=l(j.toolbarbuttonborderthickness,1);p.symbolStrokeWidth=l(j.toolbarsymbolborderthickness,1);o=p.symbolPadding=l(j.toolbarsymbolpadding,5);p.symbolHPadding=l(j.toolbarsymbolhpadding,o);p.symbolVPadding=l(j.toolbarsymbolvpadding,o);o=m.position=k(j.toolbarposition,"tr").toLowerCase();switch(o){case "tr":case "tl":case "br":case "bl":break;default:o="tr"}p=m.hAlign=(J+j.toolbarhalign).toLowerCase()==="left"?"l":o.charAt(1);
z=m.vAlign=(J+j.toolbarvalign).toLowerCase()==="bottom"?"b":o.charAt(0),o=z;m.hDirection=l(j.toolbarhdirection,p==="r"?-1:1);m.vDirection=l(j.toolbarvdirection,o==="b"?-1:1);m.vMargin=l(j.toolbarvmargin,6);m.hMargin=l(j.toolbarhmargin,10);m.x=l(j.toolbarx,p==="l"?0:a);m.y=l(j.toolbary,o==="t"?0:b);if(k(j.clickurl)!==void 0)D.link=j.clickurl,D.style.cursor="pointer";q.showPercentValues=l(t.showpercentvalues,j.showpercentvalues,0);q.numberItemsPerPage=k(t.numberitemsperpage,j.numberitemsperpage);q.showShadow=
l(t.showshadow,j.showshadow,0);q.baseFont=k(t.basefont,j.basefont,"Verdana");c=Ia(t.basefontsize,j.basefontsize,10);q.baseFontSize=c+Ra;q.baseFontColor=ca(k(t.basefontcolor,j.basefontcolor,M.baseFontColor[I]));q.alternateRowBgColor=ca(k(t.alternaterowbgcolor,j.alternaterowbgcolor,M.altHGridColor[I]));q.alternateRowBgAlpha=k(t.alternaterowbgalpha,j.alternaterowbgalpha,M.altHGridAlpha[I])+J;q.listRowDividerThickness=l(t.listrowdividerthickness,j.listrowdividerthickness,1);q.listRowDividerColor=ca(k(t.listrowdividercolor,
j.listrowdividercolor,M.borderColor[I]));q.listRowDividerAlpha=l(t.listrowdivideralpha,j.listrowdivideralpha,M.altHGridAlpha[I])+15+J;q.colorBoxWidth=l(t.colorboxwidth,j.colorboxwidth,8);q.colorBoxHeight=l(t.colorboxheight,j.colorboxheight,8);q.navButtonRadius=l(t.navbuttonradius,j.navbuttonradius,7);q.navButtonColor=ca(k(t.navbuttoncolor,j.navbuttoncolor,M.canvasBorderColor[I]));q.navButtonHoverColor=ca(k(t.navbuttonhovercolor,j.navbuttonhovercolor,M.altHGridColor[I]));q.textVerticalPadding=l(t.textverticalpadding,
j.textverticalpadding,3);q.navButtonPadding=l(t.navbuttonpadding,j.navbuttonpadding,5);q.colorBoxPadding=l(t.colorboxpadding,j.colorboxpadding,10);q.valueColumnPadding=l(t.valuecolumnpadding,j.valuecolumnpadding,10);q.nameColumnPadding=l(t.namecolumnpadding,j.namecolumnpadding,5);q.borderThickness=l(t.borderthickness,j.borderthickness,1);q.borderColor=ca(k(t.bordercolor,j.bordercolor,M.borderColor[I]));q.borderAlpha=k(t.borderalpha,j.borderalpha,M.borderAlpha[I])+J;q.bgColor=k(t.bgcolor,j.bgcolor,
"FFFFFF");q.bgAlpha=k(t.bgalpha,j.bgalpha,za);q.bgRatio=k(t.bgratio,j.bgratio,za);q.bgAngle=k(t.bgangle,j.bgangle,xa);D.borderRadius=q.borderThickness/16;D.borderWidth=q.borderThickness;D.borderColor=Z({FCcolor:{color:q.borderColor,alpha:q.borderAlpha}});D.backgroundColor={FCcolor:{color:q.bgColor,alpha:q.bgAlpha,ratio:q.bgRatio,angle:q.bgAngle}};D.borderRadius=l(j.borderradius,0);t={fontFamily:q.baseFont,fontSize:q.baseFontSize,color:q.baseFontColor};Aa(t);f.setStyle(t);for(e=0;e<i;e+=1)if(c=g[e],
p=h.getCleanValue(c.value),o=V(Ea(c.label,c.name)),m=ca(k(c.color,E[e%v])),k(c.alpha,j.plotfillalpha,za),o!=J||p!=null)r.push({value:p,label:o,color:m}),x+=p,s+=1;for(e=0;e<s;e+=1)c=r[e],p=c.value,c.dataLabel=c.label,c.displayValue=q.showPercentValues?h.percentValue(p/x*100):h.dataLabels(p),g=f.getOriSize(c.displayValue),u=Math.max(u,g.width+q.valueColumnPadding);q.numberItemsPerPage?q.numberItemsPerPage>=s?(q.numberItemsPerPage=s,p=T/q.numberItemsPerPage,m=s):(h=T,h-=2*(q.navButtonPadding+q.navButtonRadius),
m=q.numberItemsPerPage,p=h/m):(x=parseInt(t.lineHeight,10),x+=2*q.textVerticalPadding,x=Math.max(x,q.colorBoxHeight),T/x>=s?(p=T/s,m=s):(h=T,h-=2*(q.navButtonPadding+q.navButtonRadius),m=Math.floor(h/x),p=h/m));o=w-q.colorBoxPadding-q.colorBoxWidth-q.nameColumnPadding-u-q.valueColumnPadding;e=q.colorBoxPadding+q.colorBoxWidth+q.nameColumnPadding;h=k(j.basefont,"Verdana");g=Ia(j.basefontsize,10);I=k(j.basefontcolor,M.baseFontColor[I]);i=k(j.outcnvbasefont,h);c=Ia(j.outcnvbasefontsize,g);u=c+Ra;j=k(j.outcnvbasefontcolor,
I).replace(/^#?([a-f0-9]+)/ig,"#$1");g+=Ra;I=I.replace(/^#?([a-f0-9]+)/ig,"#$1");W.trendStyle=W.outCanvasStyle={fontFamily:i,color:j,fontSize:u};Aa(W.trendStyle);W.inCanvasStyle={fontFamily:h,fontSize:g,color:I};d.tooltip.style={fontFamily:h,fontSize:g,lineHeight:void 0,color:I};d.tooltip.shadow=!1;D.height=T;D.width=w;D.rowHeight=p;D.labelX=e;D.colorBoxWidth=q.colorBoxWidth;D.colorBoxHeight=q.colorBoxHeight;D.colorBoxX=q.colorBoxPadding;D.valueX=q.colorBoxPadding+q.colorBoxWidth+q.nameColumnPadding+
o+q.valueColumnPadding;D.valueColumnPadding=q.valueColumnPadding;D.textStyle=t;D.listRowDividerAttr={"stroke-width":q.listRowDividerThickness,stroke:{FCcolor:{color:q.listRowDividerColor,alpha:q.listRowDividerAlpha}}};D.alternateRowColor={FCcolor:{color:q.alternateRowBgColor,alpha:q.alternateRowBgAlpha}};D.navButtonRadius=q.navButtonRadius;D.navButtonPadding=q.navButtonPadding;D.navButtonColor=q.navButtonColor;D.navButtonHoverColor=q.navButtonHoverColor;D.lineHeight=parseInt(t.lineHeight,10);j=[];
T=0;q=!0;for(e=0;e<s&m!=0;e+=1)e%m==0&&(j.push({data:[],visible:q}),q=!1,T+=1),c=r[e],w=f.getSmartText(c.dataLabel,o,p),j[T-1].data.push({label:w.text,originalText:w.tooltext,displayValue:c.displayValue,y:c.value,color:c.color});d.series=j;n.base.parseExportOptions.call(this,d);d.tooltip.enabled=!!d.exporting.enabled;return d},creditLabel:sa},n.base);n("renderer.bubble",{drawPlotBubble:function(a,c){var d=this,f=d.options,D=f.chart,e=f.plotOptions.series,m=d.paper,t=d.elements,g=a.items,p=a.graphics=
a.graphics||[],o=d.xAxis[c.xAxis||0],r=d.yAxis[c.yAxis||0],j=a.data,i=(f.tooltip||{}).enabled!==!1,e=isNaN(+e.animation)&&e.animation.duration||e.animation*1E3,h=c.visible===!1?"hidden":"visible",f=f.plotOptions.bubble,n=f.zMax,f=f.bubbleScale,T=s(d.canvasHeight,d.canvasWidth)/8,n=R(n),w,q,x,k,I,W,E,v,u,z,K=d.layers,S=K.dataset=K.dataset||m.group("dataset-orphan");K.datalabels=K.datalabels||m.group("datalables").insertAfter(S);var K=K.tracker,G,N,S=S.bubble=S.bubble||m.group("bubble",S);D.clipBubbles&&
!S.attrs["clip-rect"]&&S.attr({"clip-rect":t["clip-canvas"]});t=0;for(w=j.length;t<w;t+=1){q=j[t];u=z=N=null;v=q.marker;if(q.y!==null&&v&&v.enabled){x=q.link;D=q.toolText;k=l(q.x,t);I=q.y;E=r.getAxisPosition(I);W=o.getAxisPosition(k);u=R(q.z);G=B(u*T/n)*f;u=m.circle(W,E,0,S).attr({fill:Z(v.fillColor),"stroke-width":v.lineWidth,stroke:Z(v.lineColor),visibility:h}).animate({r:G||0},e,"easeOut");if(x||i)G<qa&&(G=qa),z=m.circle(W,E,G,K).attr({cursor:x?"pointer":"",stroke:b,"stroke-width":v.lineWidth,
fill:b,ishot:!!x,visibility:h}).tooltip(D).data("link",x).click(function(){var a=this.data("link");a&&d.linkClickFN.call({link:a},d)});g[t]={index:t,x:k,y:I,z:q.z,value:I,graphic:u,dataLabel:N,tracker:z};N=d.drawPlotLineLabel(a,c,t,W,E)}else g[t]={index:t,x:k,y:I};N&&p.push(N);u&&p.push(u);z&&p.push(z)}a.visible=c.visible!==!1;return a}},n["renderer.cartesian"]);n("renderer.ssgrid",{drawGraph:function(){var a=this.options.series,b=this.elements,d=b.plots,f=a.length,c;if(!d)d=this.plots=this.plots||
[],b.plots=d;this.drawSSGridNavButton();for(c=0;c<f;c++){if(!(b=d[c]))d.push(b={items:[],data:a[c].data});a[c].data&&a[c].data.length&&this.drawPlot(b,a[c])}f>1&&this.nenagitePage(0)},drawPlot:function(a){var b=a.data,d=this.paper,f=this.options.chart,c=f.colorBoxHeight,g=f.colorBoxWidth,m=f.colorBoxX,t=f.labelX,h=f.valueX,p=f.rowHeight,o=f.width,r=f.listRowDividerAttr,j=r["stroke-width"],r=Z(r.stroke),n=j%2/2,T=f.textStyle,H=this.layers,H=H.dataset=H.dataset||d.group("dataset-orphan"),f=Z(f.alternateRowColor),
a=a.items,l=0,w,q,x,s;if(!b||!b.length)b=[];r={stroke:r,"stroke-width":j};s=0;for(j=b.length;s<j;s+=1)if(x=b[s],q=x.y,w=a[s]={index:s,value:q,graphic:null,dataLabel:null,dataValue:null,alternateRow:null,listRowDivider:null,hot:null},!(q===null||q===void 0)){if(s%2===0)w.alternateRow=d.rect(0,l,o,p,0,H).attr({fill:f,"stroke-width":0});q=B(l)+n;w.listRowDivider=d.path([e,0,q,i,o,q],H).attr(r);w.graphic=d.rect(m,l+p/2-c/2,g,c,0,H).attr({fill:x.color,"stroke-width":0,stroke:"#000000"});q=w.dataLabel=
d.text().attr({text:x.label,title:x.originalText||"",x:t,y:l+p/2,fill:T.color,"text-anchor":"start"}).css(T);H.appendChild(q);w=w.dataValue=d.text().attr({text:x.displayValue,title:x.originalText||"",x:h,y:l+p/2,fill:T.color,"text-anchor":"start"}).css(T);H.appendChild(w);l+=p}q=B(l)+n;d.path([e,0,q,i,o,q],H).attr(r)},drawSSGridNavButton:function(a){var a=this,b=a.paper,d=a.options,f=d.chart,c=d.series,g=f.navButtonColor,m=f.navButtonHoverColor,d=f.navButtonRadius,t=d*0.67,h=f.navButtonPadding+t+
(c&&c[0].data&&c[0].data.length*f.rowHeight)+d*0.5,f=f.width-20,p,o,r;if(c.length>1){var j=a.naviigator=b.group("navigation");a.navElePrv=c=b.group(j);p=b.path([e,20,h,i,20+d+t,h-t,20+d,h,20+d+t,h+t,"Z"]).attr({fill:g,"stroke-width":0,cursor:"pointer"});c.appendChild(p);r=b.circle(20+d,h,d).attr({fill:Pa,"stroke-width":0,cursor:"pointer"}).mouseover(function(){p.attr({fill:m,cursor:"pointer"})}).mouseout(function(){p.attr({fill:g})}).click(function(){a.nenagitePage(-1)});c.appendChild(r);a.navEleNxt=
c=b.group(j);o=b.path([e,f,h,i,f-d-t,h-t,f-d,h,f-d-t,h+t,"Z"]).attr({fill:g,"stroke-width":0,cursor:"pointer"});c.appendChild(o);b=b.circle(f-d,h,d).attr({fill:Pa,"stroke-width":0,cursor:"pointer"}).mouseover(function(){o.attr({fill:m})}).mouseout(function(){o.attr({fill:g})}).click(function(){a.nenagitePage(1)});c.appendChild(b)}},nenagitePage:function(a){var b=this.plots,d=b.length,a=(this.currentSeriesIndex||0)+(a||0),f;if(b[a]){for(f=d;f--;)va(b[f].items,function(a){a.graphic&&a.graphic.hide();
a.dataLabel&&a.dataLabel.hide();a.dataValue&&a.dataValue.hide();a.alternateRow&&a.alternateRow.hide();a.listRowDivider&&a.listRowDivider.hide()});va(b[a].items,function(a){a.graphic&&a.graphic.show();a.dataLabel&&a.dataLabel.show();a.dataValue&&a.dataValue.show();a.alternateRow&&a.alternateRow.show();a.listRowDivider&&a.listRowDivider.show()});this.currentSeriesIndex=a;a===0?this.navElePrv.hide():this.navElePrv.show();a===d-1?this.navEleNxt.hide():this.navEleNxt.show()}}},n["renderer.root"]);Da.prototype=
{getArcPath:function(a,b,d,f,c,e,m,t,h,p){return d==c&&f==e?[]:[g,m,t,0,p,h,c,e]},parseColor:function(a,b){var d,f,c,e,m,t,g,p,o,r,j=b/2,h,i,n,T,l;l=3;this.use3DLighting?(d=ha(a,80),f=ha(a,75),t=ka(a,85),g=ka(a,70),p=ka(a,40),o=ka(a,50),ka(a,30),r=ka(a,65),ha(a,85),c=ha(a,69),e=ha(a,75),m=ha(a,95)):(l=10,d=ha(a,90),f=ha(a,87),t=ka(a,93),g=ka(a,87),p=ka(a,80),r=o=ka(a,85),ka(a,80),m=ha(a,85),c=ha(a,75),e=ha(a,80));h=f+O+t+O+g+O+t+O+f;n=b+O+b+O+b+O+b+O+b;i=f+O+a+O+t+O+a+O+f;T=j+O+j+O+j+O+j+O+j;p=f+
O+a+O+p+O+a+O+f;c=e+O+t+O+o+O+t+O+c;e="FFFFFF"+O+"FFFFFF"+O+"FFFFFF"+O+"FFFFFF"+O+"FFFFFF";l=0+O+j/l+O+b/l+O+j/l+O+0;return{frontOuter:{FCcolor:{gradientUnits:"userSpaceOnUse",x1:this.leftX,y1:0,x2:this.rightX,y2:0,color:c,alpha:n,angle:0,ratio:"0,20,15,15,50"}},backOuter:{FCcolor:{gradientUnits:"userSpaceOnUse",x1:this.leftX,y1:0,x2:this.rightX,y2:0,color:p,alpha:T,angle:0,ratio:"0,62,8,8,22"}},frontInner:{FCcolor:{gradientUnits:"userSpaceOnUse",x1:this.leftInnerX,y1:0,x2:this.rightInnerX,y2:0,color:i,
alpha:T,angle:0,ratio:"0,25,5,5,65"}},backInner:{FCcolor:{gradientUnits:"userSpaceOnUse",x1:this.leftInnerX,y1:0,x2:this.rightInnerX,y2:0,color:h,alpha:n,angle:0,ratio:"0,62,8,8,22"}},topBorder:{FCcolor:{gradientUnits:"userSpaceOnUse",x1:this.leftX,y1:0,x2:this.rightX,y2:0,color:e,alpha:l,angle:0,ratio:"0,20,15,15,50"}},topInnerBorder:{FCcolor:{gradientUnits:"userSpaceOnUse",x1:this.leftInnerX,y1:0,x2:this.rightInnerX,y2:0,color:e,alpha:l,angle:0,ratio:"0,50,15,15,20"}},top:aa?{FCcolor:{gradientUnits:"userSpaceOnUse",
radialGradient:!0,cx:this.cx,cy:this.cy,r:this.rx,fx:this.cx-0.3*this.rx,fy:this.cy+this.ry*1.2,color:r+O+m,alpha:b+O+b,ratio:"0,100"}}:{FCcolor:{gradientUnits:"objectBoundingBox",color:g+O+g+O+t+O+f,alpha:b+O+b+O+b+O+b,angle:-72,ratio:"0,8,15,77"}},bottom:Z(ra(a,j)),startSlice:Z(ra(d,b)),endSlice:Z(ra(d,b))}},rotate:function(a){if(!this.hasOnePoint){for(var b=this.pointElemStore,d=0,f=b.length,c;d<f;d+=1)c=b[d],c=c._confObject,c.start+=a,c.end+=a,this.updateSliceConf(c);this.refreshDrawing()}},refreshDrawing:function(){return function(){var a=
this.slicingWallsArr,b=0,d,f=a.length,c,e,m,t,g=this.slicingWallsFrontGroup,p=this.slicingWallsBackGroup;a:{var o=a[0]&&a[0]._conf.index,r,j;t=o<=w;c=1;for(d=a.length;c<d;c+=1)if(j=a[c]._conf.index,r=j<=w,r!=t||j<o)break a;c=0}for(;b<f;b+=1,c+=1)c===f&&(c=0),d=a[c],t=d._conf.index,t<ja?g.appendChild(d):t<=w?(e?d.insertBefore(e):g.appendChild(d),e=d):t<Ta?(m?d.insertBefore(m):p.appendChild(d),m=d):p.appendChild(d)}}(),updateSliceConf:function(a,b){var d=this.getArcPath,f=a.start,c=a.end,n=ta(f),m=
ta(c),t,l,p,o,r,j,s,k,H,K,S,q,x,B,I,y,E=this.cx,v=this.cy,u=this.rx,z=this.ry,C=u+(aa?-1:2),O=z+(aa?-1:2),G=this.innerRx,N=this.innerRy,F=this.depth,L=this.depthY,ma=a.elements,Q,P,ba,R;t=W(n);l=T(n);p=W(m);o=T(m);r=E+u*t;j=v+z*l;s=E+C*t;k=v+O*l;Q=j+F;P=E+u*p;ba=v+z*o;H=E+C*p;K=v+O*o;R=ba+F;this.isDoughnut?(S=E+G*t,q=v+N*l,I=q+F,x=E+G*p,B=v+N*o,y=B+F,a.startSlice=[e,r,j,i,r,Q,S,I,S,q,h],a.endSlice=[e,P,ba,i,P,R,x,y,x,B,h]):(a.startSlice=[e,r,j,i,r,Q,E,L,E,v,h],a.endSlice=[e,P,ba,i,P,R,E,L,E,v,h]);
if(aa){d=(n>m?da:0)+m-n;a.clipTopPath=this.isDoughnut?[e,r,j,g,u,z,0,d>w?1:0,1,P,ba,i,x,B,g,G,N,0,d>w?1:0,0,S,q,h]:[e,r,j,g,u,z,0,d>w?1:0,1,P,ba,i,this.cx,this.cy,h];a.clipOuterFrontPath1=this.clipPathforNoClip;a.clipTopBorderPath=[e,s,k,g,C,O,0,d>w?1:0,1,H,K,i,P,ba,P,ba+1,g,u,z,0,d>w?1:0,0,r,j+1,i,r,j,h];if(f!=c)if(n>m)if(n<w){if(a.clipOuterFrontPath=[e,this.rightX,v,g,u,z,0,0,1,P,ba,"v",F,g,u,z,0,0,0,this.rightX,v+F,h],a.clipOuterFrontPath1=[e,this.leftX,v,g,u,z,0,0,0,r,j,"v",F,g,u,z,0,0,1,this.leftX,
v+F,h],a.clipOuterBackPath=[e,this.rightX,v,g,u,z,0,1,0,this.leftX,v,"v",F,g,u,z,0,1,1,this.rightX,v+F,h],this.isDoughnut)a.clipInnerBackPath=[e,this.rightInnerX,v,g,G,N,0,1,0,this.leftInnerX,v,"v",F,g,G,N,0,1,1,this.rightInnerX,v+F,h],a.clipInnerFrontPath=[e,this.rightInnerX,v,g,G,N,0,0,1,x,B,"v",F,g,G,N,0,0,0,this.rightInnerX,v+F,h,e,this.leftInnerX,v,g,G,N,0,0,0,S,q,"v",F,g,G,N,0,0,1,this.leftInnerX,v+F,h]}else if(m>w){if(a.clipOuterFrontPath=[e,this.rightX,v,g,u,z,0,1,1,this.leftX,v,"v",F,g,u,
z,0,1,0,this.rightX,v+F,h],a.clipOuterBackPath=[e,this.leftX,v,g,u,z,0,0,1,P,ba,"v",F,g,u,z,0,0,0,this.leftX,v+F,h,e,this.rightX,v,g,u,z,0,0,0,r,j,"v",F,g,u,z,0,0,1,this.rightX,v+F,h],this.isDoughnut)a.clipInnerFrontPath=[e,this.rightInnerX,v,g,G,N,0,1,1,this.leftInnerX,v,"v",F,g,G,N,0,1,0,this.rightInnerX,v+F,h],a.clipInnerBackPath=[e,this.leftInnerX,v,g,G,N,0,0,1,x,B,"v",F,g,G,N,0,0,0,this.leftInnerX,v+F,h,e,this.rightInnerX,v,g,G,N,0,0,0,S,q,"v",F,g,G,N,0,0,1,this.rightInnerX,v+F,h]}else{if(a.clipOuterFrontPath=
[e,this.rightX,v,g,u,z,0,0,1,P,ba,"v",F,g,u,z,0,0,0,this.rightX,v+F,h],a.clipOuterBackPath=[e,r,j,g,u,z,0,0,1,this.rightX,v,"v",F,g,u,z,0,0,0,r,Q,h],this.isDoughnut)a.clipInnerFrontPath=[e,this.rightInnerX,v,g,G,N,0,0,1,x,B,"v",F,g,G,N,0,0,0,this.rightInnerX,v+F,h],a.clipInnerBackPath=[e,S,q,g,G,N,0,0,1,this.rightInnerX,v,"v",F,g,G,N,0,0,0,S,I,h]}else if(n<w)if(m>w){if(a.clipOuterFrontPath=[e,r,j,g,u,z,0,0,1,this.leftX,v,"v",F,g,u,z,0,0,0,r,Q,h],a.clipOuterBackPath=[e,this.leftX,v,g,u,z,0,0,1,P,ba,
"v",F,g,u,z,0,0,0,this.leftX,v+F,h],this.isDoughnut)a.clipInnerFrontPath=[e,S,q,g,G,N,0,0,1,this.leftInnerX,v,"v",F,g,G,N,0,0,0,S,I,h],a.clipInnerBackPath=[e,this.leftInnerX,v,g,G,N,0,0,1,x,B,"v",F,g,G,N,0,0,0,this.leftInnerX,v+F,h]}else{if(a.clipOuterFrontPath=[e,r,j,g,u,z,0,0,1,P,ba,"v",F,g,u,z,0,0,0,r,Q,h],a.clipOuterBackPath=this.clipPathforNoClip,this.isDoughnut)a.clipInnerFrontPath=[e,S,q,g,G,N,0,0,1,x,B,"v",F,g,G,N,0,0,0,S,I,h],a.clipInnerBackPath=this.clipPathforNoClip}else{if(a.clipOuterFrontPath=
this.clipPathforNoClip,a.clipOuterBackPath=[e,r,j,g,u,z,0,0,1,P,ba,"v",F,g,u,z,0,0,0,r,Q,h],this.isDoughnut)a.clipInnerFrontPath=this.clipPathforNoClip,a.clipInnerBackPath=[e,S,q,g,G,N,0,0,1,x,B,"v",F,g,G,N,0,0,0,S,I,h]}else a.clipOuterFrontPath=a.clipOuterBackPath=a.clipInnerBackPath=a.clipInnerFrontPath=this.clipPathforNoClip;if(!b){a.elements.startSlice._conf.index=n;a.elements.endSlice._conf.index=m;a.elements.frontOuter._conf.index=Ca(m,n);if(a.elements.frontOuter1)a.elements.frontOuter1._conf.index=
n,a.elements.frontOuter1.attr("litepath",[a.clipOuterFrontPath1]);a.thisElement.attr("litepath",[a.clipTopPath]);a.elements.bottom.attr("litepath",[a.clipTopPath]);a.elements.bottomBorder.attr("litepath",[a.clipTopPath]);a.elements.topBorder&&a.elements.topBorder.attr("litepath",[a.clipTopBorderPath]);a.elements.frontOuter.attr("litepath",[a.clipOuterFrontPath]);a.elements.backOuter.attr("litepath",[a.clipOuterBackPath]);if(this.isDoughnut)a.elements.backInner.attr("litepath",[a.clipInnerBackPath]),
a.elements.frontInner.attr("litepath",[a.clipInnerFrontPath]),a.elements.backInner._conf.index=Ca(m,n);this.hasOnePoint?(a.elements.startSlice.hide(),a.elements.endSlice.hide()):(a.elements.startSlice.attr("litepath",[a.startSlice]).show(),a.elements.endSlice.attr("litepath",[a.endSlice]).show())}}else{s=this.moveCmdArr;k=this.lineCmdArr;H=this.closeCmdArr;var pa=this.centerPoint;K=this.leftPoint;var C=this.topPoint,O=this.rightPoint,F=this.bottomPoint,J=this.leftDepthPoint,U=this.rightDepthPoint;
t=this.leftInnerPoint;l=this.rightInnerPoint;p=this.leftInnerDepthPoint;o=this.rightInnerDepthPoint;a.clipOuterFrontPath1=[];if(f!=c){if(n>m?n<w?(f=d(E,v,r,j,this.leftX,v,u,z,1,0),c=d(E,v,this.leftX,v,this.rightX,v,u,z,1,0),ba=d(E,v,this.rightX,v,P,ba,u,z,1,0),a.clipOuterBackPath=s.concat(K,c,k,U,d(E,L,this.rightX,L,this.leftX,L,u,z,0,0),H),a.clipOuterFrontPath1=s.concat([r,j],f,k,J,d(E,L,this.leftX,L,r,Q,u,z,0,0),H),a.clipOuterFrontPath=s.concat(O,ba,k,[P,R],d(E,L,P,R,this.rightX,L,u,z,0,0),H),a.clipTopBorderPath=
s.concat([r,j],f,c,ba),this.isDoughnut?(r=d(E,v,x,B,this.rightInnerX,v,G,N,0,0),j=d(E,v,this.rightInnerX,v,this.leftInnerX,v,G,N,0,0),q=d(E,v,this.leftInnerX,v,S,q,G,N,0,0),a.clipInnerBackPath=s.concat(l,j,k,p,d(E,L,this.leftInnerX,L,this.rightInnerX,L,G,N,1,0),H),a.clipInnerFrontPath=s.concat(t,q,k,[S,I],d(E,L,S,I,this.leftInnerX,L,G,N,1,0),H,s,[x,B],r,k,o,d(E,L,this.rightInnerX,L,x,y,G,N,1,0),H),a.clipTopPath=a.clipTopBorderPath.concat(k,[x,B],r,j,q,H),a.clipTopBorderPath=a.clipTopBorderPath.concat(s,
[x,B],r,j,q)):a.clipTopPath=a.clipTopBorderPath.concat(k,pa,H)):m>w?(f=d(E,v,r,j,this.rightX,v,u,z,1,0),c=d(E,v,this.rightX,v,this.leftX,v,u,z,1,0),ba=d(E,v,this.leftX,v,P,ba,u,z,1,0),a.clipOuterFrontPath=s.concat(O,c,k,J,d(E,L,this.leftX,L,this.rightX,L,u,z,0,0),H),a.clipOuterBackPath=s.concat([r,j],f,k,U,d(E,L,this.rightX,L,r,Q,u,z,0,0),H,s,K,ba,k,[P,R],d(E,L,P,R,this.leftX,L,u,z,0,0),H),a.clipTopBorderPath=s.concat([r,j],f,c,ba),this.isDoughnut?(r=d(E,v,x,B,this.leftInnerX,v,G,N,0,0),j=d(E,v,this.leftInnerX,
v,this.rightInnerX,v,G,N,0,0),q=d(E,v,this.rightInnerX,v,S,q,G,N,0,0),a.clipInnerFrontPath=s.concat(t,j,k,o,d(E,L,this.rightInnerX,L,this.leftInnerX,L,G,N,1,0),H),a.clipInnerBackPath=s.concat(l,q,k,[S,I],d(E,L,S,I,this.rightInnerX,L,G,N,1,0),H,s,[x,B],r,k,p,d(E,L,this.leftInnerX,L,x,y,G,N,1,0),H),a.clipTopPath=a.clipTopBorderPath.concat(k,[x,B],r,j,q,H),a.clipTopBorderPath=a.clipTopBorderPath.concat(s,[x,B],r,j,q)):a.clipTopPath=a.clipTopBorderPath.concat(k,pa,H)):(f=d(E,v,r,j,this.rightX,v,u,z,1,
0),c=d(E,v,this.rightX,v,P,ba,u,z,1,0),a.clipOuterFrontPath=s.concat(O,c,k,[P,R],d(E,L,P,R,this.rightX,L,u,z,0,0),H),a.clipOuterBackPath=s.concat([r,j],f,k,U,d(E,L,this.rightX,L,r,Q,u,z,0,0),H),a.clipTopBorderPath=s.concat([r,j],f,c),this.isDoughnut?(r=d(E,v,x,B,this.rightInnerX,v,G,N,0,0),j=d(E,v,this.rightInnerX,v,S,q,G,N,0,0),a.clipInnerFrontPath=s.concat([x,B],r,k,o,d(E,L,this.rightInnerX,L,x,y,G,N,1,0),H),a.clipInnerBackPath=s.concat(l,j,k,[S,I],d(E,L,S,I,this.rightInnerX,L,G,N,1,0),H),a.clipTopPath=
a.clipTopBorderPath.concat(k,[x,B],r,j,H),a.clipTopBorderPath=a.clipTopBorderPath.concat(s,[x,B],r,j)):a.clipTopPath=a.clipTopBorderPath.concat(k,pa,H)):n<w?m>w?(f=d(E,v,r,j,this.leftX,v,u,z,1,0),c=d(E,v,this.leftX,v,P,ba,u,z,1,0),a.clipOuterBackPath=s.concat(K,c,k,[P,R],d(E,L,P,R,this.leftX,L,u,z,0,0),H),a.clipOuterFrontPath=s.concat([r,j],f,k,J,d(E,L,this.leftX,L,r,Q,u,z,0,0),H),a.clipTopBorderPath=s.concat([r,j],f,c),this.isDoughnut?(r=d(E,v,x,B,this.leftInnerX,v,G,N,0,0),j=d(E,v,this.leftInnerX,
v,S,q,G,N,0,0),a.clipInnerBackPath=s.concat([x,B],r,k,p,d(E,L,this.leftInnerX,L,x,y,G,N,1,0),H),a.clipInnerFrontPath=s.concat(t,j,k,[S,I],d(E,L,S,I,this.leftInnerX,L,G,N,1,0),H),a.clipTopPath=a.clipTopBorderPath.concat(k,[x,B],r,j,H),a.clipTopBorderPath=a.clipTopBorderPath.concat(s,[x,B],r,j)):a.clipTopPath=a.clipTopBorderPath.concat(k,pa,H)):(f=d(E,v,r,j,P,ba,u,z,1,0),a.clipOuterBackPath=s.concat([r,j]),a.clipTopBorderPath=a.clipOuterBackPath.concat(f),a.clipOuterFrontPath=a.clipTopBorderPath.concat(k,
[P,R],d(E,L,P,R,r,Q,u,z,0,0),H),this.isDoughnut?(r=d(E,v,x,B,S,q,G,N,0,0),a.clipInnerBackPath=s.concat([x,B]),a.clipTopPath=a.clipTopBorderPath.concat(k,[x,B],r,H),a.clipTopBorderPath=a.clipTopBorderPath.concat(s,[x,B],r),a.clipInnerFrontPath=a.clipInnerBackPath.concat(r,k,[S,I],d(E,L,S,I,x,y,G,N,1,0),H)):a.clipTopPath=a.clipTopBorderPath.concat(k,pa,H)):(f=d(E,v,r,j,P,ba,u,z,1,0),a.clipOuterFrontPath=s.concat([r,j]),a.clipTopBorderPath=a.clipOuterFrontPath.concat(f),a.clipOuterBackPath=a.clipTopBorderPath.concat(k,
[P,R],d(E,L,P,R,r,Q,u,z,0,0),H),this.isDoughnut?(r=d(E,v,x,B,S,q,G,N,0,0),a.clipInnerFrontPath=s.concat([x,B]),a.clipTopPath=a.clipTopBorderPath.concat(k,[x,B],r,H),a.clipTopBorderPath=a.clipTopBorderPath.concat(a.clipInnerFrontPath,r),a.clipInnerBackPath=a.clipInnerFrontPath.concat(r,k,[S,I],d(E,L,S,I,x,y,G,N,1,0),H)):a.clipTopPath=a.clipTopBorderPath.concat(k,pa,H)),f=s.concat(K,k,O),r=s.concat(C,k,F),a.clipTopPath=a.clipTopPath.concat(f,r),a.clipOuterFrontPath=a.clipOuterFrontPath.concat(f),a.clipOuterFrontPath1=
a.clipOuterFrontPath1.concat(f),a.clipOuterBackPath=a.clipOuterBackPath.concat(f),this.isDoughnut)r=s.concat(t,k,l),a.clipInnerFrontPath=a.clipInnerFrontPath.concat(r),a.clipInnerBackPath=a.clipInnerBackPath.concat(r)}else if(a.clipTopPath=a.clipOuterFrontPath=a.clipOuterBackPath=[],this.isDoughnut)a.clipInnerFrontPath=a.clipInnerBackPath=[];if(!b){a.elements.startSlice._conf.index=n;a.elements.endSlice._conf.index=m;a.elements.frontOuter._conf.index=Ca(m,n);if(a.elements.frontOuter1)a.elements.frontOuter1._conf.index=
n,ma.frontOuter1.attr({path:a.clipOuterFrontPath1});a.thisElement.attr({path:a.clipTopPath});ma.topBorder.attr({path:a.clipTopBorderPath});ma.bottom.attr({path:a.clipTopPath});ma.bottomBorder.attr({path:a.clipTopBorderPath});ma.frontOuter.attr({path:a.clipOuterFrontPath});ma.backOuter.attr({path:a.clipOuterBackPath});this.isDoughnut&&(ma.frontInner.attr({path:a.clipInnerFrontPath}),ma.backInner.attr({path:a.clipInnerBackPath}));this.hasOnePoint?(a.elements.startSlice.hide(),a.elements.endSlice.hide()):
(a.elements.startSlice.attr({path:a.startSlice}).show(),a.elements.endSlice.attr({path:a.endSlice}).show())}}},createSlice:function(){var a={stroke:!0,strokeWidth:!0,"stroke-width":!0,dashstyle:!0,"stroke-dasharray":!0,translateX:!0,translateY:!0,"stroke-opacity":!0,transform:!0,fill:!0,opacity:!0,ishot:!0,start:!0,end:!0,cursor:!0},b=function(b,d){var c,f,e=this,g=e._confObject,j,h=g.elements,i,A,n=g.pie3DManager;typeof b==="string"&&d!==void 0&&d!==null&&(c=b,b={},b[c]=d);if(!b||typeof b==="string")e=
e._attr(b);else{if(b.cx!==void 0)b.start=b.cx;if(b.cy!==void 0)b.end=b.cy;for(c in b)if(f=b[c],a[c])if(g[c]=f,c==="ishot"||c==="cursor"){j={};j[c]=f;for(i in h)h[i].attr(j);e._attr(j)}else if(c==="transform"){for(i in h)h[i].attr({transform:b[c]});e._attr({transform:b[c]})}else if(c==="stroke"||c==="strokeWidth"||c==="stroke-width"||c==="dashstyle"||c==="stroke-dasharray")j={},j[c]=f,h.topBorder&&h.topBorder.attr(j),h.startSlice.attr(j),h.endSlice.attr(j),h.bottomBorder.attr(j);else{if(c!=="fill"&&
(c==="start"||c==="end"))A=!0}else e._attr(c,f);A&&(n.updateSliceConf(g),n.refreshDrawing())}return e},d=function(a,b,d,c){var f=this._confObject.elements,e;for(e in f)if(d)f[e].drag(b,d,c);else f[e].on(a,b);return d?this.drag(b,d,c):this._on(a,b)},c=function(){var a=this._confObject.elements,b;for(b in a)a[b].hide();return this._hide()},e=function(){var a=this._confObject.elements,b;for(b in a)a[b].show();return this._show()},g=function(){var a=this._confObject,b=a.elements,d;for(d in b)b[d].destroy();
aa&&(a.clipTop.destroy(),a.clipOuterFront.destroy(),a.clipOuterBack.destroy(),a.clipOuterFront1&&a.clipOuterFront1.destroy(),a.clipInnerFront&&a.clipInnerFront.destroy(),a.clipInnerBack&&a.clipInnerBack.destroy());return this._destroy()};return function(a,t,h,p,o,r,j,i,n){var s=this.renderer,h=this.parseColor(h,p),l,a={start:a,end:t,elements:{},pie3DManager:this},t=this.slicingWallsArr,p=a.elements,k,q=aa?"litepath":"path";this.updateSliceConf(a,!0);if(aa){l={fill:Z(h.top),"stroke-width":0};if(n!==
1)l.stroke=o,l["stroke-width"]=r;l=s[q](a.clipTopPath,this.topGroup).attr(l);if(n)p.topBorder=s[q](a.clipTopBorderPath,this.topGroup).attr({fill:Z(h.topBorder),"stroke-width":0})}else l=s[q](a.clipTopPath,this.topGroup).attr({fill:Z(h.top),"stroke-width":0}),p.topBorder=s[q](a.clipTopBorderPath,this.topGroup).attr({stroke:o,"stroke-width":r});p.bottom=s[q](a.clipTopPath,this.bottomBorderGroup).attr({fill:Z(h.bottom),"stroke-width":0});p.bottomBorder=s[q](aa?a.clipTopPath:a.clipTopBorderPath,this.bottomBorderGroup).attr({stroke:o,
"stroke-width":r});p.frontOuter=s[q](a.clipOuterFrontPath,this.slicingWallsFrontGroup).attr({fill:Z(h.frontOuter),"stroke-width":0});p.backOuter=s[q](a.clipOuterBackPath,this.outerBackGroup).attr({fill:Z(h.backOuter),"stroke-width":0});p.startSlice=s[q](a.startSlice,this.slicingWallsFrontGroup).attr({fill:Z(h.startSlice),stroke:o,"stroke-width":r});p.endSlice=s[q](a.endSlice,this.slicingWallsFrontGroup).attr({fill:Z(h.endSlice),stroke:o,"stroke-width":r});o=ta(a.start);r=ta(a.end);n=(o>r?da:0)+r-
o;if(n>w&&(p.frontOuter1=s[q](a.clipOuterFrontPath1,this.slicingWallsFrontGroup).attr({fill:Z(h.frontOuter),"stroke-width":0}),p.frontOuter1._conf={index:o,isStart:0.5,pIndex:j},aa))a.clipOuterFront1=a.clipOuterFrontPath1;p.frontOuter._conf={index:Ca(r,o),isStart:0.5,pIndex:j};p.startSlice._conf={index:o,isStart:0,pIndex:j};p.endSlice._conf={index:r,isStart:1,pIndex:j};this.hasOnePoint&&(p.startSlice.hide(),p.endSlice.hide());this.isDoughnut?(p.frontInner=s[q](a.clipInnerFrontPath,this.innerFrontGroup).attr({fill:Z(h.frontInner),
"stroke-width":0}),p.backInner=s[q](a.clipInnerBackPath,this.innerBackGroup).attr({fill:Z(h.backInner),"stroke-width":0}),p.backInner._conf={index:Ca(r,o),isStart:0.5,pIndex:j},n>w?aa?t.push(p.startSlice,p.frontOuter1,p.frontOuter,p.backInner,p.endSlice):t.push(p.startSlice,p.frontOuter1,p.frontOuter,p.endSlice):aa?t.push(p.startSlice,p.frontOuter,p.backInner,p.endSlice):t.push(p.startSlice,p.frontOuter,p.endSlice)):n>w?t.push(p.startSlice,p.frontOuter1,p.frontOuter,p.endSlice):t.push(p.startSlice,
p.frontOuter,p.endSlice);if(i!==void 0){for(k in p)p[k].tooltip(i);l.tooltip(i)}if(aa&&(a.clipTop=a.clipTopPath,a.clipOuterFront=a.clipOuterFrontPath,a.clipOuterBack=a.clipOuterBackPath,this.isDoughnut))a.clipInnerFront=a.clipInnerFrontPath,a.clipInnerBack=a.clipInnerBackPath;l._confObject=a;a.thisElement=l;l._destroy=l.destroy;l.destroy=g;l._show=l.show;l.show=e;l._hide=l.hide;l.hide=c;l._on=l.on;l.on=d;l._attr=l.attr;l.attr=b;this.pointElemStore.push(l);return l}}()};Da.prototype.constructor=Da;
n("renderer.pie3d",{type:"pie3d",drawCaption:function(){var f;var a=this.options.chart,b=this.options.title,d=this.options.subtitle,c=this.paper,e=this.elements,g=this.layers,m=g.caption,t=e.caption,h=e.subcaption,p=b&&b.text,o=d&&d.text,i=c.width/2,j=b.x,n=d&&d.x;if((p||o)&&!m)m=g.caption=c.group("caption"),g.tracker?m.insertBefore(g.tracker):m.insertAfter(g.dataset);if(p){if(!t)t=e.caption=c.text(m);if(j===void 0)j=i,b.align="middle";t.css(b.style).attr({text:b.text,fill:b.style.color,x:j,y:b.y||
a.spacingTop||0,"text-anchor":b.align||"middle","vertical-align":"top",visibility:"visible",title:b.originalText||""})}else if(t)f=e.caption=t.remove(),t=f;if(o){if(!h)h=e.subcaption=c.text(m);if(n===void 0)n=i,d.align="middle";h.css(d.style).attr({text:d.text,title:d.originalText||"",fill:d.style.color,x:n,y:p?t.attrs.y+t.getBBox().height+2:b.y||a.spacingTop||0,"text-anchor":d.align||"middle","vertical-align":"top",visibility:"visible"})}else if(h)e.subcaption=h.remove();if(!p&&!o&&m)g.caption=m.remove()},
translate:function(){var a=0,b=this.options,d=b.series[0],c=b.plotOptions.series.dataLabels,e=b.plotOptions.pie3d,g=k(d.startAngle,0)%360,m=d.managedPieSliceDepth,h=d.slicedOffset=e.slicedOffset,i=this.canvasWidth,p=this.canvasHeight,o=[this.canvasLeft+i*0.5,this.canvasTop+p*0.5-m*0.5],r,j,n,w,H,b=d.data,K,y=s(i,p),q,x,R,I=c.distance,O=d.pieYScale,E=d.pieSliceDepth,v=d.slicedOffsetY=h*O;o.push(e.size,e.innerSize||0);o=fa(o,function(a,b){return(q=/%$/.test(a))?[i,p-m,y,y][b]*parseInt(a,10)/100:a});
o[2]/=2;o[3]/=2;o.push(o[2]*O);o.push((o[2]+o[3])/2);o.push(o[5]*O);d.getX=function(a,b){n=S.asin((a-o[1])/(o[2]+I));return o[0]+(b?-1:1)*W(n)*(o[2]+I)};d.center=o;va(b,function(b){a+=b.y});d.labelsRadius=o[2]+I;d.labelsRadiusY=d.labelsRadius*O;d.quadrantHeight=(p-m)/2;d.quadrantWidth=i/2;w=-g*ga;w=B(w*1E3)/1E3;H=w+da;e=l(parseInt(c.style.fontSize,10),10)+4;d.maxLabels=U(d.quadrantHeight/e);d.labelFontSize=e;d.connectorPadding=l(c.connectorPadding,5);d.isSmartLineSlanted=k(c.isSmartLineSlanted,!0);
d.connectorWidth=l(c.connectorWidth,1);d.enableSmartLabels=c.enableSmartLabels;if(!d.pie3DManager)d.pie3DManager=new Da(o[0],o[1],o[2],o[3],O,E,this.layers.dataset,this.paper,d.data.length===1,d.use3DLighting);va(b,function(b){r=w;K=a?b.y/a:0;w=B((w+K*da)*1E3)/1E3;w>H&&(w=H);j=w;b.shapeArgs={start:B(r*1E3)/1E3,end:B(j*1E3)/1E3};b.centerAngle=n=(j+r)/2%da;b.slicedTranslation=[B(W(n)*h),B(T(n)*v)];x=W(n)*o[2];d.radiusY=R=T(n)*o[4];b.tooltipPos=[o[0]+x*0.7,o[1]+R];b.percentage=K*100;b.total=a})},drawPlotPie3d:function(a,
b){this.translate();var d=this,c=a.items,e=a.data,g=d.options,m=g.plotOptions,h=m.series,i=d.layers,p=d.elements.plots[0],o=d.datasets[0],m=m.series.dataLabels,r=h.dataLabels.style,h=l(a.moveDuration,h.animation.duration),j=d.paper,g=(g=g.tooltip||{})&&g.enabled!==!1,n,s=o.slicedOffset,k=o.slicedOffsetY,w=d.plotGraphicClick,S=d.plotDragMove,q=d.plotDragStart,x=d.plotDragEnd,B=d.plotMouseDown,I=d.plotMouseUp,K=!!d.datasets[0].enableRotation,E=b.showBorderEffect,v=e.length,u,z,O,y,G,N,F,L,R,Q,P;if(!e||
!v)e=[];p.singletonCase=v==1;p.chartPosition=Ba(d.container);p.pieCenter=o.center;p.timerThreshold=30;for(P=-1;++P<v;)if(z=e[P],O=z.y,y=z.displayValue,N=z.sliced,Q=z.shapeArgs,L=z.centerAngle,n=z.toolText,F=(G=!!z.link)||K||!z.doNotSlice,!(O===null||O===void 0))if(!(u=c[P])){b.data[P].plot=u=c[P]={chart:d,index:P,seriesData:p,value:O,angle:L,link:z.link,shapeArgs:Q,slicedX:N&&!p.singletonCase?W(L)*s:0,slicedY:N&&!p.singletonCase?T(L)*k:0,sliced:N,labelText:y,name:z.name,label:z.name,percentage:z.percentage,
toolText:n,originalIndex:v-P-1,graphic:o.pie3DManager.createSlice(Q.start,Q.end,z.color,z._3dAlpha,z.borderColor,z.borderWidth,P,g?n:"",E)};b.data[P].legendClick=function(a){return function(){d.legendClick(a,!0,!1)}}(u);u.graphic.plotItem=u;u.transX=W(L)*s;u.transY=T(L)*k;u.slicedTranslation="t"+u.transX+","+u.transY;u.graphic.attr({transform:"t"+u.slicedX+","+u.slicedY,ishot:F,cursor:G?"pointer":""});if(!z.doNotSlice)u.graphic.on("click",function(a){return function(){w.call(a)}}(u));u.graphic.on("drag",
function(a){return function(b,d,c,f,e){S.call(a,b,d,c,f,e)}}(u),function(a){return function(b,d,c){q.call(a,b,d,c)}}(u),function(a){return function(){x.call(a)}}(u));u.graphic.on("mousedown",function(a){return function(){B.call(a)}}(u));u.graphic.on("mouseup",function(a){return function(){I.call(a)}}(u));if(y!==void 0&&(u.dataLabel=j.text(i.dataset).css(r).attr({text:y,title:z.originalText||"",fill:r.color||"#000000",visibility:"hidden",ishot:F,cursor:G?"pointer":""}),u.dataLabel.click(w,u),u.dataLabel.mousedown(B,
u),u.dataLabel.mouseup(I,u),m.distance>0&&(R=m.connectorWidth)&&m.enableSmartLabels))u.connector=j.path("M 0 0 l 0 0",i.dataset).attr({"stroke-width":R,stroke:m.connectorColor||"#606060",visibility:"hidden",ishot:F,cursor:G?"pointer":""}),u.connector.click(w,u),u.connector.mousedown(B,u),u.connector.mouseup(I,u)}o.pie3DManager.refreshDrawing();h>0?d.animate(c,h):d.placeDataLabels(!1,c)},rotate:function(a){var b=this.datasets[0],d=this.elements.plots[0].items,c=b.slicedOffset,e=b.slicedOffsetY,g=b.startAngle,
m,a=a||-b._lastAngle;m=(a-g)%360;b.startAngle=l(a,b.startAngle)%360;m=-(m*Q)/180;b.pie3DManager&&b.pie3DManager.rotate(m);va(d,function(a){var b=a.graphic,d=a.shapeArgs,d={start:d.start+=m,end:d.end+=m},g=a.angle=ta((d.start+d.end)/2),d=a.sliced,h=W(g),g=T(g);a.slicedTranslation=[B(h*c),B(g*e)];a.transX=a.slicedTranslation[0];a.transY=a.slicedTranslation[1];a.slicedX=d?W(m)*c:0;a.slicedY=d?T(m)*e:0;b&&d&&a.graphic.attr({transform:"t"+a.slicedTranslation[0]+","+a.slicedTranslation[1]})});this.placeDataLabels(!0,
d)},plotMouseDown:function(){this.seriesData.isRotating=!1},plotMouseUp:function(){var a=this.chart,b=this.seriesData;!b.isRotating&&a.linkClickFN.call({link:b.data[this.index].link},a);ea._supportsTouch&&!b.isRotating&&a.plotGraphicClick.call(this)},plotDragStart:function(a,b,d){var c=this.seriesData,e=this.chart.datasets[0];if(e.enableRotation)a=La.call(d,a,b,c.pieCenter,c.chartPosition,e.pieYScale),e.dragStartAngle=a,e._lastAngle=-e.startAngle},plotDragEnd:function(){var a=this,b=a.chart,d={hcJSON:{series:[{startAngle:b.datasets[0].startAngle}]}};
b.disposed||ua(b.logic.chartInstance.jsVars._reflowData,d,!0);setTimeout(function(){a.seriesData.isRotating=!1},0)},plotDragMove:function(a,b,d,c,e){var g=this.chart,a=g.datasets[0],b=this.seriesData;if(g.options.series[0].enableRotation&&!b.singletonCase&&(b.isRotating=!0,d=La.call(e,d,c,b.pieCenter,b.chartPosition,a.pieYScale),c=d-a.dragStartAngle,a.dragStartAngle=d,b.moveDuration=0,a._lastAngle+=c*180/Q,d=(new Date).getTime(),!a._lastTime||a._lastTime+b.timerThreshold<d))a._lastTime||g.rotate(),
b.timerId=setTimeout(function(){(!g.disposed||!g.disposing)&&g.rotate()},b.timerThreshold),a._lastTime=d},animate:function(a,b){var d,c,e,g=a.length,m,h,i,p=this,o;if(p.datasets[0].alphaAnimation)p.layers.dataset.attr({opacity:0}),p.layers.dataset.animate({opacity:1},b,"ease-in",function(){!p.disposed&&!p.disposing&&p.placeDataLabels(!1,a)});else for(d=0;d<g;d++)if(m=a[d],h=m.graphic,i=m.shapeArgs,m=2*Q,h)h.attr({start:m,end:m}),o=i.start,i=i.end,c?h.animateWith(c,e,{cx:o-m,cy:i-m},b,"ease-in"):(e=
ea.animation({cx:o-m,cy:i-m},b,"ease-in",function(){!p.disposed&&!p.disposing&&p.placeDataLabels(!1,a)}),c=h.animate(e))},plotGraphicClick:function(){var a=this.seriesData,b=this.chart,d,c,e,g,h,i;if(!a.isRotating&&!a.singletonCase)return d=this.graphic,c=this.connector,e=this.dataLabel,a=this.sliced,g=this.connectorPath,h=(a?-1:1)*this.transX,i=(a?-1:1)*this.transY,d.animate({transform:a?"t0,0":"t"+h+","+i},200,"easeIn"),e&&e.x&&e.animate({x:e.x+(a?0:h)},200,"easeIn"),g&&(g[1]+=h,g[2]+=i,g[4]+=h,
g[6]+=h,c.animate({path:g},200,"easeIn")),a=this.sliced=!a,d={hcJSON:{series:[]}},d.hcJSON.series[0]={data:[]},ua(b.logic.chartInstance.jsVars._reflowData,d,!0),a},placeDataLabels:function(){var a=function(a,b){return a.point.value-b.point.value},b=function(a,b){return a.angle-b.angle},d=["start","start","end","end"],f=[-1,1,1,-1],g=[1,1,-1,-1];return function(h,m){var n=this.datasets[0],k=this.smartLabel,p=this.options.plotOptions.series.dataLabels,o=p.style,r=l(Oa(parseFloat(o.lineHeight)),12),
j=Ea(p.placeInside,!1),K=p.skipOverlapLabels,O=p.manageLabelOverflow,H=p.connectorPadding,y=p.distance;Ea(p.softConnector,!0);var R=p.connectorWidth,q,x,y=y>0,Q=n.center,I=Q[1],C=Q[0],E=Q[2],v=Q[4],u=[[],[],[],[]],z,J,U,G=this.canvasLeft,N=this.canvasTop,F=this.canvasWidth,L,M,Y,P,ba,ca,ga,Z,Aa,aa,na,ea=n.labelsRadius,X=B(n.labelsRadiusY*100)/100,fa=n.labelFontSize,V=fa,ha=V/2,H=[H,H,-H,-H],ka=n.maxLabels,Ia=n.isSmartLineSlanted,Ha=n.enableSmartLabels,oa,n=n.pieSliceDepth/2;h||k.setStyle(o);if(m.length==
1){if(P=m[0],oa=P.dataLabel,P.slicedTranslation=[G,N],oa)oa.attr({visibility:c,"text-anchor":"middle",x:C,y:I+ha-2}),oa.x=C}else if(j)va(m,function(a){if(oa=a.dataLabel){na=a.angle;aa=I+Q[6]*T(na)+ha-2;ga=C+Q[5]*W(na);oa.x=ga;oa._x=ga;oa.y=aa;if(a.sliced){var a=a.slicedTranslation,b=a[1]-N;ga+=a[0]-G;aa+=b}oa.attr({visibility:c,align:"middle",x:ga,y:aa})}});else{va(m,function(a){if(oa=a.dataLabel)na=a.angle,na<0&&(na=da+na),z=na>=0&&na<ja?1:na<w?2:na<Ta?3:0,u[z].push({point:a,angle:na})});for(U=j=
4;U--;){if(K&&(P=u[U].length-ka,P>0)){u[U].sort(a);J=u[U].splice(0,P);M=0;for(Y=J.length;M<Y;M+=1)P=J[M].point,P.dataLabel.attr({visibility:"hidden"}),P.connector&&P.connector.attr({visibility:"hidden"})}u[U].sort(b)}U=ma(u[0].length,u[1].length,u[2].length,u[3].length);X=ma(s(U,ka)*V,X+V);u[1].reverse();u[3].reverse();for(k.setStyle(o);j--;){M=u[j];Y=M.length;K||(V=Y>ka?X/Y:fa,ha=V/2);P=Y*V;o=X;for(U=0;U<Y;U+=1,P-=V)x=pa(X*T(M[U].angle)),o<x?x=o:x<P&&(x=P),o=(M[U].oriY=x)-V;J=d[j];Y=X-(Y-1)*V;o=
0;for(U=M.length-1;U>=0;U-=1,Y+=V){P=M[U].point;na=M[U].angle;ba=P.sliced;oa=P.dataLabel;x=pa(X*T(na));x<o?x=o:x>Y&&(x=Y);o=x+V;Z=(x+M[U].oriY)/2;x=C+g[j]*ea*W(S.asin(Z/X));Z*=f[j];Z+=I;Aa=I+v*T(na);ca=C+E*W(na);(j<2&&x<ca||j>1&&x>ca)&&(x=ca);ga=x+H[j];aa=Z+ha-2;q=ga+H[j];oa.x=q;oa._x=q;O&&(L=j>1?q-this.canvasLeft:this.canvasLeft+F-q,L=k.getSmartText(P.labelText,L,r),oa.attr({text:L.text,title:L.tooltext||""}));na<w&&(Z+=n,Aa+=n,aa+=n);oa.y=aa;if(ba)ba=P.transX,L=P.transY,ga+=ba,x+=ba,ca+=ba,Aa+=
L,q+=ba;oa.attr({visibility:c,"text-anchor":J,x:q,y:Z});if(y&&R&&Ha)q=P.connector,P.connectorPath=x=[e,ca,Aa,i,Ia?x:ca,Z,ga,Z],q?(q.attr({path:x}),q.attr("visibility",c)):P.connector=q=this.paper.path(x).attr({"stroke-width":R,stroke:p.connectorColor||"#606060",visibility:c})}}}}}(),legendClick:function(a,b,d){var c=a.chart;a.chart.elements.plots[0].isRotating=!1;c.plotGraphicClick.call(a);d!==!0&&(eventArgs={datasetName:a.label,datasetIndex:a.originalIndex,id:a.userID,visible:b,label:a.label,value:a.value,
percentValue:a.percentage,tooltext:a.toolText,link:a.link,sliced:!a.sliced},la.raiseEvent("legenditemclicked",eventArgs,c.logic.chartInstance))}},n["renderer.root"]);n("renderer.pie",{drawPlotPie:function(a,b){var d=this,f=a.items,e=a.data,g=d.options,h=g.plotOptions,i=h.pie,n=h.series,p=d.layers,o=p.dataset,r=d.elements.plots[0],h=h.series.dataLabels,j=n.dataLabels.style,s=n.shadow,n=l(a.moveDuration,n.animation.duration),k=d.paper,g=(g=g.tooltip||{})&&g.enabled!==!1,B=((b.startAngle*=-w/180)||0)%
da,S=i.slicedOffset,K=b.valueTotal,q=da/K,x=d.canvasLeft+d.canvasWidth*0.5,y=d.canvasTop+d.canvasHeight*0.5,I=i.size*0.5,O=(i.innerSize||0)*0.5,E=d.plotGraphicClick,v=d.plotDragMove,u=d.plotDragStart,z=d.plotDragEnd,Q=d.plotMouseDown,R=d.plotMouseUp,G=!!d.datasets[0].enableRotation,N=e.length,F,L,C,U,P,ma,pa,J,M,Y,ca,ga=a.shadowGroup,V,Oa,ja;if(!e||!N)e=[];if(!ga)ga=a.shadowGroup=k.group(o).toBack();r.singletonCase=N==1;r.chartPosition||(r.chartPosition=Ba(d.container));r.pieCenter=[x,y];r.timerThreshold=
30;Y=M=B;for(V=N;V--;)if(L=e[V],C=L.y,U=L.displayValue,ma=L.sliced,i=L.toolText,pa=(P=!!L.link)||G||!L.doNotSlice,!(C===null||C===void 0)){F=L.color.FCcolor;F.r=I;F.cx=x;F.cy=y;Y=M;M-=!r.singletonCase?C*q:da;J=(M+Y)*0.5;if(!(F=f[V]))if(b.data[V].plot=F=f[V]={chart:d,index:V,seriesData:r,value:C,angle:J,slicedX:W(J)*S,slicedY:T(J)*S,sliced:ma,labelText:U,toolText:i,label:L.name,link:L.link,percentage:K?C*K/100:0,originalIndex:N-V-1,graphic:k.ringpath(x,y,I,O,B,B,p.dataset).attr({"stroke-width":L.borderWidth,
"stroke-linejoin":"round",stroke:L.borderColor,fill:Z(L.color),"stroke-dasharray":L.dashStyle,redrawDataLabels:B,ishot:pa,cursor:P?"pointer":""}).shadow(s&&L.shadow,ga).drag(v,u,z).mousedown(Q).mouseup(R)},L.doNotSlice||F.graphic.click(E),g&&F.graphic.tooltip(i),b.data[V].legendClick=function(a){return function(){d.legendClick(a,!0,!1)}}(F),F.graphic.data("plotItem",F),U!==void 0&&(F.dataLabel=k.text(o).css(j).attr({text:U,fill:j.color||"#000000",ishot:pa}).click(E).drag(v,u,z).mousedown(Q).mouseup(R).hide(),
F.dataLabel.data("plotItem",F),h.distance>0&&(ca=h.connectorWidth)&&h.enableSmartLabels))F.connector=k.path("M 0 0 l 0 0",o).attr({"stroke-width":ca,stroke:h.connectorColor||"#606060",visibility:c,ishot:!0}).click(E).drag(v,u,z).mousedown(Q).mouseup(R),F.connector.data("plotItem",F);F.angle=J;F.transX=W(J)*S;F.transY=T(J)*S;F.slicedTranslation="t"+W(J)*S+","+T(J)*S;Oa?F.graphic.animateWith(Oa,ja,{ringpath:[x,y,I,O,M,Y],transform:F.sliced?F.slicedTranslation:""},n,"easeIn"):(ja=ea.animation({ringpath:[x,
y,I,O,M,Y],redrawDataLabels:d,transform:F.sliced?F.slicedTranslation:""},n,"easeIn",function(){if(!d.disposed&&!d.disposing&&!d.paper.ca.redrawDataLabels)d.placeDataLabels(!1,f,a),d.paper.ca.redrawDataLabels=d.redrawDataLabels}),Oa=F.graphic.animate(ja))}},rotate:function(a,b){var d=a.items,c=a.data,e=this.options.plotOptions.pie,g=e.slicedOffset,h=da/b.valueTotal,i=this.canvasLeft+this.canvasWidth*0.5,n=this.canvasTop+this.canvasHeight*0.5,p=e.size*0.5,e=(e.innerSize||0)*0.5,o,r,j,l,s;j=(b.startAngle||
0)%da;for(s=c.length;s--;)if(o=c[s],r=o.y,!(r===null||r===void 0))o=d[s],l=j,j-=!o.seriesData.singletonCase?r*h:da,r=(j+l)*0.5,o.angle=r,o.transX=W(r)*g,o.transY=T(r)*g,o.slicedTranslation="t"+W(r)*g+","+T(r)*g,o.graphic.attr({ringpath:[i,n,p,e,j,l],transform:o.sliced?o.slicedTranslation:""});this.placeDataLabels(!0,d,a)}},n["renderer.piebase"])},[3,2,2,"sr4"]]);
FusionCharts(["private","modules.renderer.js-zoomline",function(){var Ba=this,fa=Ba.hcLib,ta=window,Ca=/msie/i.test(navigator.userAgent)&&!ta.opera,La=fa.chartAPI,Da=fa.chartAPI,la=fa.extend2,y=fa.raiseEvent,ea=fa.pluck,C=fa.pluckNumber,J=fa.getFirstColor,Ma=fa.graphics.convertColor,k=fa.defaultPaletteOptions,wa=fa.bindSelectionEvent,l=fa.createTrendLine,M=fa.Raphael,Ea=fa.FC_CONFIG_STRING,Qa="rgba(192,192,192,"+(Ca?0.002:1.0E-6)+")",V=Math,X=V.ceil,ua=V.floor,Na=V.max,Z=V.min,Fa=V.cos,Ga=V.sin,aa=
parseFloat,ya=parseInt,va=function(b){return b&&b.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,"\\$&")},qa;la(fa.eventList,{zoomed:"FC_Zoomed",pinned:"FC_Pinned",resetzoomchart:"FC_ResetZoomChart"});La("zoomline",{rendererId:"zoomline",standaloneInit:!0,hasVDivLine:!0,defaultSeriesType:"stepzoom",canvasborderthickness:1,defaultPlotShadow:1,chart:function(){var b=this.base.chart.apply(this,arguments),c=this.dataObj.chart,e=k.canvasBorderColor[this.paletteIndex],i=b.chart;la(i,{animation:!1,zoomType:"x",canvasPadding:C(c.canvaspadding,
0),scrollColor:J(ea(c.scrollcolor,k.altHGridColor[i.paletteIndex])),scrollBtnWidth:C(c.scrollbtnwidth,c.scrollheight,16),scrollHeight:C(c.scrollheight,16)||16,allowPinMode:C(c.allowpinmode,1),skipOverlapPoints:C(c.skipoverlappoints,1),showToolBarButtonTooltext:C(c.showtoolbarbuttontooltext,1),btnResetChartTooltext:ea(c.btnresetcharttooltext,"Reset Chart"),btnZoomOutTooltext:ea(c.btnzoomouttooltext,"Zoom out one level"),btnSwitchToZoomModeTooltext:ea(c.btnswitchtozoommodetooltext,"<strong>Switch to Zoom Mode</strong><br/>Select a subset of data to zoom into it for detailed view"),
btnSwitchToPinModeTooltext:ea(c.btnswitchtopinmodetooltext,"<strong>Switch to Pin Mode</strong><br/>Select a subset of data and compare with the rest of the view"),pinPaneFill:Ma(ea(c.pinpanebgcolor,e),C(c.pinpanebgalpha,15)),zoomPaneFill:Ma(ea(c.zoompanebgcolor,"#b9d5f1"),C(c.zoompanebgalpha,30)),zoomPaneStroke:Ma(ea(c.zoompanebordercolor,"#3399ff"),C(c.zoompaneborderalpha,80))});return b},preSeriesAddition:function(){var b=this.dataObj,c=b.chart,e=(e=b.categories)&&e[0]||{},b=e.category,i=this.hcJSON,
g=i[Ea],h=this.smartLabel,l=C(c.compactdatamode,0),k=ea(c.dataseparator,"|"),W=C(c.showlabels,1),K=W&&C(c.labelheight),B=c.labeldisplay&&c.labeldisplay.toLowerCase()==="rotate"?270:C(c.rotatelabels,1)?270:0,s=i.xAxis.labels.style,y=aa(s.lineHeight),J=i.chart.labelPadding=C(c.labelpadding,2)+i.chart.plotBorderWidth,Q,M,U=0,R=-1,ga,w,V;delete e.category;i.categories=k=la({data:Q=l&&b&&b.split&&b.split(k)||b||[],rotate:B},e);b!==void 0&&(e.category=b);e=Q.length||0;if(ga=!l&&W&&K!==0&&e||0){for(;ga--;)Q[ga]=
Q[ga]&&(M=Q[ga].label||"")&&((w=M.length)>U&&(U=w,R=ga,M)||M)||"";U&&(M=Q[R])}else if(l&&e)if(B){w=ta.document.createElement("div");K=ta.document.createElement("span");w.setAttribute("class","fusioncharts-zoomline-localsmartlabel");w.style.cssText="display:block;width:1px;position:absolute;";for(V in s)w.style[V]=s[V];K.appendChild(ta.document.createTextNode(b.replace(/\s*/g,"").replace(/\|/g," ")));w.appendChild(K);ta.document.body.appendChild(w);K=K.offsetWidth||void 0;w.parentNode.removeChild(w)}else M=
Q[e-1]||Q[0];K===void 0&&W&&(M?(h.setStyle(s),M=h.getSmartText(M),K=B?M.width:M.height):K=y*(B&&3||1));K>g.height*0.3&&(K=g.height*0.3);k.labelHeight=K&&K+10||0;k.show=K&&W||0;k.css=la({},s);B?(k.css.rotation=B,k.css["text-anchor"]="end"):k.css["vertical-align"]="top";i.xAxis.min=0;i.xAxis.max=e&&e-1||0;K+=C(c.scrollheight,16)||16;i.chart.marginBottom+=J;g.marginBottomExtraSpace+=K;ea(c.caption,c.subcaption)||(g.marginTopExtraSpace+=16)},series:function(){var b=this.dataObj,c=b.chart,e=b.dataset,
i=this.hcJSON,g=i[Ea],h=g[0],k=i.series,T=C(c.yaxismaxvalue),W=C(c.yaxisminvalue),K=C(c.forceyaxislimits,0),B=C(c.compactdatamode,0),s=ea(c.dataseparator,"|"),y=va(c.indecimalseparator),M=va(c.inthousandseparator),Q=C(c.drawanchors,c.showanchors,1),J=!!C(c.showlegend,1),U,R,V,w,ja,da=Infinity,X=-Infinity,Y;ja=i.categories.data.length;if(e&&e.length&&ja){y&&(y=RegExp(y,"g"));M&&(M=RegExp(M,"g"));!M&&!y&&B&&K&&T!==void 0&&W!==void 0?(K=!0,X=Na(T,W),da=Z(W,T)):K=!1;T=0;for(W=e.length;T<W;T++){U=e[T];
V=U.data;delete U.data;B?(w=V||"",M&&(w=w.replace(M,"")),y&&(w=w.replace(y,".")),w=w.split(s)):w=V||[];if(w.length>ja)w.length=ja;Y=w.length;if(B){if(!K)for(;Y--;)R=aa(w[Y]),isNaN(R)&&(R=void 0),R>X&&(X=R),R<=da&&(da=R),w[Y]=R}else for(;Y--;)R=w[Y]&&w[Y].value||"",M&&(R=R.replace(M,"")),y&&(R=R.replace(y,".")),R=aa(R),isNaN(R)&&(R=void 0),R>X&&(X=R),R<=da&&(da=R),w[Y]=R;k.push(R={index:T,type:"zoomline",data:w,name:U.seriesname||"",showInLegend:U.seriesname&&C(U.includeinlegend,1)&&J||!1,showAnchors:C(U.drawanchors,
U.showanchors,Q),visible:!!C(U.initiallyvisible,1),lineWidth:2});w.length=ja;V!==void 0&&(U.data=V);R.attrs=this.seriesGraphicsAttrs(U,T);U=R.attrs.anchors;R.color=R.attrs.graphics.stroke;R.ancorRadius=U.r+U["stroke-width"]/2;R.marker={fillColor:U.fill,lineColor:U.stroke,lineWidth:1,symbol:"circle"}}(X===-Infinity||da===Infinity)&&(X=da=void 0);K=ya(C(c.displaystartindex,1),10)-1;s=ya(C(c.displayendindex,ja||2),10)-1;(e=C(c.pixelsperpoint,15))<5&&(e=5);(k=C(c.pixelsperlabel,i.categories.rotate?20:
60))<e&&(k=e);(K<0||K>=(ja-1||1))&&(K=0);(s<=K||s>(ja-1||1))&&(s=ja-1||1);i.stepZoom={cnd:C(c.connectnulldata,0),amrd:C(c.anchorminrenderdistance,20),nvl:C(c.numvisiblelabels,0),cdm:B,oppp:e,oppl:k,dsi:K,dei:s,vdl:s-K,dmax:h.max=X,dmin:h.min=da,clen:ja,offset:0,step:1,llen:0,alen:0,ddsi:K,ddei:s};i.crossline={style:{lineHeight:g.inCanvasStyle.lineHeight,fontSize:g.inCanvasStyle.fontSize,fontFamily:g.inCanvasStyle.fontFamily}};this.configureAxis(i,b);b.trendlines&&l(b.trendlines,i.yAxis,g,!1,this.isBar)}},
seriesGraphicsAttrs:function(b,c){var e=this.dataObj.chart,i=this.hcJSON.colors,g=(b.dashed||e.linedashed||"0")!=0,h,i={"stroke-width":C(b.linethickness,e.linethickness,2),stroke:J(ea(b.color,e.linecolor,i[c%i.length])),"stroke-opacity":C(b.alpha,e.linealpha,100)/100,"stroke-dasharray":g?[C(b.linedashlen,e.linedashlen,5),C(b.linedashgap,e.linedashgap,4)]:"none","stroke-linejoin":"round","stroke-linecap":"round"},g=la({},i);h=i["stroke-width"]+C(e.pinlinethicknessdelta,1);g["stroke-width"]=h>0&&h||
0;g["stroke-dasharray"]=[3,2];return{graphics:i,pin:g,shadow:{opacity:i["stroke-opacity"],apply:C(e.showshadow,+!M.vml)},anchors:{"stroke-linejoin":"round","stroke-linecap":"round",r:C(b.anchorradius,e.anchorradius,i["stroke-width"]+2),stroke:J(ea(b.anchorbordercolor,e.anchorbordercolor,i.stroke)),"stroke-opacity":C(b.anchorborderalpha,e.anchorborderalpha,100)/100,"stroke-width":C(b.anchorborderthickness,e.anchorborderthickness,i["stroke-width"]),fill:J(ea(b.anchorbgcolor,e.anchorbgcolor,"#ffffff")),
"fill-opacity":C(b.anchorbgalpha,e.anchorbgalpha,100)/100,opacity:C(b.anchoralpha,e.anchoralpha,100)/100},anchorShadow:C(e.anchorshadow,e.showshadow,+!M.vml)&&{apply:!0,opacity:C(b.anchoralpha,e.anchoralpha,100)/100}}},eiMethods:{zoomOut:function(){var b=this.jsVars,c;if(b&&(c=b.hcObj))return c.zoomOut&&b.hcObj.zoomOut()},zoomTo:function(b,c){var e=this.jsVars,i;if(e&&(i=e.hcObj))return i.zoomRange&&e.hcObj.zoomRange(b,c-2)},resetChart:function(){var b=this.jsVars,c;if(b&&(c=b.hcObj))c.pinRangePixels&&
b.hcObj.pinRangePixels(),c.resetZoom&&b.hcObj.resetZoom()},setZoomMode:function(b){var c=this.jsVars,e;c&&(e=c.hcObj)&&b&&e.pinRangePixels&&c.hcObj.pinRangePixels()},getViewStartIndex:function(){var b=this.jsVars,c;if(b&&b.hcObj&&(c=b.hcObj._zoominfo))return c.ddsi+1},getViewEndIndex:function(){var b=this.jsVars,c;if(b&&b.hcObj&&(c=b.hcObj._zoominfo))return b=c.ddei-1,b>c.clen?c.clen:b}}},La.msline);Da("renderer.zoomline",{resetZoom:function(){var b=this._zoomhistory,c=this.options.stepZoom;if(!b.length)return!1;
b.length=0;this.zoomTo(c.dsi,c.dei)&&y("resetzoomchart",this._zoomargs,this.fusionCharts,[this.fusionCharts.id]);return!0},zoomOut:function(){var b=this._zoomhistory.pop(),c=this.options.stepZoom,e,i,g;b?(e=b.dsi,i=b.dei):this._prezoomed&&(e=0,i=c.clen-1);(g=this.zoomTo(e,i))&&Ba.raiseEvent("zoomedout",g,this.fusionCharts);return!0},zoomRangePixels:function(b,c){var e=this._zoomhistory,i=this._zoominfo,g=i.ppp,i=i.ddsi,h;e.push(this._zoominfo);(h=this.zoomTo(i+ua(b/g),i+ua(c/g)))?Ba.raiseEvent("zoomedin",
h,this.fusionCharts):e.pop()},zoomRange:function(b,c){var e=this._zoomhistory,i;e.push(this._zoominfo);(i=this.zoomTo(+b-1,+c+1))?Ba.raiseEvent("zoomedin",i,this.fusionCharts):e.pop()},zoomTo:function(b,c){var e=this.xlabels.data,i=this._zoominfo,g=this._zoomhistory,h=i.clen;b<0&&(b=0);b>=h-1&&(b=h-1);c<=b&&(c=b+1);c>h-1&&(c=h-1);if(b===c||b===i.dsi&&c===i.dei)return!1;this.pinRangePixels();i=la({},i);i.dsi=b;i.dei=c;i=this._zoominfo=i;this.updatePlotZoomline();this.zoomOutButton[i.vdl===i.clen-1?
"hide":"show"]();this.resetButton[g.length?"show":"hide"]();this.elements.zoomscroller.attr({"scroll-ratio":i.vdl/(h-!!h),"scroll-position":[i.dsi/(h-i.vdl-1),!0]});e={level:g.length+1,startIndex:b,startLabel:e[b],endIndex:c,endLabel:e[c]};y("zoomed",e,this.fusionCharts,[this.fusionCharts.id,b,c,e.startLabel,e.endLabel,e.level]);return e},activatePin:function(b){var c=this._zoominfo,e=this.options.chart,i=this.pinButton;if(i&&c.pinned^(b=!!b))return b||this.pinRangePixels(),e.showToolBarButtonTooltext&&
i.tooltip(e[b&&"btnSwitchToZoomModeTooltext"||"btnSwitchToPinModeTooltext"]||""),i.attr("button-active",b),c.pinned=b},pinRangePixels:function(b,c){var e=this.paper,i=this.elements,g=this.xlabels.data,h=this._zoominfo,l=this.layers.zoompin,k=i.pinrect,W=i["clip-pinrect"],K=this._pingrouptransform,B=this.plots,s=c-b,C,J;if(h&&l&&k){if(b===c)return l.hide(),i.pintracker.hide(),this.pinButton.attr("button-active",!1),h.pinned=!1;for(J=B.length;J--;){k=B[J];C=k.pinline;if(!C)C=k.pinline=e.path(void 0,
l).attr(k.attrPin);C.attr("path",k.graphic.attrs.path)}W[0]=b+(M.svg?this.canvasLeft:0);W[2]=s;l.attr({"clip-rect":W,transform:K}).show();i.pintracker.__pindragdelta=0;i.pintracker.show().attr({transform:K,x:b,width:s});b=this.getValuePixel(b);c=this.getValuePixel(c);y("pinned",{startIndex:b,endIndex:c,startLabel:g[b],endLabel:g[c]},this.fusionCharts,[this.fusionCharts.id,b,c,g[b],g[c]]);return h.pinned=!0}},getValuePixel:function(b){var c=this._zoominfo;return c.ddsi+ua(b/c.ppp)},drawGraph:function(){var b=
this,c=b.paper,e=b.canvasLeft,i=b.canvasTop,g=b.canvasWidth,h=b.canvasHeight,l=b.options,k=l.chart,y=k.plotBorderWidth,K=k.useRoundEdges,B=k.showToolBarButtonTooltext,s=b.layers,C=b.toolbar,J=b.elements,Q=k.allowPinMode,V,U=l.categories,R=!1,X,w,Z,da,aa,Y;Y=b._zoominfo=la({},l.stepZoom);b._zoomhistory=[];if(Y.clen){R=b._prezoomed=Y.dei-Y.dsi<Y.clen-1;aa=b._visw=b.canvasWidth-k.canvasPadding*2;da=b._visx=b.canvasLeft+k.canvasPadding;b._visout=-(b.chartHeight+b.canvasHeight+1E3);b.base.drawGraph.apply(b,
arguments);b._ypvr=b.yAxis[0]&&b.yAxis[0].pixelValueRatio||0;V=b._yzero||0;l=s.dataset.attr("clip-rect",[b._visx,b.canvasTop,b._visw,b.canvasHeight]);Z=s.scroll||(s.scroll=c.group("scroll").insertAfter(s.layerAboveDataset));b.xlabels=[];b.xlabels.show=U.show;b.xlabels.rotate=U.rotate;b.xlabels.data=U.data||[];b.xlabels.css=U.css;b.xlabels.group=c.group("zoomline-plot-xlabels",s.datalabels);s.datalabels.transform(["T",da,i+h+k.scrollHeight+k.labelPadding]);b._lcmd=U.rotate?"y":"x";if(Q)Q=M.crispBound(0,
i-V,0,h,y),X=J["clip-pinrect"]=[Q.x,M.svg?i:Q.y,Q.width,Q.height],w=s.zoompin=c.group("zoompin").insertBefore(l).transform(b._pingrouptransform=["T",da,V]).hide(),J.pinrect=c.rect(0,i-V,b._visw,h,s.zoompin).attr({"stroke-width":0,stroke:"none",fill:k.pinPaneFill,"shape-rendering":"crisp",ishot:!0}),J.pintracker=c.rect(s.tracker).attr({transform:w.transform(),x:0,y:i-V,width:0,height:h,stroke:"none",fill:Qa,ishot:!0,cursor:M.svg&&"ew-resize"||"e-resize"}).drag(function(b){var c=da+b+this.__pindragdelta,
e=this.__pinboundleft,g=this.__pinboundright;c<e?c=e:c>g&&(c=g);w.transform(["T",c,V]);J.pintracker.transform(w.transform());this.__pindragoffset=b},function(){this.__pinboundleft=0-X[0]+da+(M.svg&&e||0);this.__pinboundright=this.__pinboundleft+aa-X[2];w._.clipispath=!0},function(){w._.clipispath=!1;this.__pindragdelta=this.__pindragoffset;delete this.__pindragoffset;delete this.__pinboundleft;delete this.__pinboundright}),b.pinButton=C.add("pinModeIcon",function(){b.activatePin(!b._zoominfo.pinned)},
{tooltip:B&&k.btnSwitchToPinModeTooltext||""});y++;Q=M.crispBound(e-y,i+h+y,g+y+y,k.scrollHeight,y);y--;J.zoomscroller=c.scroller(Q.x+(K&&-1||y%2),Q.y-(K&&4||2),Q.width-(!K&&2||0),Q.height,!0,{showButtons:!0,scrollRatio:Y.vdl/(Y.clen-!!Y.clen),scrollPosition:[Y.dsi/(Y.clen-Y.vdl-1),!1]},Z).attr({fill:k.scrollColor,r:K&&2||0}).scroll(b.updatePlotZoomline,b);K&&J.zoomscroller.shadow(!0);wa(b,function(c){var g=c.selectionLeft-e,c=g+c.selectionWidth;b.crossline&&b.crossline.hide();b[b._zoominfo.pinned?
"pinRangePixels":"zoomRangePixels"](g,c)},{attr:{stroke:k.zoomPaneStroke,fill:k.zoomPaneFill,strokeWidth:0}});b.zoomOutButton=C.add("zoomOutIcon",function(){b.zoomOut()},{tooltip:B&&k.btnZoomOutTooltext||""})[R&&"show"||"hide"]();b.resetButton=C.add("resetIcon",function(){b.resetZoom()},{tooltip:B&&k.btnResetChartTooltext||""}).hide();Q=b.resetButton.attr("fill");Q[2]="rgba(255,255,255,0)";b.resetButton.attr("fill",[Q[0],Q[1],Q[2],Q[3]]);b.crossline=new qa(b);b.updatePlotZoomline()}},drawPlotZoomline:function(b,
c){var e=this.paper,i=this._yzero||(this._yzero=this.yAxis[0].getAxisPosition(0)),g=c.attrs,h=c.visible,k=h?"show":"hide",l=this.layers.dataset,y=b.group||(b.group=e.group("plot-zoomline-dataset",l)),l=b.anchorGroup||(b.anchorGroup=e.group("plot-zoomline-anchors",l)),e=b.graphic||(b.graphic=e.path(void 0,y)),i=["T",this._visx,i];y.transform(i)[k]();l.transform(i)[k]();b.graphic=e.attr(g.graphics).shadow(g.shadow);b.attrPin=g.pin;b.visible=h;b.anchors=[];b.anchors.show=c.showAnchors;b.anchors.attrs=
g.anchors;b.anchors.attrsShadow=g.anchorShadow;b.anchors.left=-(g.anchors.r+g.anchors["stroke-width"]*0.5);b.anchors.right=this._visw-b.anchors.right},updatePlotZoomline:function(b,c){var e=this.paper,i=this._ypvr,g=this._visw,h=this.xlabels,l=h.css,k=h.group,y=this.plots,K,B,s,C,J,Q;!c&&(c=this._zoominfo);B=c.oppp;s=c.vdl=c.dei-c.dsi;c.ppl=c.oppl;C=c.ppl=c.nvl?g/c.nvl:c.oppl;g=c.step=(J=c.ppp=g/s)<B?X(B/J):1;B=c.lskip=X(C/J/g);b!==void 0?(C=(c.clen-s-1)*b,c.offset=(C-(C=ya(C)))*J,Q=C+s):(C=c.dsi,
Q=c.dei,c.offset=0);s=c.norm=C%g;c.ddsi=C-=s;c.ddei=Q=Q+2*g-s;c.pvr=i;i=h.show?X((Q-C)/g/B):0;B=c.llen-1;c.llen=i;if(i>B){s=B;for(B=i;s<B;s++)(K=h[s])&&K.show()||(h[s]=e.text(0,0,"",k).css(l))}else{s=i;for(B+=1;s<B;s++)h[s].hide()}i=J*g<c.amrd?0:X((Q-C)/g);J=i-c.alen;c.alen=i;for(g=y.length;g--;){l=y[g];k=l.anchors;if(k.show&&J){K=k.attrs;s=0;for(B=i;s<B;s++)k[s]=k[s]&&k[s].show()||e.circle(0,0,0,l.anchorGroup).attr(K);s=i;for(B=k.length;s<B;s++)k[s]&&k[s].hide()}this.drawPlotZoomlineGraphics(c,l.data,
l.graphic,k,!g&&h)}if(window.FC_DEV_ENVIRONMENT)FusionCharts.debugMode.enabled()?(this.debug=this.debug||($("#fc-zoominfo").length||$("body").append('<pre id="fc-zoominfo">'),$("#fc-zoominfo").css({position:"absolute",left:"10px",top:"0","pointer-events":"none",opacity:0.7,width:"250px",zIndex:"999",border:"1px solid #cccccc","box-shadow":"1px 1px 3px #cccccc",background:"#ffffff"})),this.debug.text(JSON.stringify(c,0,2))):($("#fc-zoominfo").remove(),delete this.debug)},drawPlotZoomlineGraphics:function(b,
c,e,i,g){var h=[],k=!b.cnd,l=b.ddei,y=b.clen,K=b.step,B=b.lskip,s=b.ppp,C=b.offset,J=b.pvr,Q=this._visw,M=this._visout,U=this._lcmd,R="M",V,w,X=g&&g[0],Z=X&&g.data,i=i[0],aa={},Y={},ca,ea=0,fa,la=-b.norm,b=b.ddsi,ha=0;for(X&&g.group.transform(["T",-C,0]);b<=l;b+=K,la+=K)if(fa=ea/3+ha,ca=la*s,(V=c[b])===void 0?(k&&(R="M"),w=M,g=ca-C,V=M,ha++):(h[ea++]=R,h[ea++]=w=g=ca-C,h[ea++]=V*=J,R="L"),i&&(i=i.attr((aa.cx=w,aa.cy=V,aa)).next),X&&!(fa%B))fa=X.attrs,w=Z[b]||"",g=g<0||g>Q?M:ca,fa.text===w?delete Y.text:
Y.text=w,fa[U]===g?delete Y[U]:Y[U]=g,X=X.attr(Y).next;if(l>=y){if((V=c[y-1])!==void 0)la-=l-y,h[ea++]="L",h[ea++]=la*s-C,h[ea++]=V*J;i&&i.attr((aa.cx=M,aa.cy=M,aa))}e.attr("path",h)},legendClick:function(b){var c=!b.visible,e=c?"show":"hide";b.group[e]();b.anchorGroup[e]();this.base.legendClick.apply(this,arguments);return b.visible=c}},Da["renderer.cartesian"]);qa=function(b){var c=b.paper,e=this.left=b._visx,i=this.width=b._visw,g=b.canvasTop,h=b.canvasHeight,k=b._visout,l=this.plots=b.plots,y=
b.layers.dataset,C=this.group=c.group("crossline-labels",y).attr({transform:["T",e,b._yzero]});this.tracker=c.rect(e,g,i,h,y).attr({stroke:"none","stroke-width":0,fill:Qa}).toFront().mousedown(this.onMouseDown,this).mouseup(this.onMouseUp,this,!0).mouseout(this.onMouseOut,this).mousemove(this.onMouseMove,this);this.line=c.path(void 0,y).attr({path:["M",e,g,"l",0,h],"stroke-opacity":0.2}).toBack();e=this.labels=c.set();i=b.options.crossline.style;this.hide();this.pixelRatio=b._ypvr;this.getZoomInfo=
function(){return b._zoominfo};this.getDataIndexFromPixel=function(c){return b.getValuePixel(c)};g=0;for(h=l.length;g<h;g++)y=l[g],y=y.graphic.attrs.stroke,e.push(c.text(0,k,"",C).css(i).attr({fill:y,"text-bound":["rgba(255,255,255,0.8)","rgba(0,0,0,0.2)",1,2]}))};qa.prototype.onMouseOut=function(){this.hide()};qa.prototype.onMouseDown=function(){this.hide();this._mouseIsDown=!0};qa.prototype.onMouseUp=function(){this.hide();delete this._mouseIsDown};qa.prototype.onMouseMove=function(b){if(!this._mouseIsDown){var c=
this.getZoomInfo(),e=this.line,i=c.step,g=c.ppp*i,b=(b.layerX||b.x)-this.left,h,b=(b+=g/2+c.offset)-b%g;h=(h=this.getDataIndexFromPixel(b))+h%i;b-=c.offset;e.transform(["T",ua(b),0]);if(h!==this.position||this.hidden)this.position=h,this.lineX=b,this.updateLabels();this.hidden&&this.show()}};qa.prototype.updateLabels=function(){var b=this.plots,c=this.width,e=this.position,i=this.lineX,g=this.pixelRatio,h;this.labels.forEach(function(k,l){h=b[l].data[e];k.attr({text:h+"",x:ua(i),y:h===void 0?-1E3:
h*g,"text-anchor":i<=0&&"start"||i>=c&&"end"||"middle"})})};qa.prototype.show=function(){this.hidden=!1;this.group.show();this.line.show()};qa.prototype.hide=function(){this.hidden=!0;this.group.hide();this.line.hide()};M.addSymbol({pinModeIcon:function(b,c,e){var i=e*0.5,g=b-e,h=b+e,k=b-i,l=b+i,y=b+0.5,C=y+1,B=y+1.5,s=c-e,J=c+i,M=c-i,i=c+(e-i);return["M",g,s,"L",k,M,k,i,g,J,b-0.5,J,b,c+e+0.5,y,J,h,J,l,i,l,M,h,s,B,s,B,M,B,i,C,i,C,M,B,M,B,s,"Z"]},zoomOutIcon:function(b,c,e){b-=e*0.2;c-=e*0.2;var i=
e*0.8,g=M.rad(43),h=M.rad(48),k=b+i*Fa(g),g=c+i*Ga(g),l=b+i*Fa(h),h=c+i*Ga(h),y=M.rad(45),C=k+e*Fa(y),B=g+e*Ga(y),s=l+e*Fa(y),e=h+e*Ga(y);return["M",k,g,"A",i,i,0,1,0,l,h,"Z","M",k+1,g+1,"L",C,B,s,e,l+1,h+1,"Z","M",b-2,c,"L",b+2,c,"Z"]},resetIcon:function(b,c,e){var i=b-e,g=(V.PI/2+V.PI)/2;b+=e*Fa(g);var g=c+e*Ga(g),h=e*2/3;return["M",i,c,"A",e,e,0,1,1,b,g,"L",b+h,g-1,b+2,g+h-0.5,b,g]}})}]);