package com;
// 类名和文件名称不需要对应  

// 需要的类的所在包 是在src/main/java 目录下的类文件
import com.us.demo.age.person.Person;

function void printName(String name,String desc){
	System.out.println("name:"+name+" desc:"+desc);
}

rule "boy"
	// salience 1
	when 
		$p : Person(age>0)
	then
		$p.setDesc("少年");
		//retract($p);
		printName($p.getName(),$p.getDesc());
	end

rule "youth"
	// salience 2
	when 
		$p : Person(age>35)
	then
		$p.setDesc("青年");
		//retract($p);
		printName($p.getName(),$p.getDesc());
	end
	

	

rule "all receive"
	//salience 4
	// salience是优先级 数字越大 执行的优先级越高
	when
		$p:Person(age>35&&age<60);
	then
		$p.setDesc("是个人");
		//retract($p);
		printName($p.getName(),$p.getDesc());
		//printName($p.getName,$p.getDesc());
	end
	
 //rule "old"
   //salience 5
  // when 
   		//$p:Person(age>60 && age<80)
  // then 
   		//$p.setDesc("老年");
   		// $p.setDesc("$p");
   		// bug 出现在这边，赋值参数写错了，所以会报那样的错误 粗心导致
   		//retract($p);
   	//	printName($p.getName(),$p.getDesc());
   	//	modify($p){
   	//	setAge(5)
   		// $p.setAge(5)
   		//Compilation error $p cannot be resolved or is not a field
   		// 注意 这边直接调用方法， 不用表明对象
   		// modify() 可以传入多个参数么？
   		// modify之后 会重新放入memory之内 也就是再次重新运行这个规则文件 从头再来
   //	};
   //end



