DROP TABLE IF EXISTS user;

CREATE TABLE user
(
    id BIGINT(20) NOT NULL COMMENT '主键ID',
    username VARCHAR(30) NULL DEFAULT NULL COMMENT '用户名',
    password VARCHAR(255) NULL DEFAULT NULL COMMENT '密码',
    email VARCHAR(255) NULL DEFAULT NULL COMMENT '邮箱',
    sm2 VARCHAR(800) NULL DEFAULT NULL COMMENT '国密SM2非对称算法',
    sm3 VARCHAR(255) NULL DEFAULT NULL COMMENT '国密SM3签名算法',
    PRIMARY KEY (id)
);