package com.hanke.hbrid.template.drools
import com.hanke.preag.core.domain.ContentElements;
import com.hanke.preag.dto.RuleCondition;

rule "fertilizationRule_41" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Al")&&value<=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Al", 50.0, 0.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.5);
end

rule "fertilizationRule_40" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Mg")&&value<=100.0&&value>=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Mg", 100.0, 50.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.3);
end

rule "fertilizationRule_39" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("P")&&value>=100.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("P", 0.0, 100.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.2);
end

rule "fertilizationRule_38" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("S")&&value<=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("S", 50.0, 0.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.5);
end

rule "fertilizationRule_37" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Cu")&&value>=100.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Cu", 0.0, 100.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.2);
end

rule "fertilizationRule_36" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("B")&&value<=100.0&&value>=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("B", 100.0, 50.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.3);
end

rule "fertilizationRule_35" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Al")&&value<=100.0&&value>=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Al", 100.0, 50.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.3);
end

rule "fertilizationRule_34" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("B")&&value>=100.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("B", 0.0, 100.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.2);
end

rule "fertilizationRule_33" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Ca")&&value<=100.0&&value>=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Ca", 100.0, 50.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.3);
end

rule "fertilizationRule_32" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("K")&&value<=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("K", 50.0, 0.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.5);
end

rule "fertilizationRule_31" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("N")&&value<=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("N", 50.0, 0.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.5);
end

rule "fertilizationRule_30" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Mg")&&value>=100.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Mg", 0.0, 100.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.2);
end

rule "fertilizationRule_29" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("N")&&value<=100.0&&value>=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("N", 100.0, 50.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.3);
end

rule "fertilizationRule_28" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Mn")&&value>=100.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Mn", 0.0, 100.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.2);
end

rule "fertilizationRule_27" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("K")&&value<=100.0&&value>=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("K", 100.0, 50.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.3);
end

rule "fertilizationRule_26" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("P")&&value<=100.0&&value>=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("P", 100.0, 50.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.3);
end

rule "fertilizationRule_25" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Mn")&&value<=100.0&&value>=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Mn", 100.0, 50.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.3);
end

rule "fertilizationRule_24" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Cl")&&value>=100.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Cl", 0.0, 100.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.2);
end

rule "fertilizationRule_23" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Zn")&&value<=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Zn", 50.0, 0.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.5);
end

rule "fertilizationRule_22" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Ca")&&value>=100.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Ca", 0.0, 100.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.2);
end

rule "fertilizationRule_21" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Mo")&&value<=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Mo", 50.0, 0.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.5);
end

rule "fertilizationRule_20" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Fe")&&value>=100.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Fe", 0.0, 100.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.2);
end

rule "fertilizationRule_19" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("B")&&value<=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("B", 50.0, 0.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.5);
end

rule "fertilizationRule_18" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Fe")&&value<=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Fe", 50.0, 0.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.5);
end

rule "fertilizationRule_17" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Cu")&&value<=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Cu", 50.0, 0.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.5);
end

rule "fertilizationRule_16" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("S")&&value<=100.0&&value>=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("S", 100.0, 50.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.3);
end

rule "fertilizationRule_15" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Cl")&&value<=100.0&&value>=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Cl", 100.0, 50.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.3);
end

rule "fertilizationRule_14" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Cl")&&value<=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Cl", 50.0, 0.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.5);
end

rule "fertilizationRule_13" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("P")&&value<=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("P", 50.0, 0.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.5);
end

rule "fertilizationRule_12" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Zn")&&value>=100.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Zn", 0.0, 100.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.2);
end

rule "fertilizationRule_11" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Mg")&&value<=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Mg", 50.0, 0.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.5);
end

rule "fertilizationRule_10" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("S")&&value>=100.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("S", 0.0, 100.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.2);
end

rule "fertilizationRule_9" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Zn")&&value<=100.0&&value>=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Zn", 100.0, 50.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.3);
end

rule "fertilizationRule_8" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Fe")&&value<=100.0&&value>=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Fe", 100.0, 50.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.3);
end

rule "fertilizationRule_7" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Cu")&&value<=100.0&&value>=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Cu", 100.0, 50.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.3);
end

rule "fertilizationRule_6" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Al")&&value>=100.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Al", 0.0, 100.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.2);
end

rule "fertilizationRule_5" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Mo")&&value>=100.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Mo", 0.0, 100.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.2);
end

rule "fertilizationRule_4" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Mo")&&value<=100.0&&value>=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Mo", 100.0, 50.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.3);
end

rule "fertilizationRule_3" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Ca")&&value<=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Ca", 50.0, 0.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.5);
end

rule "fertilizationRule_2" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("K")&&value>=100.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("K", 0.0, 100.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.2);
end

rule "fertilizationRule_1" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("Mn")&&value<=50.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("Mn", 50.0, 0.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.5);
end

rule "fertilizationRule_0" 
	ruleflow-group "fertilizationrule_group"
    when
    	$elems : ContentElements(type.toString.equals("N")&&value>=100.0)
    then
    	RuleCondition ruleCondition = new RuleCondition("N", 0.0, 100.0);
    	$elems.setCondition(ruleCondition);
    	$elems.setConclusion(1.2);
end