(function(){function h(a){throw a;}var i=true,j=null,l=false,aa=navigator,ba=Error,ca=Boolean,m=undefined,da=encodeURIComponent,ea=parseInt,fa=parseFloat,n=String,p=window,ga=Number,r=Object,t=document,ha=decodeURIComponent,ia=RegExp,ja=Array,v=Math;function ka(a,b){return a.toString=b}function la(a,b){return a.length=b}function ma(a,b){return a.className=b}function na(a,b){return a.width=b}function oa(a,b){return a.cancel=b}function pa(a,b){return a.innerHTML=b}function qa(a,b){return a.value=b}
function ra(a,b){return a.currentTarget=b}function sa(a,b){return a.left=b}function ta(a,b){return a.target=b}function ua(a,b){return a.send=b}function va(a,b){return a.isAvailable=b}function wa(a,b){return a.bottom=b}function xa(a,b){return a.restore=b}function ya(a,b){return a.display=b}function za(a,b){return a.isSupported=b}function Aa(a,b){return a.height=b}function Ba(a,b){return a.right=b}
var x="appendChild",Ca="scrollTop",Da="previousSibling",y="push",z="toString",A="length",Ea="propertyIsEnumerable",Fa="getBoundingClientRect",Ga="plugins",B="prototype",Ha="test",Ia="shift",Ja="className",Ka="exec",La="clearTimeout",D="width",Ma="index",Na="text",Oa="clientWidth",Pa="cancel",Qa="round",Ra="abort",Sa="slice",Ta="setTimeout",E="replace",F="nodeType",Ua="document",Va="split",Wa="offsetWidth",Xa="concat",Ya="createTextNode",Za="value",$a="location",ab="item",bb="insertBefore",G="indexOf",
cb="message",db="hasOwnProperty",H="dispatchEvent",I="style",eb="close",fb="nodeName",gb="currentTarget",J="body",K="left",hb="write",ib="ownerDocument",jb="removeChild",kb="target",lb="screenX",mb="screenY",nb="lastChild",L="call",ob="match",pb="getBoxObjectFor",qb="send",rb="createElement",sb="protocol",tb="keyCode",M="firstChild",ub="forEach",vb="isAvailable",wb="clientHeight",xb="scrollLeft",yb="clientLeft",zb="bottom",Ab="currentStyle",Bb="href",Cb="substring",Db="clientTop",Eb="handleEvent",
Fb="restore",Gb="type",Hb="apply",Ib="translate",Jb="parentWindow",N="tagName",Kb="setPosition",Lb="reset",Mb="defaultView",Nb="name",O="parentNode",Ob="fileName",Pb="isSupported",Qb="nextSibling",Rb="contentWindow",P="height",Sb="offsetHeight",Tb="join",Ub="getElementsByTagName",Vb="nodeValue",Wb="documentElement",Xb="substr",Yb="right";function Zb(a){return function(b){this[a]=b}}function $b(a){return function(){return this[a]}}var Q,ac=ac||{},R=this;
function bc(a,b,c){a=a[Va](".");c=c||R;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a[A]&&(d=a[Ia]());)if(!a[A]&&b!==m)c[d]=b;else c=c[d]?c[d]:c[d]={}}function cc(a,b){for(var c=a[Va]("."),d=b||R,e;e=c[Ia]();)if(d[e])d=d[e];else return j;return d}function dc(){}function ec(a){a.Dc=function(){return a.Hd||(a.Hd=new a)}}
function fc(a){var b=typeof a;if(b=="object")if(a){if(a instanceof ja||!(a instanceof r)&&r[B][z][L](a)=="[object Array]"||typeof a[A]=="number"&&typeof a.splice!="undefined"&&typeof a[Ea]!="undefined"&&!a[Ea]("splice"))return"array";if(!(a instanceof r)&&(r[B][z][L](a)=="[object Function]"||typeof a[L]!="undefined"&&typeof a[Ea]!="undefined"&&!a[Ea]("call")))return"function"}else return"null";else if(b=="function"&&typeof a[L]=="undefined")return"object";return b}
function gc(a){return fc(a)=="array"}function hc(a){var b=fc(a);return b=="array"||b=="object"&&typeof a[A]=="number"}function ic(a){return typeof a=="string"}function jc(a){return fc(a)=="function"}function kc(a){a=fc(a);return a=="object"||a=="array"||a=="function"}function lc(a){return a[mc]||(a[mc]=++nc)}var mc="closure_uid_"+v.floor(v.random()*2147483648)[z](36),nc=0;
function T(a,b){var c=b||R;if(arguments[A]>2){var d=ja[B][Sa][L](arguments,2);return function(){var e=ja[B][Sa][L](arguments);ja[B].unshift[Hb](e,d);return a[Hb](c,e)}}else return function(){return a[Hb](c,arguments)}}function oc(a){var b=ja[B][Sa][L](arguments,1);return function(){var c=ja[B][Sa][L](arguments);c.unshift[Hb](c,b);return a[Hb](this,c)}}var pc=Date.now||function(){return+new Date};function V(a,b){function c(){}c.prototype=b[B];a.s=b[B];a.prototype=new c;a[B].constructor=a};var qc=google[Ib]._const,rc=qc._cl||"en",sc=qc._cuc,tc=qc._cnad||l,uc=qc._cnal||{},vc=qc._cam=="lib"?1:0,wc;a:{for(var xc=t[Ub]("meta"),yc=0;yc<xc[A];++yc)if(xc[yc][Nb]=="google-translate-customization"){wc=xc[yc].content;break a}wc=""}
var zc=wc,Ac=(qc._cac||"te")+(vc==1?"_lib":""),Bc=qc._pah||"",Cc=qc._pbi||"",Dc=qc._pci||"",Ec=qc._phf||"",Fc=qc._plla||"",Gc=qc._pli||"",Hc=qc._pmi||"",Ic=qc._ps||"",Jc=qc._puh||"",Kc=p[$a][sb]=="https:"?"https://":"http://",Lc=Kc+"www.google.com/images/cleardot.gif",Mc=Kc+"www.google.com/intl/"+rc[E]("_","-")+"/images/logos/translate_logo_sm.png",Nc="http://"+Jc+"/translate_suggestion";function Oc(){}Oc[B].qc=l;Oc[B].p=function(){if(!this.qc){this.qc=i;this.r()}};Oc[B].r=function(){};function Pc(a){return a[E](/^[\s\xa0]+|[\s\xa0]+$/g,"")}function Qc(a){return a[E](/^[\s\xa0]+/,"")}function Rc(a){return a[E](/[\s\xa0]+$/,"")}var Sc=/^[a-zA-Z0-9\-_.!~*'()]*$/;function Tc(a){a=n(a);if(!Sc[Ha](a))return da(a);return a}
function Uc(a,b){if(b)return a[E](Vc,"&amp;")[E](Wc,"&lt;")[E](Xc,"&gt;")[E](Yc,"&quot;");else{if(!Zc[Ha](a))return a;if(a[G]("&")!=-1)a=a[E](Vc,"&amp;");if(a[G]("<")!=-1)a=a[E](Wc,"&lt;");if(a[G](">")!=-1)a=a[E](Xc,"&gt;");if(a[G]('"')!=-1)a=a[E](Yc,"&quot;");return a}}var Vc=/&/g,Wc=/</g,Xc=/>/g,Yc=/\"/g,Zc=/[&<>\"]/;
function $c(a){if(a[G]("&")!=-1){if("document"in R&&a[G]("<")==-1){a=a;var b=R[Ua][rb]("div");pa(b,"<pre>"+a+"</pre>");b[M].normalize&&b[M].normalize();a=b[M][M][Vb];pa(b,"");a=a[E](/(\r\n|\r|\n)/g,"\n")}else a=ad(a);return a}return a}function ad(a){return a[E](/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c.charAt(0)=="#"){var d=ga("0"+c[Xb](1));if(!isNaN(d))return n.fromCharCode(d)}return b}})}
function bd(a,b){for(var c=0,d=Pc(n(a))[Va]("."),e=Pc(n(b))[Va]("."),f=v.max(d[A],e[A]),g=0;c==0&&g<f;g++){var k=d[g]||"",o=e[g]||"",q=ia("(\\d*)(\\D*)","g"),w=ia("(\\d*)(\\D*)","g");do{var s=q[Ka](k)||["","",""],u=w[Ka](o)||["","",""];if(s[0][A]==0&&u[0][A]==0)break;c=s[1][A]==0?0:ea(s[1],10);var U=u[1][A]==0?0:ea(u[1],10);c=cd(c,U)||cd(s[2][A]==0,u[2][A]==0)||cd(s[2],u[2])}while(c==0)}return c}function cd(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var dd=ja[B],ed=dd[G]?function(a,b,c){return dd[G][L](a,b,c)}:function(a,b,c){c=c==j?0:c<0?v.max(0,a[A]+c):c;if(ic(a)){if(!ic(b)||b[A]!=1)return-1;return a[G](b,c)}for(c=c;c<a[A];c++)if(c in a&&a[c]===b)return c;return-1},fd=dd[ub]?function(a,b,c){dd[ub][L](a,b,c)}:function(a,b,c){for(var d=a[A],e=ic(a)?a[Va](""):a,f=0;f<d;f++)f in e&&b[L](c,e[f],f,a)};function gd(a,b){return ed(a,b)>=0}function hd(a,b){var c=ed(a,b),d;if(d=c>=0){var e=a;c=c;dd.splice[L](e,c,1)}return d}
function id(){return dd[Xa][Hb](dd,arguments)}function jd(a){if(gc(a))return id(a);else{for(var b=[],c=0,d=a[A];c<d;c++)b[c]=a[c];return b}}function kd(a){for(var b=1;b<arguments[A];b++){var c=arguments[b],d;if(gc(c)||(d=hc(c))&&c[db]("callee"))a[y][Hb](a,c);else if(d)for(var e=a[A],f=c[A],g=0;g<f;g++)a[e+g]=c[g];else a[y](c)}}function ld(a){return dd.splice[Hb](a,md(arguments,1))}function md(a,b,c){return arguments[A]<=2?dd[Sa][L](a,b):dd[Sa][L](a,b,c)};function nd(a,b){this.x=a!==m?a:0;this.y=b!==m?b:0}nd[B].Q=function(){return new nd(this.x,this.y)};function od(a,b){return new nd(a.x-b.x,a.y-b.y)};function pd(a,b){na(this,a);Aa(this,b)}pd[B].Q=function(){return new pd(this[D],this[P])};pd[B].floor=function(){na(this,v.floor(this[D]));Aa(this,v.floor(this[P]));return this};pd[B].round=function(){na(this,v[Qa](this[D]));Aa(this,v[Qa](this[P]));return this};function qd(a,b,c){for(var d in a)b[L](c,a[d],d,a)}function rd(a){var b=[],c=0;for(var d in a)b[c++]=a[d];return b}function td(a){var b=[],c=0;for(var d in a)b[c++]=d;return b}function ud(a,b){var c;if(c=b in a)delete a[b];return c}var vd=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];
function wd(a){for(var b,c,d=1;d<arguments[A];d++){c=arguments[d];for(b in c)a[b]=c[b];for(var e=0;e<vd[A];e++){b=vd[e];if(r[B][db][L](c,b))a[b]=c[b]}}};var xd,yd,zd,Ad,Bd,Cd,Dd;function Ed(){return R.navigator?R.navigator.userAgent:j}function Fd(){return R.navigator}Bd=Ad=zd=yd=xd=l;var Gd;if(Gd=Ed()){var Hd=Fd();xd=Gd[G]("Opera")==0;yd=!xd&&Gd[G]("MSIE")!=-1;Ad=(zd=!xd&&Gd[G]("WebKit")!=-1)&&Gd[G]("Mobile")!=-1;Bd=!xd&&!zd&&Hd.product=="Gecko"}var Id=xd,W=yd,Jd=Bd,Kd=zd,Ld=Ad,Md,Nd=Fd(),Od=Md=Nd&&Nd.platform||"";Cd=Od[G]("Mac")!=-1;Od[G]("Win");Od[G]("Linux");Dd=!!Fd()&&(Fd().appVersion||"")[G]("X11")!=-1;var Pd=Cd,Qd=Dd,Rd;
a:{var Sd="",Td;if(Id&&R.opera){var Ud=R.opera.version;Sd=typeof Ud=="function"?Ud():Ud}else{if(Jd)Td=/rv\:([^\);]+)(\)|;)/;else if(W)Td=/MSIE\s+([^\);]+)(\)|;)/;else if(Kd)Td=/WebKit\/(\S+)/;if(Td){var Vd=Td[Ka](Ed());Sd=Vd?Vd[1]:""}}if(W){var Wd,Xd=R[Ua];Wd=Xd?Xd.documentMode:m;if(Wd>fa(Sd)){Rd=n(Wd);break a}}Rd=Sd}var Yd=Rd,Zd={};function $d(a){return Zd[a]||(Zd[a]=bd(Yd,a)>=0)};var ae,be=!W||$d("9"),ce=W&&!$d("9");function de(a){return(a=a[Ja])&&typeof a[Va]=="function"?a[Va](/\s+/):[]}function ee(a){var b=de(a),c=md(arguments,1),d;d=b;c=c;for(var e=0,f=0;f<c[A];f++)if(!gd(d,c[f])){d[y](c[f]);e++}d=e==c[A];ma(a,b[Tb](" "));return d}function fe(a){var b=de(a),c=md(arguments,1),d;d=b;c=c;for(var e=0,f=0;f<d[A];f++)if(gd(c,d[f])){ld(d,f--,1);e++}d=e==c[A];ma(a,b[Tb](" "));return d};function ge(a){return a?new he(ie(a)):ae||(ae=new he)}
function je(a,b,c,d){a=d||a;b=b&&b!="*"?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(!Kd||ke(t)||$d("528"))&&(b||c)){c=b+(c?"."+c:"");return a.querySelectorAll(c)}if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,g;g=a[f];f++)if(b==g[fb])d[e++]=g;la(d,e);return d}else return a}a=a[Ub](b||"*");if(c){d={};for(f=e=0;g=a[f];f++){b=g[Ja];if(typeof b[Va]=="function"&&gd(b[Va](/\s+/),c))d[e++]=g}la(d,e);return d}else return a}
function le(a,b){qd(b,function(c,d){if(d=="style")a[I].cssText=c;else if(d=="class")ma(a,c);else if(d=="for")a.htmlFor=c;else if(d in me)a.setAttribute(me[d],c);else a[d]=c})}var me={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"};
function ne(a){var b=a[Ua];if(Kd&&!$d("500")&&!Ld){if(typeof a.innerHeight=="undefined")a=p;b=a.innerHeight;var c=a[Ua][Wb].scrollHeight;if(a==a.top)if(c<b)b-=15;return new pd(a.innerWidth,b)}a=ke(b);if(Id&&!$d("9.50"))a=l;a=a?b[Wb]:b[J];return new pd(a[Oa],a[wb])}function oe(a){a=!Kd&&ke(a)?a[Wb]:a[J];return new nd(a[xb],a[Ca])}function pe(){return qe(t,arguments)}
function qe(a,b){var c=b[0],d=b[1];if(!be&&d&&(d[Nb]||d[Gb])){c=["<",c];d[Nb]&&c[y](' name="',Uc(d[Nb]),'"');if(d[Gb]){c[y](' type="',Uc(d[Gb]),'"');var e={};wd(e,d);d=e;delete d[Gb]}c[y](">");c=c[Tb]("")}c=a[rb](c);if(d)if(ic(d))ma(c,d);else gc(d)?ee[Hb](j,[c][Xa](d)):le(c,d);b[A]>2&&re(a,c,b,2);return c}function re(a,b,c,d){function e(g){if(g)b[x](ic(g)?a[Ya](g):g)}for(d=d;d<c[A];d++){var f=c[d];hc(f)&&!(kc(f)&&f[F]>0)?fd(se(f)?jd(f):f,e):e(f)}}function ke(a){return a.compatMode=="CSS1Compat"}
function te(a,b){a[x](b)}function ue(a){re(ie(a),a,arguments,1)}function ve(a){for(var b;b=a[M];)a[jb](b)}function we(a,b){b[O]&&b[O][bb](a,b)}function xe(a){return a&&a[O]?a[O][jb](a):j}function ye(a,b){var c=b[O];c&&c.replaceChild(a,b)}function ze(a,b){if(a.contains&&b[F]==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||ca(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b[O];return b==a}function ie(a){return a[F]==9?a:a[ib]||a[Ua]}
function Ae(a){return a=Kd?a[Ua]||a[Rb][Ua]:a.contentDocument||a[Rb][Ua]}function Be(a,b){if("textContent"in a)a.textContent=b;else if(a[M]&&a[M][F]==3){for(;a[nb]!=a[M];)a[jb](a[nb]);a[M].data=b}else{ve(a);var c=ie(a);a[x](c[Ya](b))}}var Ce={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},De={IMG:" ",BR:"\n"};
function Ee(a){if(ce&&"innerText"in a)a=a.innerText[E](/(\r\n|\r|\n)/g,"\n");else{var b=[];Fe(a,b,i);a=b[Tb]("")}a=a[E](/ \xAD /g," ")[E](/\xAD/g,"");W||(a=a[E](/ +/g," "));if(a!=" ")a=a[E](/^\s*/,"");return a}function Fe(a,b,c){if(!(a[fb]in Ce))if(a[F]==3)c?b[y](n(a[Vb])[E](/(\r\n|\r|\n)/g,"")):b[y](a[Vb]);else if(a[fb]in De)b[y](De[a[fb]]);else for(a=a[M];a;){Fe(a,b,c);a=a[Qb]}}
function se(a){if(a&&typeof a[A]=="number")if(kc(a))return typeof a[ab]=="function"||typeof a[ab]=="string";else if(jc(a))return typeof a[ab]=="function";return l}function he(a){this.a=a||R[Ua]||t}function Ge(a){return a.a}Q=he[B];Q.n=function(a){return ic(a)?this.a.getElementById(a):a};Q.Wc=he[B].n;Q.t=function(){return qe(this.a,arguments)};Q.createElement=function(a){return this.a[rb](a)};Q.createTextNode=function(a){return this.a[Ya](a)};function He(a){return ke(a.a)}
function Ie(a){return oe(a.a)}Q.appendChild=te;Q.H=ue;Q.hc=ve;Q.removeNode=xe;Q.contains=ze;Q.Ib=Be;var Je;!W||$d("9");W&&$d("8");function Ke(a,b){this.type=a;ta(this,b);ra(this,this[kb])}V(Ke,Oc);Ke[B].r=function(){delete this[Gb];delete this[kb];delete this[gb]};Ke[B].a=l;Ke[B].b=i;function Le(a,b){a&&Me(this,a,b)}V(Le,Ke);Q=Le[B];ta(Q,j);Q.relatedTarget=j;Q.offsetX=0;Q.offsetY=0;Q.clientX=0;Q.clientY=0;Q.screenX=0;Q.screenY=0;Q.button=0;Q.keyCode=0;Q.charCode=0;Q.ctrlKey=l;Q.altKey=l;Q.shiftKey=l;Q.metaKey=l;Q.Pd=l;Q.yc=j;
function Me(a,b,c){var d=a.type=b[Gb];ta(a,b[kb]||b.srcElement);ra(a,c);if(c=b.relatedTarget){if(Jd)try{c=c[fb]&&c}catch(e){c=j}}else if(d=="mouseover")c=b.fromElement;else if(d=="mouseout")c=b.toElement;a.relatedTarget=c;a.offsetX=b.offsetX!==m?b.offsetX:b.layerX;a.offsetY=b.offsetY!==m?b.offsetY:b.layerY;a.clientX=b.clientX!==m?b.clientX:b.pageX;a.clientY=b.clientY!==m?b.clientY:b.pageY;a.screenX=b[lb]||0;a.screenY=b[mb]||0;a.button=b.button;a.keyCode=b[tb]||0;a.charCode=b.charCode||(d=="keypress"?
b[tb]:0);a.ctrlKey=b.ctrlKey;a.altKey=b.altKey;a.shiftKey=b.shiftKey;a.metaKey=b.metaKey;a.Pd=Pd?b.metaKey:b.ctrlKey;a.yc=b;delete a.b;delete a.a}Q.r=function(){Le.s.r[L](this);this.yc=j;ta(this,j);ra(this,j);this.relatedTarget=j};function Ne(a,b){this.d=b;this.b=[];var c=a;if(c>this.d)h(ba("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var d=0;d<c;d++)this.b[y](this.a?this.a():{})}V(Ne,Oc);Ne[B].a=j;Ne[B].c=j;function Oe(a){if(a.b[A])return a.b.pop();return a.a?a.a():{}}function Pe(a,b){a.b[A]<a.d?a.b[y](b):Qe(a,b)}function Qe(a,b){if(a.c)a.c(b);else if(kc(b))if(jc(b.p))b.p();else for(var c in b)delete b[c]}Ne[B].r=function(){Ne.s.r[L](this);for(var a=this.b;a[A];)Qe(this,a.pop());delete this.b};var Re,Se,Te="ScriptEngine"in R;Se=(Re=Te&&R.ScriptEngine()=="JScript")?R.ScriptEngineMajorVersion()+"."+R.ScriptEngineMinorVersion()+"."+R.ScriptEngineBuildVersion():"0";var Ue=Re,Ve=Se;function We(){}var Xe=0;We[B].ga=0;We[B].ab=l;We[B].a=l;We[B].handleEvent=function(a){if(this.b)return this.Va[L](this.Bb||this.src,a);return this.Va[Eb][L](this.Va,a)};var Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf;
(function(){function a(){return{o:0,ca:0}}function b(){return[]}function c(){function u(U){return g[L](u.src,u.ga,U)}return u}function d(){return new We}function e(){return new Le}var f=Ue&&!(bd(Ve,"5.7")>=0),g;cf=function(u){g=u};if(f){Ye=function(){return Oe(k)};Ze=function(u){Pe(k,u)};$e=function(){return Oe(o)};af=function(u){Pe(o,u)};bf=function(){return Oe(q)};df=function(){Pe(q,c())};ef=function(){return Oe(w)};ff=function(u){Pe(w,u)};gf=function(){return Oe(s)};hf=function(u){Pe(s,u)};var k=
new Ne(0,600);k.a=a;var o=new Ne(0,600);o.a=b;var q=new Ne(0,600);q.a=c;var w=new Ne(0,600);w.a=d;var s=new Ne(0,600);s.a=e}else{Ye=a;Ze=dc;$e=b;af=dc;bf=c;df=dc;ef=d;ff=dc;gf=e;hf=dc}})();var jf={},kf={},lf={},mf="on",nf={};
function of(a,b,c,d,e){if(b)if(gc(b)){for(var f=0;f<b[A];f++)of(a,b[f],c,d,e);return j}else{d=!!d;var g=kf;b in g||(g[b]=Ye());g=g[b];if(!(d in g)){g[d]=Ye();g.o++}g=g[d];var k=lc(a),o;g.ca++;if(g[k]){o=g[k];for(f=0;f<o[A];f++){g=o[f];if(g.Va==c&&g.Bb==e){if(g.ab)break;return o[f].ga}}}else{o=g[k]=$e();g.o++}f=bf();f.src=a;var q=g=ef();c=c;var w=f,s=a,u=b,U=d;e=e;if(jc(c))q.b=i;else if(c&&c[Eb]&&jc(c[Eb]))q.b=l;else h(ba("Invalid listener argument"));q.Va=c;q.c=w;q.src=s;q.type=u;q.hb=!!U;q.Bb=e;
q.a=l;q.ga=++Xe;q.ab=l;e=g.ga;f.ga=e;o[y](g);jf[e]=g;lf[k]||(lf[k]=$e());lf[k][y](g);if(a.addEventListener){if(a==R||!a.vc)a.addEventListener(b,f,d)}else a.attachEvent(pf(b),f);return e}else h(ba("Invalid event type"))}function qf(a,b,c,d,e){if(gc(b)){for(var f=0;f<b[A];f++)qf(a,b[f],c,d,e);return j}d=!!d;a=rf(a,b,d);if(!a)return l;for(f=0;f<a[A];f++)if(a[f].Va==c&&a[f].hb==d&&a[f].Bb==e)return sf(a[f].ga);return l}
function sf(a){if(!jf[a])return l;var b=jf[a];if(b.ab)return l;var c=b.src,d=b[Gb],e=b.c,f=b.hb;if(c.removeEventListener){if(c==R||!c.vc)c.removeEventListener(d,e,f)}else c.detachEvent&&c.detachEvent(pf(d),e);c=lc(c);e=kf[d][f][c];if(lf[c]){var g=lf[c];hd(g,b);g[A]==0&&delete lf[c]}b.ab=i;e.Kc=i;tf(d,f,c,e);delete jf[a];return i}
function tf(a,b,c,d){if(!d.Db)if(d.Kc){for(var e=0,f=0;e<d[A];e++)if(d[e].ab){var g=d[e].c;g.src=j;df(g);ff(d[e])}else{if(e!=f)d[f]=d[e];f++}la(d,f);d.Kc=l;if(f==0){af(d);delete kf[a][b][c];kf[a][b].o--;if(kf[a][b].o==0){Ze(kf[a][b]);delete kf[a][b];kf[a].o--}if(kf[a].o==0){Ze(kf[a]);delete kf[a]}}}}
function uf(a,b,c){var d=0,e=a==j,f=b==j,g=c==j;c=!!c;if(e)qd(lf,function(o){for(var q=o[A]-1;q>=0;q--){var w=o[q];if((f||b==w[Gb])&&(g||c==w.hb)){sf(w.ga);d++}}});else{a=lc(a);if(lf[a]){a=lf[a];for(e=a[A]-1;e>=0;e--){var k=a[e];if((f||b==k[Gb])&&(g||c==k.hb)){sf(k.ga);d++}}}}return d}function rf(a,b,c){var d=kf;if(b in d){d=d[b];if(c in d){d=d[c];a=lc(a);if(d[a])return d[a]}}return j}function pf(a){if(a in nf)return nf[a];return nf[a]=mf+a}
function vf(a,b,c,d,e){var f=1;b=lc(b);if(a[b]){a.ca--;a=a[b];if(a.Db)a.Db++;else a.Db=1;try{for(var g=a[A],k=0;k<g;k++){var o=a[k];if(o&&!o.ab)f&=wf(o,e)!==l}}finally{a.Db--;tf(c,d,b,a)}}return ca(f)}function wf(a,b){var c=a[Eb](b);a.a&&sf(a.ga);return c}
function xf(a,b){if(!jf[a])return i;var c=jf[a],d=c[Gb],e=kf;if(!(d in e))return i;e=e[d];var f,g,k;if(Je===m)Je=W&&!R.addEventListener;if(k=Je){f=b||cc("window.event");k=i in e;var o=l in e;if(k){if(f[tb]<0||f.returnValue!=m)return i;a:{var q=f,w=l;if(q[tb]==0)try{q.keyCode=-1;break a}catch(s){w=i}if(w||q.returnValue==m)q.returnValue=i}}q=gf();Me(q,f,this);f=i;try{if(k){for(var u=$e(),U=q[gb];U;U=U[O])u[y](U);g=e[i];g.ca=g.o;for(var S=u[A]-1;!q.a&&S>=0&&g.ca;S--){ra(q,u[S]);f&=vf(g,u[S],d,i,q)}if(o){g=
e[l];g.ca=g.o;for(S=0;!q.a&&S<u[A]&&g.ca;S++){ra(q,u[S]);f&=vf(g,u[S],d,l,q)}}}else f=wf(c,q)}finally{if(u){la(u,0);af(u)}q.p();hf(q)}return f}d=new Le(b,this);try{f=wf(c,d)}finally{d.p()}return f}cf(xf);function yf(a,b,c,d){this.top=a;Ba(this,b);wa(this,c);sa(this,d)}yf[B].Q=function(){return new yf(this.top,this[Yb],this[zb],this[K])};yf[B].contains=function(a){a=!this||!a?l:a instanceof yf?a[K]>=this[K]&&a[Yb]<=this[Yb]&&a.top>=this.top&&a[zb]<=this[zb]:a.x>=this[K]&&a.x<=this[Yb]&&a.y>=this.top&&a.y<=this[zb];return a};function zf(a,b,c,d){sa(this,a);this.top=b;na(this,c);Aa(this,d)}zf[B].Q=function(){return new zf(this[K],this.top,this[D],this[P])};zf[B].contains=function(a){return a instanceof zf?this[K]<=a[K]&&this[K]+this[D]>=a[K]+a[D]&&this.top<=a.top&&this.top+this[P]>=a.top+a[P]:a.x>=this[K]&&a.x<=this[K]+this[D]&&a.y>=this.top&&a.y<=this.top+this[P]};function Af(a,b,c){ic(b)?Bf(a,c,b):qd(b,oc(Bf,a))}function Bf(a,b,c){a[I][Cf(c)]=b}function Df(a,b){var c=ie(a);if(c[Mb]&&c[Mb].getComputedStyle)if(c=c[Mb].getComputedStyle(a,""))return c[b];return j}function Ef(a,b){return Df(a,b)||(a[Ab]?a[Ab][b]:j)||a[I][b]}function Ff(a,b,c){var d,e=Jd&&(Pd||Qd)&&$d("1.9");if(b instanceof nd){d=b.x;b=b.y}else{d=b;b=c}sa(a[I],Gf(d,e));a[I].top=Gf(b,e)}function Hf(a){var b=a[Fa]();if(W){a=a[ib];b.left-=a[Wb][yb]+a[J][yb];b.top-=a[Wb][Db]+a[J][Db]}return b}
function If(a){if(W)return a.offsetParent;var b=ie(a),c=Ef(a,"position"),d=c=="fixed"||c=="absolute";for(a=a[O];a&&a!=b;a=a[O]){c=Ef(a,"position");d=d&&c=="static"&&a!=b[Wb]&&a!=b[J];if(!d&&(a.scrollWidth>a[Oa]||a.scrollHeight>a[wb]||c=="fixed"||c=="absolute"))return a}return j}
function Jf(a){var b=new yf(0,Infinity,Infinity,0),c=ge(a),d=c.a[J],e=!Kd&&ke(c.a)?c.a[Wb]:c.a[J],f;for(a=a;a=If(a);)if((!W||a[Oa]!=0)&&(!Kd||a[wb]!=0||a!=d)&&(a.scrollWidth!=a[Oa]||a.scrollHeight!=a[wb])&&Ef(a,"overflow")!="visible"){var g=Kf(a),k;k=a;if(Jd&&!$d("1.9")){var o=fa(Df(k,"borderLeftWidth"));if(Lf(k)){var q=k[Wa]-k[Oa]-o-fa(Df(k,"borderRightWidth"));o+=q}k=new nd(o,fa(Df(k,"borderTopWidth")))}else k=new nd(k[yb],k[Db]);g.x+=k.x;g.y+=k.y;b.top=v.max(b.top,g.y);Ba(b,v.min(b[Yb],g.x+a[Oa]));
wa(b,v.min(b[zb],g.y+a[wb]));sa(b,v.max(b[K],g.x));f=f||a!=e}d=e[xb];e=e[Ca];if(Kd){b.left+=d;b.top+=e}else{sa(b,v.max(b[K],d));b.top=v.max(b.top,e)}if(!f||Kd){b.right+=d;b.bottom+=e}c=ne(c.a[Jb]||c.a[Mb]||p);Ba(b,v.min(b[Yb],d+c[D]));wa(b,v.min(b[zb],e+c[P]));return b.top>=0&&b[K]>=0&&b[zb]>b.top&&b[Yb]>b[K]?b:j}
function Kf(a){var b,c=ie(a),d=Ef(a,"position"),e=Jd&&c[pb]&&!a[Fa]&&d=="absolute"&&(b=c[pb](a))&&(b[lb]<0||b[mb]<0),f=new nd(0,0),g;b=c?c[F]==9?c:ie(c):t;g=W&&!He(ge(b))?b[J]:b[Wb];if(a==g)return f;if(a[Fa]){b=Hf(a);a=Ie(ge(c));f.x=b[K]+a.x;f.y=b.top+a.y}else if(c[pb]&&!e){b=c[pb](a);a=c[pb](g);f.x=b[lb]-a[lb];f.y=b[mb]-a[mb]}else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;if(b!=a){f.x+=b[yb]||0;f.y+=b[Db]||0}if(Kd&&Ef(b,"position")=="fixed"){f.x+=c[J][xb];f.y+=c[J][Ca];break}b=b.offsetParent}while(b&&
b!=a);if(Id||Kd&&d=="absolute")f.y-=c[J].offsetTop;for(b=a;(b=If(b))&&b!=c[J]&&b!=g;){f.x-=b[xb];if(!Id||b[N]!="TR")f.y-=b[Ca]}}return f}function Mf(a,b){var c=new nd(0,0),d=ie(a)?ie(a)[Jb]||ie(a)[Mb]:p,e=a;do{var f;if(d==b)f=Kf(e);else{var g=e;f=new nd;if(g[F]==1)if(g[Fa]){var k=Hf(g);f.x=k[K];f.y=k.top}else{k=Ie(ge(g));g=Kf(g);f.x=g.x-k.x;f.y=g.y-k.y}else{f.x=g.clientX;f.y=g.clientY}f=f}f=f;c.x+=f.x;c.y+=f.y}while(d&&d!=b&&(e=d.frameElement)&&(d=d.parent));return c}
function Gf(a,b){if(typeof a=="number")a=(b?v[Qa](a):a)+"px";return a}function Nf(a){var b=Id&&!$d("10");if(Ef(a,"display")!="none")return b?new pd(a[Wa]||a[Oa],a[Sb]||a[wb]):new pd(a[Wa],a[Sb]);var c=a[I],d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";ya(c,"inline");if(b){b=a[Wa]||a[Oa];a=a[Sb]||a[wb]}else{b=a[Wa];a=a[Sb]}ya(c,d);c.position=f;c.visibility=e;return new pd(b,a)}function Of(a){var b=Kf(a);a=Nf(a);return new zf(b.x,b.y,a[D],a[P])}var Pf={};
function Cf(a){return Pf[a]||(Pf[a]=n(a)[E](/\-([a-z])/g,function(b,c){return c.toUpperCase()}))}function X(a,b){ya(a[I],b?"":"none")}function Qf(a,b){var c=ge(b),d=j;if(W){d=c.a.createStyleSheet();Rf(d,a)}else{var e=je(c.a,"head",void 0,void 0)[0];if(!e){d=je(c.a,"body",void 0,void 0)[0];e=c.t("head");d[O][bb](e,d)}d=c.t("style");Rf(d,a);c[x](e,d)}return d}function Rf(a,b){if(W)a.cssText=b;else{var c=Kd?"innerText":"innerHTML";a[c]=b}}function Lf(a){return"rtl"==Ef(a,"direction")}
function Sf(a){return new pd(a[Wa],a[Sb])}
function Tf(a,b){var c=ie(a),d=He(ge(c));if(W&&(!d||!$d("8"))){c=a[I];if(d){c.pixelWidth=b[D];c.pixelHeight=b[P]}else{var e=a,f="padding";if(W){d=Uf(e,f+"Left");var g=Uf(e,f+"Right"),k=Uf(e,f+"Top");e=Uf(e,f+"Bottom");d=new yf(k,g,e,d)}else{d=Df(e,f+"Left");g=Df(e,f+"Right");k=Df(e,f+"Top");e=Df(e,f+"Bottom");d=new yf(fa(k),fa(g),fa(e),fa(d))}f=a;if(W){g=Vf(f,"borderLeft");k=Vf(f,"borderRight");e=Vf(f,"borderTop");f=Vf(f,"borderBottom");g=new yf(e,k,f,g)}else{g=Df(f,"borderLeftWidth");k=Df(f,"borderRightWidth");
e=Df(f,"borderTopWidth");f=Df(f,"borderBottomWidth");g=new yf(fa(e),fa(k),fa(f),fa(g))}c.pixelWidth=b[D]+g[K]+d[K]+d[Yb]+g[Yb];c.pixelHeight=b[P]+g.top+d.top+d[zb]+g[zb]}}else{c=b;d="content-box";g=a[I];if(Jd)g.MozBoxSizing=d;else if(Kd)g.WebkitBoxSizing=d;else if(Id&&!$d("9.50"))d?g.setProperty("box-sizing",d):g.removeProperty("box-sizing");else g.qe=d;na(g,c[D]+"px");Aa(g,c[P]+"px")}}
function Wf(a,b,c,d){if(/^\d+px?$/[Ha](b))return ea(b,10);else{var e=a[I][c],f=a.runtimeStyle[c];a.runtimeStyle[c]=a[Ab][c];a[I][c]=b;b=a[I][d];a[I][c]=e;a.runtimeStyle[c]=f;return b}}function Uf(a,b){return Wf(a,a[Ab]?a[Ab][b]:j,"left","pixelLeft")}var Xf={thin:2,medium:4,thick:6};function Vf(a,b){if((a[Ab]?a[Ab][b+"Style"]:j)=="none")return 0;var c=a[Ab]?a[Ab][b+"Width"]:j;if(c in Xf)return Xf[c];return Wf(a,c,"left","pixelLeft")};function Yf(a){this.c=a}V(Yf,Oc);var Zf=new Ne(0,100);function Y(a,b,c,d,e,f){if(gc(c))for(var g=0;g<c[A];g++)Y(a,b,c[g],d,e,f);else{c=of(b,c,d||a,e||l,f||a.c||a);b=a;c=c;if(b.a)b.a[c]=i;else if(b.b){b.a=Oe(Zf);b.a[b.b]=i;b.b=j;b.a[c]=i}else b.b=c}return a}
function $f(a,b,c,d,e,f){if(a.b||a.a)if(gc(c))for(var g=0;g<c[A];g++)$f(a,b,c[g],d,e,f);else{a:{d=d||a;f=f||a.c||a;e=!!(e||l);if(b=rf(b,c,e))for(c=0;c<b[A];c++)if(b[c].Va==d&&b[c].hb==e&&b[c].Bb==f){b=b[c];break a}b=j}if(b){b=b.ga;sf(b);if(a.a)ud(a.a,b);else if(a.b==b)a.b=j}}return a}function ag(a){if(a.a){for(var b in a.a){sf(b);delete a.a[b]}Pe(Zf,a.a);a.a=j}else a.b&&sf(a.b)}Yf[B].r=function(){Yf.s.r[L](this);ag(this)};Yf[B].handleEvent=function(){h(ba("EventHandler.handleEvent not implemented"))};function bg(){}V(bg,Oc);Q=bg[B];Q.vc=i;Q.Hb=j;Q.lc=Zb("Hb");Q.addEventListener=function(a,b,c,d){of(this,a,b,c,d)};Q.removeEventListener=function(a,b,c,d){qf(this,a,b,c,d)};
Q.dispatchEvent=function(a){a=a;if(ic(a))a=new Ke(a,this);else if(a instanceof Ke)ta(a,a[kb]||this);else{var b=a;a=new Ke(a[Gb],this);wd(a,b)}b=1;var c,d=a[Gb],e=kf;if(d in e){e=e[d];d=i in e;var f;if(d){c=[];for(f=this;f;f=f.Hb)c[y](f);f=e[i];f.ca=f.o;for(var g=c[A]-1;!a.a&&g>=0&&f.ca;g--){ra(a,c[g]);b&=vf(f,c[g],a[Gb],i,a)&&a.b!=l}}if(f=l in e){f=e[l];f.ca=f.o;if(d)for(g=0;!a.a&&g<c[A]&&f.ca;g++){ra(a,c[g]);b&=vf(f,c[g],a[Gb],l,a)&&a.b!=l}else for(c=this;!a.a&&c&&f.ca;c=c.Hb){ra(a,c);b&=vf(f,c,
a[Gb],l,a)&&a.b!=l}}a=ca(b)}else a=i;return a};Q.r=function(){bg.s.r[L](this);uf(this);this.Hb=j};function cg(){}ec(cg);cg[B].a=0;cg.Dc();function dg(a){this.b=a||ge();this.Wd=eg}V(dg,bg);dg[B].N=cg.Dc();var eg=j;Q=dg[B];Q.R=j;Q.Ca=l;Q.h=j;Q.Wd=j;Q.Md=j;Q.Pa=j;Q.sa=j;Q.wb=j;Q.he=l;Q.n=$b("h");Q.lc=function(a){if(this.Pa&&this.Pa!=a)h(ba("Method not supported"));dg.s.lc[L](this,a)};Q.t=function(){this.h=this.b[rb]("div")};Q.ma=function(a){fg(this,a)};function fg(a,b,c){if(a.Ca)h(ba("Component already rendered"));a.h||a.t();b?b[bb](a.h,c||j):a.b.a[J][x](a.h);if(!a.Pa||a.Pa.Ca)a.Y()}
Q.Y=function(){this.Ca=i;gg(this,function(a){!a.Ca&&a.n()&&a.Y()})};Q.M=function(){gg(this,function(a){a.Ca&&a.M()});this.D&&ag(this.D);this.Ca=l};Q.r=function(){dg.s.r[L](this);this.Ca&&this.M();if(this.D){this.D.p();delete this.D}gg(this,function(a){a.p()});!this.he&&this.h&&xe(this.h);this.Pa=this.Md=this.h=this.wb=this.sa=j};function Z(a,b){return(a.R||(a.R=":"+(a.N.a++)[z](36)))+"."+b}function gg(a,b,c){a.sa&&fd(a.sa,b,c)}
Q.removeChild=function(a,b){if(a){var c=ic(a)?a:a.R||(a.R=":"+(a.N.a++)[z](36)),d;if(this.wb&&c){d=this.wb;d=c in d?d[c]:void 0;d=d||j}else d=j;a=d;if(c&&a){ud(this.wb,c);hd(this.sa,a);if(b){a.M();a.h&&xe(a.h)}c=a;if(c==j)h(ba("Unable to set parent component"));c.Pa=j;dg.s.lc[L](c,j)}}if(!a)h(ba("Child is not in parent component"));return a};Q.hc=function(a){for(;this.sa&&this.sa[A]!=0;)this[jb](this.sa?this.sa[0]||j:j,a)};function hg(a,b,c,d,e,f,g,k){var o,q=c.offsetParent;if(q){var w=q[N]=="HTML"||q[N]=="BODY";if(!w||Ef(q,"position")!="static"){o=Kf(q);w||(o=od(o,new nd(q[xb],q[Ca])))}}w=a;q=Of(w);var s=Jf(w);if(s){w=q;var u=new zf(s[K],s.top,s[Yb]-s[K],s[zb]-s.top);s=v.max(w[K],u[K]);var U=v.min(w[K]+w[D],u[K]+u[D]);if(s<=U){var S=v.max(w.top,u.top);u=v.min(w.top+w[P],u.top+u[P]);if(S<=u){sa(w,s);w.top=S;na(w,U-s);Aa(w,u-S)}}}w=q=q;s=ge(a);S=ge(c);if(s.a!=S.a){U=s.a[J];S=Mf(U,S.a[Jb]||S.a[Mb]);S=od(S,Kf(U));if(W&&
!He(s))S=od(S,Ie(s));w.left+=S.x;w.top+=S.y}a=(b&4&&Lf(a)?b^2:b)&-5;b=new nd(a&2?q[K]+q[D]:q[K],a&1?q.top+q[P]:q.top);if(o)b=od(b,o);if(e){b.x+=(a&2?-1:1)*e.x;b.y+=(a&1?-1:1)*e.y}var C;if(g)if((C=Jf(c))&&o){C.top=v.max(0,C.top-o.y);C.right-=o.x;C.bottom-=o.y;sa(C,v.max(0,C[K]-o.x))}var sd;a:{e=b;c=c;a=d;d=f;C=C;f=g;k=k;e=e.Q();o=0;a=(a&4&&Lf(c)?a^2:a)&-5;g=Nf(c);k=k?k.Q():g;if(d||a!=0){if(a&2)e.x-=k[D]+(d?d[Yb]:0);else if(d)e.x+=d[K];if(a&1)e.y-=k[P]+(d?d[zb]:0);else if(d)e.y+=d.top}if(f){if(C){d=
e;o=k;C=C;f=f;a=0;if(d.x<C[K]&&f&1){d.x=C[K];a|=1}if(d.x<C[K]&&d.x+o[D]>C[Yb]&&f&16){o.width-=d.x+o[D]-C[Yb];a|=4}if(d.x+o[D]>C[Yb]&&f&1){d.x=v.max(C[Yb]-o[D],C[K]);a|=1}if(f&2)a|=(d.x<C[K]?16:0)|(d.x+o[D]>C[Yb]?32:0);if(d.y<C.top&&f&4){d.y=C.top;a|=2}if(d.y>=C.top&&d.y+o[P]>C[zb]&&f&32){o.height-=d.y+o[P]-C[zb];a|=8}if(d.y+o[P]>C[zb]&&f&4){d.y=v.max(C[zb]-o[P],C.top);a|=2}if(f&8)a|=(d.y<C.top?64:0)|(d.y+o[P]>C[zb]?128:0);C=a}else C=256;o=C;if(o&496){sd=o;break a}}Ff(c,e);g=g==k?i:!g||!k?l:g[D]==
k[D]&&g[P]==k[P];if(!g){g=c;k=k;if(k instanceof pd){sd=k[P];k=k[D]}else h(ba("missing height argument"));na(g[I],Gf(k,i));Aa(g[I],Gf(sd,i))}sd=o}return sd};var ig="A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff",jg="\u0591-\u07ff\ufb1d-\ufdff\ufe70-\ufefc";ia("["+jg+"]");ia("["+ig+"]");ia("^["+ig+"]");ia("^["+jg+"]");ia("^[^"+jg+"]*["+ig+"]");ia("^[^"+ig+"]*["+jg+"]");ia("["+ig+"][^"+jg+"]*$");ia("["+jg+"][^"+ig+"]*$");var kg=ia("^(ar|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)");function lg(a){this.a=Ue?[]:"";a!=j&&this.H[Hb](this,arguments)}lg[B].da=function(a){this.clear();this.H(a)};if(Ue){lg[B].b=0;lg[B].H=function(a,b){if(b==j)this.a[this.b++]=a;else{this.a[y][Hb](this.a,arguments);this.b=this.a[A]}return this}}else lg[B].H=function(a,b){this.a+=a;if(b!=j)for(var c=1;c<arguments[A];c++)this.a+=arguments[c];return this};lg[B].clear=function(){if(Ue){la(this.a,0);this.b=0}else this.a=""};ka(lg[B],function(){if(Ue){var a=this.a[Tb]("");this.clear();a&&this.H(a);return a}else return this.a});var mg=lg;function ng(a,b){var c=b||new mg;c.H('<head><meta http-equiv="Content-Type" content="text/html; charset=UTF8"><link rel="stylesheet" type="text/css" href="',a.A,'"></head><body scroll="no" style="margin:0px;overflow:hidden" dir="',a.dir,'" marginHeight=0 marginWidth=0 leftMargin=0 topMargin=0 border=0><div id="',a.id,'" class="goog-te-menu"></div></body>');if(!b)return c[z]()}
function og(a,b){var c=b||new mg;c.H('<head><meta http-equiv="Content-Type" content="text/html; charset=UTF8"><link rel="stylesheet" type="text/css" href="',a.A,'"></head><body class="goog-te-banner" scroll="no" border=0 dir="',a.dir,'"><table border=0 cellspacing=0 cellpadding=0 width=100% height=100%><tr valign=middle><td width=1 nowrap><a href="',a.fc,'" class="goog-logo-link" target="_blank"><img src="',a.Da,'" alt="Google ',"Google \u7ffb\u8bd1",'"></a></td>',a.Ga?'<td width=1><img src="'+a.ya+
'" width="9" height="15" title="'+a.Ga+'" alt="'+a.Ga+'" style="background-image:url('+a.Ra+');background-position:-56px 0px;margin:0 4px"></td>':"",'<td class="goog-te-banner-margin"></td><td><table border=0 cellspacing=0 cellpadding=0 height=100%><tr id="',a.Td,'" style="display:none" valign=middle><td nowrap><span class="goog-te-banner-content">',a.Sd,'</span></td><td class="goog-te-banner-margin"></td><td nowrap><div class="goog-te-button"><div><button id="',a.ad,'"><b>',"\u7ffb\u8bd1",'</b></button></div></div></td><td class="goog-te-banner-margin"></td><td nowrap><div class="goog-te-button"><div><button id="',
a.Nd,'"></button></div></div></td></tr><tr id="',a.Rd,'" style="display:none" valign=middle><td><span class="goog-te-banner-content">',"\u6b63\u5728\u7ffb\u8bd1",'&nbsp;<span dir="ltr">(<b id="',a.Qd,'"></b>%)</span>&nbsp;<img src="',a.Ld,'"></span></td><td class="goog-te-banner-margin"></td><td nowrap><div class="goog-te-button"><div><button id="',a.Zc,'">',"\u53d6\u6d88",'</button></div></div></td></tr><tr id="',a.gd,'" style="display:none"><td><span class="goog-te-banner-content">',a.fd,'</span></td><td class="goog-te-banner-margin"></td><td nowrap><div class="goog-te-button"><div><button id="',
a.Ud,'">',"\u663e\u793a\u539f\u6587",'</button></div></div></td></tr><tr id="',a.ed,'" style="display:none" valign=middle><td><span id="',a.dd,'" class="goog-te-banner-content"></span></td></tr></table></td><td width=1><a href="',a.Kd,'" target="_blank" style="white-space:nowrap">',"\u4e86\u89e3\u8be6\u60c5",'</a></td><td width=1><a id="',a.$c,'" class="goog-close-link" href="javascript:void(0)" title="',"\u53d6\u6d88",'"><img src="',a.ya,'" width="15" height="15" alt="',"\u53d6\u6d88",'" style="background-image:url(',
a.Ra,');background-position:-28px 0px"></a></td></tr></table></body>');if(!b)return c[z]()}function pg(a,b){var c=b||new mg;c.H('<span id="',a.id,'"></span>');if(!b)return c[z]()}function qg(a,b){var c=b||new mg;c.H(a.Pc,'<div id="',a.id,'"></div>',a.Oc);if(!b)return c[z]()}
function rg(a,b){var c=b||new mg;c.H('<head><meta http-equiv="Content-Type" content="text/html; charset=UTF8"><link rel="stylesheet" type="text/css" href="',a.A,'"></head><body class="goog-te-ftab ',a.xb,'" scroll="no" style="overflow:hidden" dir="',a.dir,'"><a id="',a.ge,'" href="javascript:void(0)" class="goog-te-ftab-link"><img src="',a.ya,'" style="background-image:url(',a.Ra,');background-position:-65px 0px"><span>',"\u7ffb\u8bd1","</span></a></body>");if(!b)return c[z]()}
function sg(a,b){var c=b||new mg;c.H(".",a[Ja]," {z-index:9999999; overflow:visible; position:fixed; _position:absolute;",a.top||a.top==0?"top:"+a.top+"px; _top:expression(("+a.top+"+(hack1=document.documentElement.scrollTop||document.body.scrollTop))+'px');":"top:auto;",a[K]||a[K]==0?"left:"+a[K]+"px; _left:expression(("+a[K]+"+(hack2=document.documentElement.scrollLeft||document.body.scrollLeft))+'px');":"left:auto;",a[zb]||a[zb]==0?"bottom:"+a[zb]+"px; _top:expression((-"+a[zb]+"-document.getElementById('"+
a.id+"').offsetHeight+(hack3=document.documentElement.clientHeight||document.body.clientHeight)+(hack4=document.documentElement.scrollTop||document.body.scrollTop))+'px');":"bottom:auto;",a[Yb]||a[Yb]==0?"right:"+a[Yb]+"px; _left:expression((-"+a[Yb]+"-document.getElementById('"+a.id+"').offsetWidth+(hack5=document.documentElement.clientWidth||document.body.clientWidth)+(hack6=document.documentElement.scrollLeft||document.body.scrollLeft))+'px');":"right:auto;","}");if(!b)return c[z]()}
function tg(a,b){var c=b||new mg;c.H('<head><meta http-equiv="Content-Type" content="text/html; charset=UTF8"><link rel="stylesheet" type="text/css" href="',a.A,'"></head><body scroll="no" style="margin:0px;overflow:hidden" dir="',a.dir,'" marginHeight=0 marginWidth=0 leftMargin=0 topMargin=0 border=0><div id="content" class="goog-te-balloon"><table border=0 cellspacing=0 cellpadding=0 width=100%><tr valign=middle><td nowrap><b>',"\u539f\u6587\uff1a",'</b></td><td id="logo" width=1 nowrap>',a.cc?
"<span style=\"display:inline-block;vertical-align:middle;height:15px; width:51px;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader( src='"+a.Da+"',sizingMethod='scale');\"></span>":'<img src="'+a.Da+'">','</td><td width=8></td><td width=1 nowrap><a id="close" href="javascript:void(0)" title="',"\u53d6\u6d88",'"><img src="',a.ya,'" width="15" height="15" style="background-image:url(',a.Ra,');background-position:-28px 0px"></a></td></tr></table><div id="original" class="goog-te-balloon-text"></div><div id="zippy" class="goog-te-balloon-zippy" style="display:none"><img id="zippy_img" class="plus" width="12" height="12" src="',
a.ya,'"><span>',"\u63d0\u4f9b\u66f4\u597d\u7684\u7ffb\u8bd1\u5efa\u8bae",'</span></div><div id="feedback" style="display:none"><iframe name="feedback-frame" frameBorder=0 style="width:100%;display:none"></iframe></div><div class="goog-te-balloon-form" style="display:none"><form id="suggestForm" target="feedback-frame" method="post"><input type="hidden" name="gtrans"><input type="hidden" name="hl"><input type="hidden" name="text"><input type="hidden" name="langpair"><input type="hidden" name="oe" value="UTF-8">');
for(var d=a.aa,e=d[A],f=0;f<e;f++){var g=d[f];c.H('<input type="hidden" name="',g,'" />')}c.H('<textarea rows="3" name="utrans"></textarea><div style="text-align:',a.dir=="rtl"?"left":"right",'"><input type="submit" value="',"\u63d0\u4f9b\u5efa\u8bae",'"></div></form></div><div id="forward" class="goog-te-balloon-footer" style="display:none"><a id="forward_link" href="javascript:void(0)">',"\u63d0\u4f9b\u66f4\u597d\u7684\u7ffb\u8bd1\u5efa\u8bae","</a></div></div></body>");if(!b)return c[z]()};function ug(a){for(var b={},c=0;c<a[A];++c)b[a[c]]=i;return b}function vg(a,b,c){this.c=[];this.f=a||0;if(b||!c)this.d=b||1;else this.j=c;this.a=0;this.b=i}vg[B].add=function(a){this.c[y](a)};vg[B].go=function(){if(this.b){this.b=l;p[Ta](T(this.g,this),this.f)}};oa(vg[B],function(){this.b=i});
vg[B].g=function(){if(!this.b){if(this.d)for(var a=0;a<this.d;++a)if(this.c[this.a]){this.c[this.a][L]();this.a++}else{this.b=i;return}else for(a=(new Date).getTime();(new Date).getTime()-a<this.j;)if(this.c[this.a]){this.c[this.a][L]();this.a++}else{this.b=i;return}p[Ta](T(this.g,this),this.f)}};function wg(a){this.ib=a?[a]:[];this.Ea=[0];this.za=l}function xg(a,b){if(a.za)return b;a.Ea[y](0);var c=a.Ea[A]-1;return T(function(){this.Ea[c]++;b&&b[Hb](j,arguments);yg(this)},a)}
function zg(a,b){if(a.za)return b;return T(function(){if(this.za)b[Hb](j,arguments);else{var c=arguments;this.ib[y](function(){b[Hb](j,c)})}},a)}wg[B].pa=function(){this.Ea[0]=1;yg(this)};function yg(a){for(var b=0;b<a.Ea[A];++b)if(a.Ea[b]==0)return;a.za=i;for(b=0;b<a.ib[A];++b){var c=a.ib[b];a.ib[b]=j;c[L]()}a.ib=[];a.Ea=[]}function Ag(a){this.Tc=a;this.qa=this.Nb=l}function Bg(a,b){return T(function(){b&&b[Hb](j,arguments);if(this.qa){if(!this.Nb){this.Tc[L]();this.Nb=i}}else this.Nb=i},a)}
Ag[B].pa=function(){if(!this.qa){this.qa=i;this.Nb&&this.Tc[L]()}};function Cg(a,b,c,d){this.Ka=b;this.d=a;this.f=c||0;this.o=d||0;this.a=this.qa=l}Cg[B].go=function(){this.qa||this.c()};Cg[B].c=function(){if(this.qa=(this.a=!!this.d[L]())||--this.o<=0){this.Ka[L](j,this.a);this.b=0}else this.b=p[Ta](T(this.c,this),this.f)};oa(Cg[B],function(){this.b&&p[La](this.b);this.qa=i;this.Ka[L](j,this.a)});
function Dg(a){var b="";if(a)if(a[F]==3)b=n(a[Vb]);else if(a[F]==1&&(a[N]=="INPUT"||a[N]=="TEXTAREA"))b=a[Za];else if(a[M]&&!a[M][Qb]&&a[M][F]==3)b=n(a[M][Vb]);return b}function Eg(a,b){if(a)if(a[F]==3)a.nodeValue=b;else if(a[F]==1)if(a[N]=="INPUT"||a[N]=="TEXTAREA")qa(a,b);else Be(a,b)}function Fg(a,b){return function(){a[H](b)}}
function Gg(a){a=Pc(a).toLowerCase()[E]("_","-");if(a=="zh-cn")return"zh-CN";else if(a=="zh-tw")return"zh-TW";var b=a[G]("-");a=b>=0?a[Cb](0,b):a;if(a=="zh")return"zh-CN";return a}function Hg(a){var b=[];for(var c in a)if(a[c]!==r[B][c]){var d=Tc(c);if(fc(a[c])=="array")for(var e=0;e<a[c][A];++e)b[y](d+"="+Tc(a[c][e]));else b[y](d+"="+Tc(a[c]))}return b[Tb]("&")}function Ig(a,b){var c=b||{};c.nca=a;c.client=Ac;var d=new Image;d.src="//"+Jc+"/gen204?"+Hg(c);d.onload=function(){d.onload=j}}
function Jg(a,b){if((W||Id)&&p[$a].hostname!=t.domain){Kg=Kg?Kg+1:1;var c="f"+Kg+"_"+pc()[z](36);p[c]=function(){p[c]=m;a.src="javascript:void(0)";b&&p[Ta](function(){b()},0)};a.src="javascript:void(document.write(\"<script>document.domain='"+t.domain+"';parent['"+c+"']();<\/script>\"))"}else b&&b()}var Kg;function Lg(){var a={};try{for(var b in r[B]){var c=r[B][b];delete r[B][b];a[b]=c}}catch(d){return{}}return a}function Mg(a){for(var b in a)r[B][b]=a[b]};function Ng(a,b){dg[L](this,b);this.e=a||{};this.e.A||(this.e.A=Ic);this.e.Z=this.e.Z;this.e.Fa=!!this.e.Fa;this.e.aa=this.e.aa||[];this.d=new Yf(this);this.j=new wg}V(Ng,dg);Q=Ng[B];
Q.t=function(){this.h=this.b[rb]("div");this.h[I].position="absolute";this.h[I].zIndex=1073741824;this.h[I].top="-9999em";this.f=l;var a={id:Z(this,"container")},b=this.h;a=a;var c=new mg;c.H('<iframe id="',a.id,'" class="goog-te-balloon-frame skiptranslate" frameBorder=0 src="javascript:\'\'" style="visibility:visible"></iframe>');a=c[z]();pa(b,a)};
Q.Y=function(){Ng.s.Y[L](this);var a={A:this.e.A,dir:kg[Ha](rc)?"rtl":"ltr",Da:Hc,cc:W&&!$d("7.0"),ya:Lc,Ra:Dc,aa:this.e.aa};this.h.id=Z(this,"balloonContainer");this.z=this.b.n(Z(this,"container"));Y(this.d,this.z,"load",this.be);Jg(this.z,T(function(){var b=Ae(this.z);b[hb](tg(a));b[eb]()},this))};
Q.be=function(){X(this.h,i);var a=new he(Ae(this.z));this.a=a;this.k=a.n("content");this.m=a.n("original");var b=W?this.z:this.z[Rb]||Ae(this.z)[Jb]||Ae(this.z)[Mb];Y(this.d,b,"mouseout",this.Ed);Y(this.d,b,"mouseover",this.Fd);Y(this.d,a.n("close"),"click",Fg(this,"close"));if(W)na(this.k[I],"100%");this.e.Fa||X(a.n("logo"),l);this.g=200;if(this.e.Z!=0){this.c=a.n("suggestForm");this.c.action=Nc;Y(this.d,this.c,"submit",this.ud);if(this.e.Z==1){this.l=a.n("zippy_img");this.B=a.n("feedback");a=a.n("zippy");
Y(this.d,a,"click",this.Gc);X(a,i);for(a=a[M];a;a=a[Qb])this.g+=a[Wa]}else if(this.e.Z==2){ta(this.c,"_blank");X(a.n("forward"),i);Y(this.d,a.n("forward_link"),"click",T(this.c.submit,this.c))}}X(this.h,l);this[H]("load");this.j.pa()};Q.M=function(){Ng.s.M[L](this);this.d.p();this.a=this.d=j;xe(this.z);this.B=this.l=this.c=this.m=this.k=this.z=j};Q.Gc=function(){if(this.l[Ja]=="plus"){ma(this.l,"minus");X(this.c[O],i);this[H]("open_form")}else{ma(this.l,"plus");X(this.c[O],l);this[H]("close_form")}Og(this)};
Q.Ed=function(){this[H]("mouseout")};Q.Fd=function(){this[H]("mouseover")};Q.ud=function(){this.e.Z==1&&this.Gc()};Q.kc=function(a,b,c,d,e){if(this.j.za){Be(this.m,Pc(a||""));if(this.c){qa(this.c.gtrans,b||"");qa(this.c.hl,rc);qa(this.c[Na],a||"");qa(this.c.langpair,c+"|"+d);qa(this.c.utrans,Pc(b||""));for(a=0;a<this.e.aa[A];++a){b=this.e.aa[a];qa(this.c[b],e&&e[b]||"")}}}else zg(this.j,T(this.kc,this,a,b,c,d,e))[L]()};
function Og(a){var b=Sf(a.k);if(b[D]<a.g)na(b,a.g);if(b[P]<=0)Aa(b,a.g);Tf(a.z,b);Tf(a.h,b)}Q.reset=function(a){if(this.j.za){this.h[I].top="-9999em";X(this.h,i);var b=this.a[rb]("span");this.m[M]&&b[x](this.m[M].cloneNode(i));b[I].whiteSpace="nowrap";this.k[x](b);var c=b[Wa]+20;this.k[jb](b);b=this.b.a[J][Wa]/2;if(a&&c>a)c=a;if(c>b)c=b;if(c<this.g)c=this.g;na(this.z[I],c+"px");Og(this);if(this.e.Z==1){ma(this.l,"plus");X(this.c[O],l);X(this.B,l)}}else zg(this.j,T(this[Lb],this,a))[L]()};Q.fa=$b("f");
Q.P=function(a,b,c){if(this.j.za){if(a){if(b){var d=0,e=0,f=0;if(c&&c[A]){for(var g=NaN,k=NaN,o=NaN,q=NaN,w=0;w<c[A];++w){var s=Of(c[w]);if(s[D]&&s[P]){g<s[K]||(g=s[K]);k>s[K]+s[D]||(k=s[K]+s[D]);o<s.top||(o=s.top);q>s.top+s[P]||(q=s.top+s[P])}}this[Lb](k-g);if(g&&o&&q){s=Of(b);d=g-s[K];e=o-s.top;f=s.top+s[P]-q}}else this[Lb]();c=hg(b,4,this.h,5,new nd(d||0,-4+(e||0)),m,9);if(c&496)hg(b,5,this.h,4,new nd(d||0,-4+(f||0)),m,5)}}else{this[Lb]();X(this.h,a)}this.f=a}else zg(this.j,T(this.P,this,a,b,c))[L]()};function Pg(a,b){this.e=a||{};this.e.Z=a.Z;this.e.Fa=!!a.Fa;this.e.wc=ea(a.wc,10)||300;this.e.aa=a.aa;this.j=0;this.d={};this.c=l;this.b=new Yf(this);this.f=j;this.k={};this.a=new Ng({A:Ic,Z:this.e.Z,Fa:this.e.Fa,aa:this.e.aa},b);this.a.ma(Ge(b||ge())[J]);Y(this.b,this.a,"open_form",this.md);Y(this.b,this.a,"close_form",this.kd);Y(this.b,this.a,"mouseout",this.Ec);Y(this.b,this.a,"mouseover",this.nd);Y(this.b,this.a,"close",this.ld);this.g=""}V(Pg,Oc);
function Qg(a,b,c,d,e,f){a.d[++a.j]={text:c,fe:d,Yd:e||a.l,ee:f||a.m,la:b};for(c=0;c<b[A];++c)if(b[c]){Y(a.b,b[c],"mouseout",a.Ec);Y(a.b,b[c],"mouseover",T(a.Bd,a,a.j,b[c]))}return a.j[z]()}function Rg(a,b){var c=a.d[b];if(c){for(var d=0;d<c.la[A];++d)if(c.la[d]){$f(a.b,c.la[d],"mouseout");$f(a.b,c.la[d],"mouseover")}delete a.d[b]}}Q=Pg[B];Q.r=function(){Sg(this);for(var a in this.d)Rg(this,a);this.b.p();this.b=j;this.a.p();this.a=j};function Tg(a){if(a.f){p[La](a.f);a.f=j}}
function Ug(a,b){Tg(a);a.f=p[Ta](T(function(c){c[L](this);this.f=j},a,b),a.e.wc)}Q.md=function(){this.c=i};Q.kd=function(){Tg(this);this.c=l};function Vg(a,b,c){if(a=a.d[b]){c=c||typeof c=="undefined";for(b=0;b<a.la[A];++b)if(a.la[b]){Af(a.la[b],"backgroundColor",c?"#E6ECF9":"");Af(a.la[b],"color",c?"#000":"")}}}Q.Ec=function(){this.c||Ug(this,function(){Vg(this,this.g,l);this.a.P(l);this.c=l})};Q.nd=function(){this.c||Tg(this)};function Sg(a){a.c=i;Tg(a);Vg(a,a.g,l);a.a.P(l);a.c=l}Q.ld=function(){Sg(this)};
Q.Bd=function(a,b){this.c||Ug(this,function(){Vg(this,this.g,l);this.g=a;Vg(this,a);var c=this.d[a];this.e.Z!=0?this.a.kc(c[Na],c.fe,c.Yd,c.ee,this.k):this.a.kc(c[Na]);this.a.P(i,b,c.la);this.c=l})};function Wg(a,b,c,d,e,f){this.a=a;this.ja=b;this.B=d;this.l=c;this.g=e;this.j=ja(this.a[A]);this.b=ja(this.a[A]);this.c=[];this.d=[];this.f=this.k=l;this.m=f||"transparent"}V(Wg,Oc);
function Xg(a,b,c,d){a.k=i;a.c=[];a.c.cd=d;if(!d){d=t[rb]("div");X(d,l);pa(d,b[G]("<i>")>=0?b:"<b>"+b+"</b>");t[J][x](d);b=j;for(var e=d[M];e;e=e[Qb])if(e[N]=="I")a.c[y](b={Mc:Ee(e),$:[]});else if(e[N]=="B"){b||a.c[y](b={Mc:"",$:[]});if(a.a[A]==1)b.$[y]({index:0,text:$c(Ee(e))});else{for(var f={},g=-1,k=function(s,u,U){f[s]||(f[s]="");if(U)f[s]=u+f[s];else f[s]+=u},o=e[M];o;o=o[Qb])if(o.attributes&&o.attributes.i){g=ea(o.attributes.i[Vb],10);g!=NaN&&k(g,Ee(o))}else if(o[F]==3)if(Pc(o[Vb])==""){var q=
a.a[g],w=a.a[g+1];q&&(q[Da]||q[Qb])||!(w&&(w[Da]||w[Qb]))?k(g,o[Vb]):k(g+1,o[Vb],i)}else k(g,o[Vb]);for(g in f)f[g]!==r[B][g]&&g>=0&&g<a.a[A]&&b.$[y]({index:g,text:$c(f[g])});if(f[-1])if(b.$[A]==0&&f[-1])b.$[y]({index:0,text:$c(f[-1])});else b.$[0].text=$c(f[-1])+b.$[0][Na];f=j}b=j}d[O][jb](d)}c&&(c[a.ja]=a.c);Yg(a)}function Zg(a){for(var b=0;b<a.a[A];++b)try{if(!a.a[b]||!a.a[b][O]){a.a[b]=j;a.b[b]=j}}catch(c){a.a[b]=j;a.b[b]=j}}
xa(Wg[B],function(){if(this.f){this.f=l;if(this.d[A]>0){for(var a=0;a<this.d[A];++a)Rg(this.g,this.d[a]);this.d=[]}Zg(this);for(a=0;a<this.a[A];++a)if(this.j[a]&&this.a[a]){Eg(this.a[a],this.l[a]);if(this.b[a]){var b=this.b[a];this.a[a]=b[M];b=b;var c=void 0,d=b[O];if(d&&d[F]!=11)if(b.removeNode)b.removeNode(l);else{for(;c=b[M];)d[bb](c,b);xe(b)}this.b[a]=j}this.j[a]=l}}});
function Yg(a,b){function c(u,U){u.background=U;u.border="0";u.fontSize="100%";u.margin="0";u.outline="0";u.padding="0";u.verticalAlign="baseline";ya(u,"inline")}if(b&&b[a.ja]){a.c=b[a.ja];a.k=i}if(!(!a.k||a.f||a.c.cd)){a.f=i;Zg(a);for(var d=0;d<a.a[A];++d)if(!a.j[d]&&a.a[d]){var e=a.a[d];if(e[O]&&(e[O][N]=="OPTION"||e[O][N]=="TITLE")||e[N]=="INPUT"||e[N]=="TEXTAREA"){Eg(a.a[d],"");a.b[d]=j}else{var f=e[ib]?e[ib][rb]("font"):t[rb]("font");c(f[I],a.m);ye(f,e);a.b[d]=f;a.a[d]=f}a.j[d]=i}for(d=0;d<a.c[A];++d){var g=
a.c[d],k=g.Mc;if(!k){for(var o=[],q=0;q<g.$[A];++q)o[y](a.l[g.$[q][Ma]]);k=o[Tb](" ")}var w=[];o=[];for(q=0;q<g.$[A];++q){o[y](g.$[q][Na]);var s=g.$[q];if(e=a.b[s[Ma]]){f=e[ib]?e[ib][rb]("font"):t[rb]("font");w[y](f);c(f[I],a.m);a.g||(f.title=k);Eg(f,s[Na]);e[x](f);d!=0&&e[M]!=f&&we(f[ib]?f[ib][Ya](" "):t[Ya](" "),f)}else a.a[s[Ma]]&&Eg(a.a[s[Ma]],Dg(a.a[s[Ma]])+s[Na])}a.g&&a.d[y](Qg(a.g,w,k,o[Tb]("")))}for(d=0;d<a.a[A];++d){e=a.b[d];g=a.l[d];f=g[Cb](0,g[A]-Qc(g)[A]);g=g[Cb](Rc(g)[A]);if(f==" ")f=
"";if(g==" ")g="";if(e){if(f){for(k=e[M];k;k=k[Qb]){o=Qc(Dg(k));Eg(k,o);if(o)break}(k=e[M])?Eg(k,f+Dg(k)):te(e,e[ib]?e[ib][Ya](f):t[Ya](f))}if(g){for(k=e[nb];k;k=k[Da]){o=Rc(Dg(k));Eg(k,o);if(o)break}(k=e[nb])?Eg(k,Dg(k)+g):te(e,e[ib]?e[ib][Ya](g):t[Ya](g))}}else{e=Dg(a.a[d]);if(f&&g)e=f+Pc(e)+g;else if(f)e=f+Qc(e);else if(g)e=Rc(e)+g;Eg(a.a[d],e)}}}}Wg[B].r=function(){Wg.s.r[L](this);this[Fb]();this.a=j};function $g(a){dg[L](this,a);this.g=new Yf(this)}V($g,dg);Q=$g[B];Q.t=function(){this.h=this.b[rb]("select");ma(this.h,"goog-te-combo")};Q.Y=function(){$g.s.Y[L](this);this.xc()};Q.xc=function(){of(this.h,"change",Fg(this,"chg_lang"));this[H]("load")};function ah(a,b){if(a.h[O]!=b){a.h[O][jb](a.h);b[x](a.h)}}Q.ua=function(a){this.b.hc(this.h);for(var b in a)if(a[b]!==r[B][b]){var c=this.b.t("option",{value:b});this.b.Ib(c,a[b]);this.h[x](c)}this.h.selectedIndex=0};Q.Ab=function(){return this.h[Za]};
Q.va=function(a){if(this.h[Za]!=a)for(var b=0,c;c=this.h.options[ab](b);++b)if(c[Za]==a){this.h.selectedIndex=b;return}};Q.Zb=function(a){if(fc(a)=="undefined")return this.h.options[ab](this.h.selectedIndex)[Na];for(var b=0,c;c=this.h.options[ab](b);++b)if(c[Za]==a)return c[Na]};Q.M=function(){$g.s.M[L](this);this.g.p();this.g=j};Q.bb=function(a){this.h.disabled=!a};function bh(a,b){$g[L](this,b);this.e=a||{};this.e.A||(this.e.A=Ic)}V(bh,$g);Q=bh[B];
Q.t=function(){this.h=this.b[rb]("a");ma(this.h,"goog-te-menu-value");this.h.href="javascript:void(0)";this.K=this.b.t("span");this.h[x](this.K);if(this.e.hd){this.h[x](this.b.t("img",{src:Lc,width:1,height:1}));this.h[x](this.b.t("span",{style:"border-left:1px solid #bbb"},"\u200b"));this.h[x](this.b.t("img",{src:Lc,width:1,height:1}));this.f=this.b.t("span",{style:"color:#9b9b9b"},"\u25bc");this.h[x](this.f);this.l=this.f}else{this.d=this.b.t("img",{src:Lc,style:"background-image:url("+Dc+");background-position:-14px 0px;border:none",
width:14,height:14});this.h[x](this.d);this.l=this.d}this.C=pe("iframe",{frameBorder:0,"class":"goog-te-menu-frame skiptranslate"});this.C[I].visibility="visible";X(this.C,l);t[J][x](this.C)};Q.xc=function(){var a={dir:kg[Ha](rc)?"rtl":"ltr",A:this.e.A,id:Z(this,"menuBody")};Y(this.g,this.C,"load",this.ae);Jg(this.C,T(function(){var b=Ae(this.C);b[hb](ng(a));b[eb]()},this))};
Q.ae=function(){this.a=new he(Ae(this.C));this.j=this.a.n(Z(this,"menuBody"));Y(this.g,this.h,"click",this.sd);W?Y(this.g,this.C,"blur",this.bc):Y(this.g,this.C[Rb]||Ae(this.C)[Jb]||Ae(this.C)[Mb],"blur",this.bc);this[H]("load")};Q.ua=function(){};Q.Ad=function(a){if(this.k!=a[gb][Za]){this.va(a[gb][Za]);this[H]("chg_lang")}this.bc()};Q.sd=function(){this.Kb();(this.C[Rb]||Ae(this.C)[Jb]||Ae(this.C)[Mb]).focus();this.O=i};Q.bc=function(){if(this.O){this.O=l;this.Kb(l)}};
Q.Kb=function(a){if(a==l){this.d&&Af(this.d,"backgroundPosition","-14px 0px");this.f&&Af(this.f,"color","#9b9b9b");X(this.C,l)}else{a=Mf(this.l,p);a.y+=this.l[Sb];a.x+=this.l[Wa]-this.m[D]>>1;if(W&&!$d("7.0")){var b=t[J];a.y-=b.offsetTop;a.x-=b.offsetLeft}else{b=oe(t);a.y-=b.y;a.x-=b.x}b=ne(p);if(a.x>b[D]-this.m[D])a.x=b[D]-this.m[D];if(a.x<0)a.x=0;if(a.y>b[P]-this.m[P])a.y=b[P]-this.m[P];if(a.y<0)a.y=0;Ff(this.C,a);this.d&&Af(this.d,"backgroundPosition","0px 0px");this.f&&Af(this.f,"color","#d5d5d5");
X(this.C,i)}};Q.Ab=$b("k");Q.va=function(a){if(this.k!=a){var b=this.Zb(a);if(b){this.k=a;this.b.Ib(this.K,b)}}};Q.Zb=function(){};Q.M=function(){bh.s.M[L](this);xe(this.C);this.j=this.a=this.C=this.l=this.f=this.d=this.K=j};function ch(a,b){bh[L](this,a,b);this.e=a||{};this.e.A||(this.e.A=Ic)}V(ch,bh);Q=ch[B];
Q.ua=function(a){this.a.hc(this.j);X(this.C,i);this.B=a;this.c=[];for(var b in a)if(a[b]!==r[B][b]){var c={Ua:this.a.t("a",{className:"goog-te-menu2-item-selected",href:"javascript:void(0)",value:b})};this.c[y](c);var d=this.a.t("div",{style:"white-space:nowrap"});this.a[x](c.Ua,d);this.a[x](d,this.a.t("span",{className:"indicator"},"\u203a"));this.a[x](d,this.a.t("span",{className:"text"},a[b]));Y(this.g,c.Ua,"click",this.Ad)}a=this.c[A]-1;a=v[Qa]((a-a%11)/11)+1;this.G=this.a.t("table",{cellspacing:0,
cellpadding:0,border:0});c=this.a.t("tbody");b=this.a.t("tr",{valign:"top"});ma(this.j,"goog-te-menu2");this.a[x](this.j,this.G);this.a[x](this.G,c);this.a[x](c,b);for(d=c=0;c<a;++c){var e=this.a.t("td");this.a[x](b,e);for(var f=0;f<11&&d<this.c[A];++f,++d)this.a[x](e,this.c[d].Ua);if(c!=a-1){e=this.a.t("td",{"class":"goog-te-menu2-colpad"},"\u00a0");this.a[x](b,e)}}this.k=j;this.va(this.c[0].Ua[Za]);dh(this);X(this.C,l)};Q.Zb=function(a){a=fc(a)=="undefined"?this.k:a;return this.B[a]};
Q.va=function(a){if(this.k!=a){ch.s.va[L](this,a);for(var b=0;b<this.c[A];++b){var c=this.c[b];ma(c.Ua,c.Ua[Za]==a?"goog-te-menu2-item-selected":"goog-te-menu2-item")}}};function dh(a){Tf(a.j,Sf(a.G));Tf(a.C,Sf(a.j));a.m=Sf(a.C)}Q.Kb=function(a){ch.s.Kb[L](this,a);a!=l&&dh(this)};Q.M=function(){ch.s.M[L](this);this.G=this.c=j};function eh(a){return a="\u5df2\u7ffb\u8bd1\u4e3a\u4ee5\u4e0b\u8bed\u8a00\uff1a"+a}function fh(a){return a="\u4f7f\u7528\u4ee5\u4e0b\u8bed\u8a00\u67e5\u770b\u6b64\u7f51\u9875\uff1a"+a};var gh="StopIteration"in R?R.StopIteration:ba("StopIteration");function hh(){}hh[B].Ya=function(){h(gh)};hh[B].Xc=function(){return this};function ih(a,b,c,d,e){this.a=!!b;a&&this[Kb](a,d);this.b=e!=m?e:this.S||0;if(this.a)this.b*=-1;this.c=!c}V(ih,hh);Q=ih[B];Q.ha=j;Q.S=0;Q.oc=l;Q.setPosition=function(a,b,c){if(this.ha=a)this.S=typeof b=="number"?b:this.ha[F]!=1?0:this.a?-1:1;if(typeof c=="number")this.b=c};Q.Q=function(){return new ih(this.ha,this.a,!this.c,this.S,this.b)};function jh(a){var b=a.a?-1:1;if(a.S==b){a.S=b*-1;a.b+=a.S*(a.a?-1:1)}}
Q.Ya=function(){var a;if(this.oc){if(!this.ha||this.c&&this.b==0)h(gh);a=this.ha;var b=this.a?-1:1;if(this.S==b){var c=this.a?a[nb]:a[M];c?this[Kb](c):this[Kb](a,b*-1)}else(c=this.a?a[Da]:a[Qb])?this[Kb](c):this[Kb](a[O],b*-1);this.b+=this.S*(this.a?-1:1)}else this.oc=i;a=this.ha;if(!this.ha)h(gh);return a};
Q.splice=function(){var a=this.ha,b=this.a?1:-1;if(this.S==b){this.S=b*-1;this.b+=this.S*(this.a?-1:1)}this.a=!this.a;ih[B].Ya[L](this);this.a=!this.a;b=hc(arguments[0])?arguments[0]:arguments;for(var c=b[A]-1;c>=0;c--)a[O]&&a[O][bb](b[c],a[Qb]);xe(a)};var kh=ia("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function lh(a,b,c){this.a=new ih;this.D=a;this.oa=b;this.O=c}var mh=ug(["A","ABBR","ACRONYM","B","BASEFONT","BDO","BIG","CITE","CODE","DFN","EM","FONT","I","KBD","LABEL","Q","S","SMALL","SPAN","STRIKE","STRONG","SUB","SUP","TT","U","VAR"]),nh=ug(["APPLET","AREA","BASE","FRAME","FRAMESET","HR","IMG","LINK","META","MAP","OBJECT","PARAM","SCRIPT","STYLE","INPUT","TEXTAREA"]),oh=ug(["submit","button"]);lh[B].reset=function(a,b){this.j=[];this.l=[];this.G=i;this.k=[];this.B=[];ph(this,a,i,b)};
function ph(a,b,c,d){a.a[Kb](b,1,1);a.m=i;a.d=0;a.f=[c];a.b=W?[]:j;a.g=!!d;a.a.oc||a.a.Ya();qh(a)}
function rh(a,b){if(a.m){var c=0,d=[],e=[],f=0,g=[],k=a.g?27:13;do{var o=a.N;f+=a.d||(a.d=(a.g?Tc(o)[A]:o[A])+k);if(c!=0&&f>b)break;a.d=0;d[y](a.K);g[y](a.c);if(c==0){e[y](o);c++}else{if(c==1)e[0]="<a i=0>"+e[0]+"</a>";e[y]("<a i="+c++ +">");e[y](o);e[y]("</a>")}}while(qh(a));return new Wg(d,e[Tb](""),g,(d[A]==1?f-k:f)-a.d,a.oa,a.O)}else if(a.j[A]>0){ph(a,a.j[Ia](),a.l[Ia](),a.g);return rh(a,b)}else if(a.k[A]>0){a.G=l;ph(a,a.k[Ia](),a.B[Ia](),a.g);return rh(a,b)}}
function sh(a){return a.f[a.f[A]-1]}function th(a){var b=a.a.ha,c=a.a.S;a.b&&a.b[A]>0&&c!=1&&!b[Qb]?a.a[Kb](a.b[a.b[A]-1],-1,a.a.b-1):a.a.Ya()}
function qh(a){var b=i;try{for(;;){var c=a.K=a.a.ha,d=a.a.S;if(d==-1){a.f.pop();if(a.b&&a.b[A]>0)a.b.length-=1;b=b&&!!c&&(c[F]==3||mh[c[N]])}else if(c&&(c[F]==3||c[N]=="TEXTAREA"&&gd(de(c),"translate")||c[N]=="INPUT"&&(oh[c[Gb]]||gd(de(c),"translate")))){jh(a.a);if(sh(a)){a.c=Dg(c);var e=Pc(a.c[E](/\xa0|[ \t]+/g," "));e||(a.c=e);if(a.c){a.N=Uc(a.c);th(a);break}}}else if(d==1){if(uh(c))jh(a.a);else if(c[N]=="IFRAME"){jh(a.a);try{var f;if(!(f=!c.src[ob](/https?:\/\//))){var g,k=c.src[ob](kh)[3]||j;
g=k&&ha(k);f=g==p[$a].hostname}if(f){var o=c[Rb][Ua][Wb];if(o){a.j[y](o);a.l[y](sh(a))}}}catch(q){}}else if(a.G&&!(c[Wa]&&c[Sb])){jh(a.a);a.k[y](c);a.B[y](sh(a))}else{var w=a,s=c,u=!gd(de(s),"notranslate")&&(gd(de(s),"translate")||sh(w));w.f[y](u);a.b&&a.b[y](c)}b=b&&sh(a)&&!!c&&(c[F]==3||mh[c[N]]);a.D&&sh(a)&&c[N]=="A"&&c[Bb]&&a.D(c)}th(a)}}catch(U){if(U!=gh)h(U);a.m=l;a.c=j;b=l}return b}function uh(a){return a[F]!=3&&(!a[N]||nh[a[N]]||gd(de(a),"skiptranslate"))};function vh(a,b){dg[L](this,b);this.d=new Yf(this);this.e=a||{};this.e.A||(this.e.A=Ic);this.e.nc=l;Af(this.b.a[J],"position","relative");Af(this.b.a[J],"minHeight","100%");Af(this.b.a[Wb],"height","100%");Af(this.b.a[J],"top","0px");if(W){p._bannerquirkfixleft=-ea("0"+this.b.a[J].leftMargin,10);p._bannerquirkfixtop=-ea("0"+this.b.a[J].topMargin,10)-40}}V(vh,dg);Q=vh[B];Q.ma=function(){var a=this.b.a[J][M];fg(this,a[O],a)};
Q.t=function(){this.h=this.b[rb]("div");this.f=l;X(this.h,l);ee(this.h,"skiptranslate");var a={id:Z(this,"container")},b=this.h;a=a;var c=new mg;c.H('<iframe id="',a.id,'" class="goog-te-banner-frame skiptranslate" frameBorder=0 src="javascript:\'\'" style="visibility:visible"></iframe>');a=c[z]();pa(b,a)};
Q.Y=function(){vh.s.Y[L](this);var a={dir:kg[Ha](rc)?"rtl":"ltr",A:this.e.A,ya:Lc,fc:"http://translate.google.com",Da:Mc,Ra:Dc,Td:Z(this,"promptSection"),ad:Z(this,"confirm"),Kd:"http://www.google.com/intl/en/help/faq_translation.html#element",Rd:Z(this,"progressSection"),Qd:Z(this,"progressValue"),Ld:Gc,Zc:Z(this,"cancel"),gd:Z(this,"finishSection"),Ud:Z(this,"restore"),ed:Z(this,"errorSection"),dd:Z(this,"errorContent"),$c:Z(this,"close"),re:Dc,Nd:Z(this,"noAutoPopup")},b=[];this.e.nc&&b[y](pg({id:Z(this,
"promptSourceLang")}));b[y](pg({id:Z(this,"promptTargetLang")}));a.Sd=fh[Hb](j,b);b=[];this.e.nc&&b[y](pg({id:Z(this,"finishSourceLang")}));b[y](pg({id:Z(this,"finishTargetLang")}));a.fd=eh[Hb](j,b);this.e.Ga&&(a.Ga=this.e.Ga);this.z=this.b.n(Z(this,"container"));Y(this.d,this.z,"load",this.ce);Jg(this.z,T(function(){var c=Ae(this.z);c[hb](og(a));c[eb]()},this))};
Q.ce=function(){this.a=new he(Ae(this.z));pa(this.a.n(Z(this,"errorContent")),"\u9519\u8bef\uff1a\u670d\u52a1\u5668\u65e0\u6cd5\u5b8c\u6210\u60a8\u7684\u8bf7\u6c42\u3002\u8bf7\u7a0d\u540e\u518d\u8bd5\u3002");if(this.e.A==Ic){var a="url("+Cc+")";Af(this.a.a[J],"backgroundImage",a);for(var b=this.a.a[Ub]("button"),c=0;c<b[A];++c){Af(b[c][O],"backgroundImage",a);Af(b[c][O],"backgroundRepeat","repeat-x");Af(b[c][O],"backgroundPosition","0 -39px")}}if(this.e.nc)this.I=new ch(this.e,this.a);this.c=new ch(this.e,
this.a);Y(this.d,this.a.n(Z(this,"confirm")),"click",Fg(this,"clk_confirm"));Y(this.d,this.a.n(Z(this,"cancel")),"click",Fg(this,"clk_cancel"));Y(this.d,this.a.n(Z(this,"restore")),"click",Fg(this,"clk_restore"));Y(this.d,this.a.n(Z(this,"close")),"click",Fg(this,"clk_close"));this.k=this.a.n(Z(this,"noAutoPopup"));Y(this.d,this.k,"click",Fg(this,"clk_no_ap"));this.I&&Y(this.d,this.I,"chg_lang",Fg(this,"chg_src_lang"));Y(this.d,this.c,"chg_lang",Fg(this,"chg_tgt_lang"));a=new wg(T(this[H],this,"load"));
this.I&&Y(this.d,this.I,"load",xg(a));Y(this.d,this.c,"load",xg(a));a.pa();this.I&&this.I.ma(this.a.n(Z(this,"promptSourceLang")));this.c.ma(this.a.n(Z(this,"promptTargetLang")))};Q.M=function(){this.P(l);vh.s.M[L](this);this.d.p();this.d=j;if(this.I){this.I.p();this.I=j}this.c.p();this.c=j;xe(this.z);this.kb=this.a=j};Q.ba=function(){return this.c.Ab()};
function wh(a,b){a.I&&a.I.va(b);if(a.l)if(a.l[b]){var c;c=c="\u5173\u95ed\u4ee5\u4e0b\u8bed\u8a00\u7684\u81ea\u52a8\u6a2a\u5e45\u5f39\u51fa\u529f\u80fd\uff1a"+a.l[b];a.a.Ib(a.k,c)}}Q.U=function(a){this.c.va(a)};
function xh(a,b,c,d){if(a.kb!=b){a.kb=b;if(b==0){a.I&&ah(a.I,a.a.n(Z(a,"promptSourceLang")));if(a.j){var e=a.ba();a.c.ua(a.j);a.U(e)}ah(a.c,a.a.n(Z(a,"promptTargetLang")))}else if(b==2){a.I&&ah(a.I,a.a.n(Z(a,"finishSourceLang")));if(a.g){e=a.ba();a.c.ua(a.g);a.U(e)}ah(a.c,a.a.n(Z(a,"finishTargetLang")))}e={};e[-1]=a.a.n(Z(a,"errorSection"));e[0]=a.a.n(Z(a,"promptSection"));e[1]=a.a.n(Z(a,"progressSection"));e[2]=a.a.n(Z(a,"finishSection"));for(var f in e)e[f]!==r[B][f]&&X(e[f],f==b)}c&&a.P(i);ya(a.k[O][O][I],
d?"block":"none")}Q.fa=$b("f");
Q.P=function(a){if(this.f!=a){this.f=a;if(W)var b=ea("0"+this.b.a[J].leftMargin,10),c=ea("0"+this.b.a[J].topMargin,10);var d=this.b.a.compatMode=="BackCompat";if(a){Af(this.b.a[J],"top","40px");X(this.h,i);if(W)if($d("7.0")){p._bannerquirkfixleft=p._bannerquirkfixtop=0;if(d)this.b.a[J].topMargin=c+40}else if(d){this.m=i;this.b.a[J].topMargin=c+40;p._bannerquirkfixleft=p._bannerquirkfixtop=0}else{p._bannerquirkfixleft=-b;p._bannerquirkfixtop=-c-40}}else{Af(this.b.a[J],"top","0px");X(this.h,l);if(d&&
c>=40)this.b.a[J].topMargin=c-40}}};function yh(a,b){a.a.Ib(a.a.n(Z(a,"progressValue")),b)}Q.mc=function(a,b){this.j=a;this.g=b;this.c.ua(a)};function zh(a,b){dg[L](this,b);this.e=a||{};this.a=new Yf(this)}V(zh,dg);var Ah={pe:0,le:1,me:2};Q=zh[B];
Q.t=function(){this.h=this.b[rb]("div");ee(this.h,"skiptranslate");ee(this.h,"goog-te-gadget");X(this.h,l);if(this.e.Ta==2)pa(this.h,qg({id:Z(this,"targetLanguage"),Pc:"",Oc:""}));else{var a;a={cc:W&&!$d("7.0"),Da:Hc,fc:"http://translate.google.com"};var b=new mg;b.H('<span style="white-space:nowrap"><a class="goog-logo-link" href="',a.fc,'" target="_blank">',a.cc?"<span style=\"display:inline-block;vertical-align:middle;height:15px; width:51px;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader( src='"+a.Da+
"',sizingMethod='scale');\"></span>":'<img src="'+a.Da+'">',"\u7ffb\u8bd1","</a></span>");a=b[z]();a=a="\u7531 "+(a+"\u5f3a\u529b\u9a71\u52a8");pa(this.h,qg({id:Z(this,"targetLanguage"),Pc:"",Oc:this.e.Ta==1?"&nbsp;&nbsp;"+a:a}))}};
Q.Y=function(){zh.s.Y[L](this);this.c=this.e.Ta==2?new ch({hd:i},this.b):new $g(this.b);Y(this.a,this.c,"chg_lang",Fg(this,"chg_tgt_lang"));Y(this.a,this.c,"load",this.yd);var a=this.b.Wc(Z(this,"targetLanguage"));if(this.e.Ta==2){var b=this.b.t("img",{src:Lc,"class":"goog-te-gadget-icon"});b[I].backgroundImage="url("+Dc+")";b[I].backgroundPosition="-65px 0px";var c=this.b.t("span",{style:"vertical-align: middle"});a[x](b);a[x](c);this.c.ma(c);a[I].whiteSpace="nowrap";ma(a,"goog-te-gadget-simple")}else{this.c.ma(a);
if(this.e.Ta==1)ya(a[I],"inline")}};Q.yd=function(){this[H]("load")};Q.M=function(){zh.s.M[L](this);this.a.p();this.a=j;this.c.p();this.c=j};Q.ba=function(){return this.c.Ab()};Q.U=function(a){if(a=="")this.j&&this.c.ua(this.j);else this.g&&this.c.ua(this.g);this.c.va(a)};Q.P=function(a){X(this.h,a)};Q.bb=function(a){this.c.bb(a)};Q.mc=function(a,b){this.j=a;this.g=b};function Bh(a,b){dg[L](this,b);this.e=a||{};this.e.A||(this.e.A=Ic);this.a=new Yf(this)}V(Bh,dg);var Ch={ne:1,oe:2,je:3,ie:4};Q=Bh[B];Q.t=function(){this.h=this.b[rb]("div");this.f=l;X(this.h,l);var a={id:Z(this,"container")},b=this.h;a=a;var c=new mg;c.H('<iframe id="',a.id,'" frameBorder=0 src="javascript:\'\'" class="goog-te-ftab-frame skiptranslate" style="visibility:visible"></iframe>');a=c[z]();pa(b,a)};
Q.Y=function(){Bh.s.Y[L](this);var a={dir:kg[Ha](rc)?"rtl":"ltr",A:this.e.A,ge:Z(this,"translate"),ya:Lc,Ra:Dc};this.h.id=Z(this,"floatContainer");var b={id:this.h.id,className:"goog-te-ftab-float"};this.h.className+=" goog-te-ftab-float";switch(this.e.mb){case 2:a.xb="goog-float-top";b.top=0;Ba(b,20);break;case 3:a.xb="goog-float-bottom";wa(b,0);Ba(b,20);break;case 4:a.xb="goog-float-bottom";wa(b,0);sa(b,20);break;default:a.xb="goog-float-top";b.top=0;sa(b,20)}Qf(sg(b),this.h);this.z=this.b.n(Z(this,
"container"));Y(this.a,this.z,"load",this.de);Jg(this.z,T(function(){var c=Ae(this.z);c[hb](rg(a));c[eb]()},this))};Q.de=function(){var a=new he(Ae(this.z));this.c=a.n(Z(this,"translate"));Y(this.a,this.c,"click",Fg(this,"clk_trans"));X(this.h,i);a=Sf(this.c);X(this.h,l);Tf(this.z,a);Tf(this.h,a);this[H]("load")};Q.M=function(){Bh.s.M[L](this);this.a.p();this.a=j;xe(this.z);this.c=this.z=j};Q.fa=$b("f");Q.P=function(a){this.f=a;X(this.h,a)};function Dh(a){if(typeof a.Aa=="function")return a.Aa();if(ic(a))return a[Va]("");if(hc(a)){for(var b=[],c=a[A],d=0;d<c;d++)b[y](a[d]);return b}return rd(a)}function Eh(a,b,c){if(typeof a[ub]=="function")a[ub](b,c);else if(hc(a)||ic(a))fd(a,b,c);else{var d;var e=a;if(typeof e.Na=="function")d=e.Na();else if(typeof e.Aa!="function")if(hc(e)||ic(e)){d=[];e=e[A];for(var f=0;f<e;f++)d[y](f);d=d}else d=td(e);else d=void 0;e=Dh(a);f=e[A];for(var g=0;g<f;g++)b[L](c,e[g],d&&d[g],a)}};function Fh(a){this.b={};this.a=[];var b=arguments[A];if(b>1){if(b%2)h(ba("Uneven number of arguments"));for(var c=0;c<b;c+=2)this.da(arguments[c],arguments[c+1])}else if(a){c=a;if(c instanceof Fh){b=c.Na();c=c.Aa()}else{b=td(c);c=rd(c)}for(var d=0;d<b[A];d++)this.da(b[d],c[d])}}Q=Fh[B];Q.o=0;Q.sb=0;Q.Aa=function(){Gh(this);for(var a=[],b=0;b<this.a[A];b++){var c=this.a[b];a[y](this.b[c])}return a};Q.Na=function(){Gh(this);return this.a[Xa]()};Q.ia=function(a){return Hh(this.b,a)};
Q.clear=function(){this.b={};la(this.a,0);this.sb=this.o=0};Q.remove=function(a){if(Hh(this.b,a)){delete this.b[a];this.o--;this.sb++;this.a[A]>2*this.o&&Gh(this);return i}return l};function Gh(a){if(a.o!=a.a[A]){for(var b=0,c=0;b<a.a[A];){var d=a.a[b];if(Hh(a.b,d))a.a[c++]=d;b++}la(a.a,c)}if(a.o!=a.a[A]){var e={};for(c=b=0;b<a.a[A];){d=a.a[b];if(!Hh(e,d)){a.a[c++]=d;e[d]=1}b++}la(a.a,c)}}Q.ra=function(a,b){if(Hh(this.b,a))return this.b[a];return b};
Q.da=function(a,b){if(!Hh(this.b,a)){this.o++;this.a[y](a);this.sb++}this.b[a]=b};Q.Q=function(){return new Fh(this)};Q.Xc=function(a){Gh(this);var b=0,c=this.a,d=this.b,e=this.sb,f=this,g=new hh;g.Ya=function(){for(;;){if(e!=f.sb)h(ba("The map has changed since the iterator was created"));if(b>=c[A])h(gh);var k=c[b++];return a?k:d[k]}};return g};function Hh(a,b){return r[B][db][L](a,b)};function Ih(a,b){var c;if(a instanceof Ih){Jh(this,b==j?a.Oa:b);Kh(this,a.ta);Lh(this,a.rb);Mh(this,a.Ma);Nh(this,a.$a);Oh(this,a.Za);Ph(this,a.a.Q());Qh(this,a.nb)}else if(a&&(c=n(a)[ob](kh))){Jh(this,!!b);Kh(this,c[1]||"",i);Lh(this,c[2]||"",i);Mh(this,c[3]||"",i);Nh(this,c[4]);Oh(this,c[5]||"",i);Ph(this,c[6]||"",i);Qh(this,c[7]||"",i)}else{Jh(this,!!b);this.a=new Rh(j,this,this.Oa)}}Q=Ih[B];Q.ta="";Q.rb="";Q.Ma="";Q.$a=j;Q.Za="";Q.nb="";Q.Id=l;Q.Oa=l;
ka(Q,function(){if(this.V)return this.V;var a=[];this.ta&&a[y](Sh(this.ta,Th),":");if(this.Ma){a[y]("//");this.rb&&a[y](Sh(this.rb,Th),"@");a[y](Uh(this.Ma));this.$a!=j&&a[y](":",n(this.$a))}if(this.Za){this.Ma&&this.Za.charAt(0)!="/"&&a[y]("/");a[y](Sh(this.Za,Vh))}var b=n(this.a);b&&a[y]("?",b);this.nb&&a[y]("#",Sh(this.nb,Wh));return this.V=a[Tb]("")});
Q.Q=function(){var a;a=this.ta;var b=this.rb,c=this.Ma,d=this.$a,e=this.Za,f=this.a.Q(),g=this.nb,k=new Ih(j,this.Oa);a&&Kh(k,a);b&&Lh(k,b);c&&Mh(k,c);d&&Nh(k,d);e&&Oh(k,e);f&&Ph(k,f);g&&Qh(k,g);return a=k};function Kh(a,b,c){Xh(a);delete a.V;a.ta=c?b?ha(b):"":b;if(a.ta)a.ta=a.ta[E](/:$/,"");return a}function Lh(a,b,c){Xh(a);delete a.V;a.rb=c?b?ha(b):"":b;return a}function Mh(a,b,c){Xh(a);delete a.V;a.Ma=c?b?ha(b):"":b;return a}
function Nh(a,b){Xh(a);delete a.V;if(b){b=ga(b);if(isNaN(b)||b<0)h(ba("Bad port number "+b));a.$a=b}else a.$a=j;return a}function Oh(a,b,c){Xh(a);delete a.V;a.Za=c?b?ha(b):"":b;return a}function Ph(a,b,c){Xh(a);delete a.V;if(b instanceof Rh){a.a=b;a.a.d=a;Yh(a.a,a.Oa)}else{c||(b=Sh(b,Zh));a.a=new Rh(b,a,a.Oa)}return a}function $h(a,b,c){Xh(a);delete a.V;a.a.da(b,c);return a}
function ai(a,b,c){Xh(a);delete a.V;gc(c)||(c=[n(c)]);var d=a.a;b=b;c=c;bi(d);ci(d);b=di(d,b);if(d.ia(b)){var e=d.w.ra(b);if(gc(e))d.o-=e[A];else d.o--}if(c[A]>0){d.w.da(b,c);d.o+=c[A]}return a}function Qh(a,b,c){Xh(a);delete a.V;a.nb=c?b?ha(b):"":b;return a}function Xh(a){if(a.Id)h(ba("Tried to modify a read-only Uri"))}function Jh(a,b){a.Oa=b;a.a&&Yh(a.a,b)}function Uh(a){if(ic(a))return da(a);return j}var ei=/^[a-zA-Z0-9\-_.!~*'():\/;?]*$/;
function Sh(a,b){var c=j;if(ic(a)){c=a;ei[Ha](c)||(c=encodeURI(a));if(c.search(b)>=0)c=c[E](b,fi)}return c}function fi(a){a=a.charCodeAt(0);return"%"+(a>>4&15)[z](16)+(a&15)[z](16)}var Th=/[#\/\?@]/g,Vh=/[\#\?]/g,Zh=/[\#\?@]/g,Wh=/#/g;function Rh(a,b,c){this.a=a||j;this.d=b||j;this.c=!!c}
function bi(a){if(!a.w){a.w=new Fh;if(a.a)for(var b=a.a[Va]("&"),c=0;c<b[A];c++){var d=b[c][G]("="),e=j,f=j;if(d>=0){e=b[c][Cb](0,d);f=b[c][Cb](d+1)}else e=b[c];e=ha(e[E](/\+/g," "));e=di(a,e);a.add(e,f?ha(f[E](/\+/g," ")):"")}}}Q=Rh[B];Q.w=j;Q.o=j;Q.add=function(a,b){bi(this);ci(this);a=di(this,a);if(this.ia(a)){var c=this.w.ra(a);gc(c)?c[y](b):this.w.da(a,[c,b])}else this.w.da(a,b);this.o++;return this};
Q.remove=function(a){bi(this);a=di(this,a);if(this.w.ia(a)){ci(this);var b=this.w.ra(a);if(gc(b))this.o-=b[A];else this.o--;return this.w.remove(a)}return l};Q.clear=function(){ci(this);this.w&&this.w.clear();this.o=0};Q.ia=function(a){bi(this);a=di(this,a);return this.w.ia(a)};Q.Na=function(){bi(this);for(var a=this.w.Aa(),b=this.w.Na(),c=[],d=0;d<b[A];d++){var e=a[d];if(gc(e))for(var f=0;f<e[A];f++)c[y](b[d]);else c[y](b[d])}return c};
Q.Aa=function(a){bi(this);if(a){a=di(this,a);if(this.ia(a)){var b=this.w.ra(a);if(gc(b))return b;else{a=[];a[y](b)}}else a=[]}else{b=this.w.Aa();a=[];for(var c=0;c<b[A];c++){var d=b[c];gc(d)?kd(a,d):a[y](d)}}return a};Q.da=function(a,b){bi(this);ci(this);a=di(this,a);if(this.ia(a)){var c=this.w.ra(a);if(gc(c))this.o-=c[A];else this.o--}this.w.da(a,b);this.o++;return this};Q.ra=function(a,b){bi(this);a=di(this,a);if(this.ia(a)){var c=this.w.ra(a);return gc(c)?c[0]:c}else return b};
ka(Q,function(){if(this.a)return this.a;if(!this.w)return"";for(var a=[],b=0,c=this.w.Na(),d=0;d<c[A];d++){var e=c[d],f=Tc(e);e=this.w.ra(e);if(gc(e))for(var g=0;g<e[A];g++){b>0&&a[y]("&");a[y](f);e[g]!==""&&a[y]("=",Tc(e[g]));b++}else{b>0&&a[y]("&");a[y](f);e!==""&&a[y]("=",Tc(e));b++}}return this.a=a[Tb]("")});function ci(a){delete a.b;delete a.a;a.d&&delete a.d.V}Q.Q=function(){var a=new Rh;if(this.b)a.b=this.b;if(this.a)a.a=this.a;if(this.w)a.w=this.w.Q();return a};
function di(a,b){var c=n(b);if(a.c)c=c.toLowerCase();return c}function Yh(a,b){var c=b&&!a.c;if(c){bi(a);ci(a);Eh(a.w,function(d,e){var f=e.toLowerCase();if(e!=f){this.remove(e);this.add(f,d)}},a)}a.c=b};function gi(a,b){this.b=new Ih(a);this.a=b?b:"callback";this.wa=5E3}var hi=0;
ua(gi[B],function(a,b,c,d){if(!t[Wb][M]){c&&c(a);return j}d=d||"_"+(hi++)[z](36)+pc()[z](36);R._callbacks_||(R._callbacks_={});var e=t[rb]("script"),f=j;if(this.wa>0){f=ii(d,e,a,c);f=R[Ta](f,this.wa)}c=this.b.Q();a=a;var g=c;for(var k in a)if(!a[db]||a[db](k))ai(g,k,a[k]);if(b){b=ji(d,e,b,f);R._callbacks_[d]=b;ai(c,this.a,"_callbacks_."+d)}le(e,{type:"text/javascript",id:d,charset:"UTF-8",src:c[z]()});b=t[Ub]("head")[0];b[x](e);return{R:d,wa:f}});
oa(gi[B],function(a){if(a&&a.R){var b=ic(a.R)?t.getElementById(a.R):a.R;if(b&&b[N]=="SCRIPT"&&typeof R._callbacks_[a.R]=="function"){a.wa&&R[La](a.wa);ki(a.R,b,l)}}});function ii(a,b,c,d){return function(){ki(a,b,l);d&&d(c)}}function ji(a,b,c,d){return function(){R[La](d);ki(a,b,i);c[Hb](m,arguments)}}function ki(a,b,c){R[Ta](function(){xe(b)},0);if(R._callbacks_[a])if(c)delete R._callbacks_[a];else R._callbacks_[a]=dc};function li(a){return mi(a||arguments.callee.caller,[])}
function mi(a,b){var c=[];if(gd(b,a))c[y]("[...circular reference...]");else if(a&&b[A]<50){c[y](ni(a)+"(");for(var d=a.arguments,e=0;e<d[A];e++){e>0&&c[y](", ");var f;f=d[e];switch(typeof f){case "object":f=f?"object":"null";break;case "string":f=f;break;case "number":f=n(f);break;case "boolean":f=f?"true":"false";break;case "function":f=(f=ni(f))?f:"[fn]";break;default:f=typeof f}if(f[A]>40)f=f[Xb](0,40)+"...";c[y](f)}b[y](a);c[y](")\n");try{c[y](mi(a.caller,b))}catch(g){c[y]("[exception trying to get caller]\n")}}else a?
c[y]("[...long stack...]"):c[y]("[end]");return c[Tb]("")}function ni(a){a=n(a);if(!oi[a]){var b=/function ([^\(]+)/[Ka](a);if(b){b=b[1];oi[a]=b}else oi[a]="[Anonymous]"}return oi[a]}var oi={};function pi(a,b,c,d,e){this[Lb](a,b,c,d,e)}pi[B].c=0;pi[B].a=j;pi[B].zc=j;var qi=0;pi[B].reset=function(a,b,c,d,e){this.c=typeof e=="number"?e:qi++;this.g=d||pc();this.b=a;this.f=b;this.d=c;delete this.a;delete this.zc};pi[B].Rc=Zb("b");function ri(a){this.g=a}ri[B].a=j;ri[B].c=j;ri[B].b=j;ri[B].d=j;function si(a,b){this.name=a;qa(this,b)}ka(si[B],$b("name"));var ti=new si("SEVERE",1E3),ui=new si("WARNING",900),vi=new si("CONFIG",700),wi=new si("FINE",500);ri[B].Rc=Zb("c");function xi(a){if(a.c)return a.c;if(a.a)return xi(a.a);return j}ri[B].log=function(a,b,c){if(a[Za]>=xi(this)[Za]){a=this.f(a,b,c);for(b=this;b;){c=b;var d=a;if(c.d)for(var e=0,f=void 0;f=c.d[e];e++)f(d);b=b.a}}};
ri[B].f=function(a,b,c){var d;d=d=new pi(a,n(b),this.g);if(c){d.a=c;var e=d,f;var g=arguments.callee.caller;try{var k,o=c,q=cc("window.location.href");k=typeof o=="string"?{message:o,name:"Unknown error",lineNumber:"Not available",fileName:q,stack:"Not available"}:!o.lineNumber||!o[Ob]||!o.stack?{message:o[cb],name:o[Nb],lineNumber:o.lineNumber||o.line||"Not available",fileName:o[Ob]||o.filename||o.sourceURL||q,stack:o.stack||"Not available"}:o;var w="Message: "+Uc(k[cb])+'\nUrl: <a href="view-source:'+
k[Ob]+'" target="_new">'+k[Ob]+"</a>\nLine: "+k.lineNumber+"\n\nBrowser stack:\n"+Uc(k.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+Uc(li(g)+"-> ");f=w}catch(s){f="Exception trying to expose exception! You win, we lose. "+s}e.zc=f}return d};function yi(a,b,c){a.log(wi,b,c)}var zi={},Ai=j;
function Bi(a){if(!Ai){Ai=new ri("");zi[""]=Ai;Ai.Rc(vi)}var b=zi[a];if(!(b=b)){a=a;b=new ri(a);var c=a.lastIndexOf("."),d=a[Xb](0,c);c=a[Xb](c+1);d=Bi(d);c=c;var e=b,f;f=d;if(!f.b)f.b={};f=f.b;f[c]=e;b.a=d;b=zi[a]=b}return b};var Ci=R.window;function Di(){}Di[B].vb=j;function Ei(){return Fi(Gi)}var Gi;function Hi(){}V(Hi,Di);function Fi(a){return(a=Ii(a))?new ActiveXObject(a):new XMLHttpRequest}function Ji(a){a=Ii(a);var b={};if(a){b[0]=i;b[1]=i}return b}Hi[B].a=j;
function Ii(a){if(!a.a&&typeof XMLHttpRequest=="undefined"&&typeof ActiveXObject!="undefined"){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b[A];c++){var d=b[c];try{new ActiveXObject(d);return a.a=d}catch(e){}}h(ba("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed"))}return a.a}var Ki=new Hi;Gi=Ki;function Li(a){this.headers=new Fh;this.a=a||j}V(Li,bg);Q=Li[B];Q.T=Bi("goog.net.XhrIo");Q.xa=l;Q.F=j;Q.Pb=j;Q.Ic="";Q.Hc="";Q.ob=0;Q.pb="";Q.Wb=l;Q.Cb=l;Q.dc=l;Q.Ba=l;Q.Lb=0;Q.Ia=j;
ua(Q,function(a,b,c,d){if(this.F)h(ba("[goog.net.XhrIo] Object is active with another request"));b=b||"GET";this.Ic=a;this.pb="";this.ob=0;this.Hc=b;this.Wb=l;this.xa=i;this.F=this.a?Fi(this.a):new Ei;this.Pb=this.a?this.a.vb||(this.a.vb=Ji(this.a)):Gi.vb||(Gi.vb=Ji(Gi));this.F.onreadystatechange=T(this.Lc,this);try{yi(this.T,Mi(this,"Opening Xhr"));this.dc=i;this.F.open(b,a,i);this.dc=l}catch(e){yi(this.T,Mi(this,"Error opening Xhr: "+e[cb]));Ni(this,5,e);return}a=c||"";var f=this.headers.Q();d&&
Eh(d,function(k,o){f.da(o,k)});b=="POST"&&!f.ia("Content-Type")&&f.da("Content-Type","application/x-www-form-urlencoded;charset=utf-8");Eh(f,function(k,o){this.F.setRequestHeader(o,k)},this);try{if(this.Ia){Ci[La](this.Ia);this.Ia=j}if(this.Lb>0){yi(this.T,Mi(this,"Will abort after "+this.Lb+"ms if incomplete"));this.Ia=Ci[Ta](T(this.wa,this),this.Lb)}yi(this.T,Mi(this,"Sending request"));this.Cb=i;this.F[qb](a);this.Cb=l}catch(g){yi(this.T,Mi(this,"Send error: "+g[cb]));Ni(this,5,g)}});
Q.dispatchEvent=function(a){return Li.s[H][L](this,a)};Q.wa=function(){if(typeof ac!="undefined")if(this.F){this.pb="Timed out after "+this.Lb+"ms, aborting";this.ob=8;yi(this.T,Mi(this,this.pb));this[H]("timeout");this[Ra](8)}};function Ni(a,b,c){a.xa=l;if(a.F){a.Ba=i;a.F[Ra]();a.Ba=l}a.pb=c;a.ob=b;Oi(a);Pi(a)}function Oi(a){if(!a.Wb){a.Wb=i;a[H]("complete");a[H]("error")}}
Q.abort=function(a){if(this.F){yi(this.T,Mi(this,"Aborting"));this.xa=l;this.Ba=i;this.F[Ra]();this.Ba=l;this.ob=a||7;this[H]("complete");this[H]("abort");Pi(this)}};Q.r=function(){if(this.F){if(this.xa){this.xa=l;this.Ba=i;this.F[Ra]();this.Ba=l}Pi(this,i)}Li.s.r[L](this)};Q.Lc=function(){!this.dc&&!this.Cb&&!this.Ba?this.Od():Qi(this)};Q.Od=function(){Qi(this)};
function Qi(a){if(a.xa)if(typeof ac!="undefined")if(a.Pb[1]&&Ri(a)==4&&Si(a)==2)yi(a.T,Mi(a,"Local request error detected and ignored"));else if(a.Cb&&Ri(a)==4)Ci[Ta](T(a.Lc,a),0);else{a[H]("readystatechange");if(Ri(a)==4){yi(a.T,Mi(a,"Request complete"));a.xa=l;if(Ti(a)){a[H]("complete");a[H]("success")}else{a.ob=6;var b=a,c;try{c=Ri(a)>2?a.F.statusText:""}catch(d){yi(a.T,"Can not get status: "+d[cb]);c=""}b.pb=c+" ["+Si(a)+"]";Oi(a)}Pi(a)}}}
function Pi(a,b){if(a.F){var c=a.F,d=a.Pb[0]?dc:j;a.F=j;a.Pb=j;if(a.Ia){Ci[La](a.Ia);a.Ia=j}b||a[H]("ready");try{c.onreadystatechange=d}catch(e){a.T.log(ti,"Problem encountered resetting onreadystatechange: "+e[cb],void 0)}}}function Ti(a){switch(Si(a)){case 0:case 200:case 204:case 304:return i;default:return l}}function Ri(a){return a.F?a.F.readyState:0}function Si(a){try{return Ri(a)>2?a.F.status:-1}catch(b){a.T.log(ui,"Can not get status: "+b[cb],void 0);return-1}}
function Mi(a,b){return b+" ["+a.Hc+" "+a.Ic+" "+Si(a)+"]"};var Ui;
(function(){function a(k){k=k[ob](/[\d]+/g);la(k,3);return k[Tb](".")}var b=l,c="";if(aa[Ga]&&aa[Ga][A]){var d=aa[Ga]["Shockwave Flash"];if(d){b=i;if(d.description)c=a(d.description)}if(aa[Ga]["Shockwave Flash 2.0"]){b=i;c="2.0.0.11"}}else if(aa.mimeTypes&&aa.mimeTypes[A]){if(b=(d=aa.mimeTypes["application/x-shockwave-flash"])&&d.enabledPlugin)c=a(d.enabledPlugin.description)}else try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7");b=i;c=a(d.GetVariable("$version"))}catch(e){try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");b=
i;c="6.0.21"}catch(f){try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");b=i;c=a(d.GetVariable("$version"))}catch(g){}}}Ui=c})();function Vi(a,b){this.cb=new Ih(a);if(b)for(var c in b)b[c]!==r[B][c]&&$h(this.cb,c,b[c])}V(Vi,Oc);za(Vi[B],function(){return i});va(Vi[B],function(){return this[Pb]()});ua(Vi[B],function(){return j});oa(Vi[B],function(){});function Wi(a,b,c,d){Vi[L](this,a,b);this.b=d==j||!!d;this.a=new gi(this.cb[z](),c)}V(Wi,Vi);za(Wi[B],$b("b"));ua(Wi[B],function(a,b){this.a.wa=-1;return this.a[qb](a,b)});oa(Wi[B],function(a){this.a[Pa](a)});
function Xi(a,b,c){Vi[L](this,"",c);this.d=a;this.f=b;this.g=Hg(c);this.b={};R._fhr_callback_||(R._fhr_callback_={});this.d=a;this.c=bd(Ui,"9.0")>=0}V(Xi,Vi);var Yi=0;function Zi(){return"I"+(Yi++)[z](36)+pc()[z](36)}
function $i(a){if(a.c){if(!a.k){a.k=pe("div",{style:"position:absolute;top:-1000px;height:1px;width:1px"});t[J][x](a.k);a.R="f"+Zi();var b={id:a.R,src:a.d},c=a.k;if(W){b=b;var d=new mg;d.H('<object id="',b.id,'" name="',b.id,'" width="400" height="500" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="//download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab"><param name="movie" value="',b.src,'"/><param name="allowScriptAccess" value="always"/></object>');b=d[z]()}else{b=b;d=new mg;
d.H('<object id="',b.id,'" name="',b.id,'" width="400" height="500" type="application/x-shockwave-flash" data="',b.src,'"><param name="allowScriptAccess" value="always"/></object>');b=d[z]()}pa(c,b)}if(!a.a)a.a=W?p[a.R]:t[a.R]}}Q=Xi[B];za(Q,function(){return this.c&&p[$a][sb]!="file:"});va(Q,function(){$i(this);return this.c&&this.a&&this.a[vb]&&this.a[vb]()});
ua(Q,function(a,b){$i(this);if(!this.a||!this.a[qb])return j;var c="cb"+Zi();R._fhr_callback_[c]=b;var d=this.a[qb](this.f,"_fhr_callback_."+c,this.g,Hg(a));if(d<0){delete R._fhr_callback_[c];return j}var e=Zi();this.b[e]={Yc:c,na:d};return e});oa(Q,function(a){$i(this);var b=this.b[a];if(b){this.a[Pa](b.na);delete R._fhr_callback_[b.Yc];delete this.b[a]}});
Q.r=function(){Xi.s.r[L](this);for(var a in this.b)if(this.b[a]!==r[B][a]){var b=this.b[a];this.a[Pa](b.na);delete R._fhr_callback_[b.na]}if(this.k){xe(this.k);this.a=this.b=this.k=j}};function aj(a,b){Vi[L](this,a,b);this.b={};this.a=this.c=0;if(!Jd){if(p.XMLHttpRequest){var c=new XMLHttpRequest;if("withCredentials"in c)this.a=1}if(!this.a&&p.XDomainRequest&&p[$a][sb]!="file:"){this.a=2;$h(this.cb,"u",p[$a][Bb])}}}V(aj,Vi);za(aj[B],function(){return!!this.a});
ua(aj[B],function(a,b){var c=Lg(),d=++this.c,e={};if(this.a==1){e.Ja=new Li;of(e.Ja,"complete",T(function(){if(!e.Ub){if(Ti(e.Ja)){var f=b,g;var k=e.Ja;try{g=k.F?k.F.responseText:""}catch(o){yi(k.T,"Can not get responseText: "+o[cb]);g=""}f(g)}else b(j,"IO_ERROR");bj(this,d)}},this));e.Ja[qb](this.cb[z](),"POST",Hg(a),{"Content-Type":"application/x-www-form-urlencoded"})}else{e.ea=new XDomainRequest;e.ea.timeout=2E4;e.ea.onload=T(function(){if(!e.Ub){b(e.ea.responseText);bj(this,d)}},this);e.ea.onerror=
e.ea.ontimeout=T(function(){if(!e.Ub){b(j,"IO_ERROR");bj(this,d)}},this);e.ea.open("POST",this.cb[z]());e.ea[qb](Hg(a))}this.b[d]=e;Mg(c);return d});oa(aj[B],function(a){var b=this.b[a];if(b){b.Ub=i;b.ea&&b.ea[Ra]();bj(this,a)}});function bj(a,b){var c=a.b[b];if(c){if(c.Ja){c.Ja.p();c.Ja=j}else if(c.ea)c.ea=j;delete a.b[b]}}aj[B].r=function(){aj.s.r[L](this);for(var a in this.b)this[Pa](a)};function cj(a){var b={anno:3,client:Ac,format:"html",v:"1.0"};a&&(b.ssl=1);if(zc)b.scid=zc;a=a?"https://":"http://";this.J=j;this.La={jb:dj,Jc:300};this.b=new Wi(a+Fc,{client:Ac},"cb");b=[{L:new aj(a+Bc+"/translate_a/t",b),jb:ej,Fb:30720,gc:61440,Wa:-1,jc:0,lb:l},{L:new Xi(a+Ec,"translate",b),Nc:100,jb:ej,Fb:30720,gc:61440,Wa:-1,jc:0,lb:l},{L:new Wi(a+Bc+"/translate_a/t",b,"cb",W&&Yd<=7),jb:fj,Fb:1900,gc:61440,Wa:-1,jc:3,lb:i}];this.c=new gj(b);this.a=l;for(a=0;a<b[A];++a)this.a=this.a||b[a].L[Pb]();
this.a||Ig("te_au")}V(cj,Oc);function gj(a){this.b=a}gj[B].start=function(a){this.Ka=a;this.a=0;hj(this)};function hj(a){if(a.a>=a.b[A])a.Ka(j);else{var b=a.b[a.a++];if(b.Nc)(new Cg(T(b.L[vb],b.L),T(function(c){c?this.Ka(b):hj(this)},a),30,b.Nc)).go();else b.L[vb]()?a.Ka(b):hj(a)}}
function ij(a){var b;if(fc(a)!="array")b=[[a,200]];else if(fc(a[0])!="array")if(a[A]==2)b=[[a[0],200,a[1]],[a[1],200,a[1]]];else{b=[];for(var c=0;c<a[A];++c)b[c]=[a[c],200]}else{b=[];for(c=0;c<a[A];++c)b[c]=[a[c][0],200,a[c][1]]}return b}function ej(a){return function(b){if(b)try{var c=b[G]("\u0000");if(c>=0)b=b[Xb](0,c);var d=eval("("+b+")")}catch(e){d=j;Ig("te_afbr")}d?a(ij(d),200):a([],500)}}function fj(a){return function(b){b?a(ij(b),200):a([],500)}}
function dj(a){return function(b){if(b)try{var c=eval("("+b+")")}catch(d){c=j}a(c&&c[1]||m)}}Q=cj[B];Q.Gd=function(a){if(!this.d){this.d=i;this.c.start(T(function(b){if(b){this.J=b;this.La.L=b.L}a()},this))}};za(Q,$b("a"));va(Q,function(){return this.J!==j&&this.J.L!==j&&this.J.L[vb]()});Q.translate=function(a,b,c,d,e,f){a=this.J.jb(a);b={q:b,sl:c,tl:d};b.tc=e;if(f)b.ctt=1;return this.J.L[qb](b,a)};function jj(a){return a.J.lb?a.J.Fb-a.J.L.cb.Q()[z]()[A]:a.J.Fb}
Q.r=function(){cj.s.r[L](this);if(this.J){this.J.L.p();this.J.L=j}this.La.L=j;this.b.p();this.b=j};function kj(a,b){this.d=a;this.l=!!b;this.a=this.k=0;this.b=this.c=-1;this.f=this.j=this.g=0}var lj=ug([".",",",";",":","\\?","!"]),mj=ug([34,35,36,37,38,43,44,47,58,59,60,61,62,63,64,91,92,93,94,96,123,124,125,127]);function nj(a,b){if(!a.l)return 1;if(b<=127){if(b<=32||mj[b])return 3;return 1}else if(b<=2047)return 6;else if(b<=65535)return 9;return 12}
function oj(a,b){a.l&&(b-=12);for(var c="",d=a.k;d<a.d[A];++d){var e=a.d.charAt(d),f=e.charCodeAt(0);a.g+=nj(a,f);if(lj[e]){a.b=d;a.j=a.g}else if(e==" "){a.c=d;a.f=a.g}if(a.g>=b){if(a.b>=0){c=a.d[Cb](a.a,a.b+1);a.g-=a.j;a.a=a.b+1;if(a.b>=a.c){a.c=-1;a.f=0}else a.f-=a.j;a.b=-1;a.j=0}else if(a.c>=0){c=a.d[Cb](a.a,a.c+1);a.g-=a.f;a.a=a.c+1;if(a.c>=a.b)a.b=-1;else a.j-=a.f;a.c=-1;a.f=0}else{c=a.d[Cb](a.a,d+1);a.g=0;a.a=d+1;a.b=a.c=-1;a.f=a.j=0}a.k=d+1;return c}}if(a.a<a.d[A]){c=a.d[Cb](a.a);a.a=a.d[A]}return c}
function pj(a,b,c,d,e){this.O=a;this.f=b;this.sc=c;this.K=new lh(d?T(this.Vd,this):j,c,e);this.m=j;this.B=l;this.j="auto";this.d="en";this.rc=l;this.l={};this.c={};this.ke=[]}V(pj,Oc);Q=pj[B];
Q.Bc=function(){var a=this.eb,b;if(b=a.db>0){b=a;var c;c=a.Eb;var d=rh(this.K,c);if(d)c=d;else if(this.Qb[A]){this.K[Lb](this.Qb[Ia](),this.eb.Vc);c=rh(this.K,c)}else c=j;b=b.X=c}if(b){this.m[y](a.X);var e=this.f.J.lb?a.X.B:a.X.ja[A];this.gb+=a.X.ja[A];if(this.l&&this.l[a.X.ja]){this.b.add(T(this.Sb,this,a.X));a.db-=e}else if(e>a.W){b=a.X.ja;c=new kj(b);d=[];var f="";if(a.Sa)for(;qj(a)&&e>a.W;);for(;f=oj(c,a.W);){e={na:j,X:a.X,Qa:d,content:f,qb:l};d[y](e);this.a[y](e);a.db-=f[A];if(a.db<=0){e.uc=
b[Cb](c.a);break}else qj(a)}}else{if(!a.Sa||e>a.Vb||a.ic>=a.Wa&&a.Wa>0){if(a.Sa){rj(this);qj(a);a.Vb=a.W}a.Sa={na:j,ka:[],qb:l};this.a[y](a.Sa);a.ic=0}a.Sa.ka[y](a.X);a.Vb-=e+this.f.J.jc;a.db-=e;a.ic++}this.g.add(T(this.Bc,this))}else{this.g=j;if(this.a[A]==0)this.b.add(T(this.Xb,this));else this.D==0&&rj(this);this.b.go()}};Q.Vd=function(a){var b=Pc(a[Bb]);if(!(b[G]("javascript:")==0||b[G]("#")>=0)){this.fb[y](a[Bb]);this.k[y](a);a.href=b+"#googtrans/"+this.j+"/"+this.d}};
function rj(a){for(var b=3+a.oa;a.D<a.a[A]&&a.D<b;++a.D){var c=a,d=a.D,e=c.a[d],f=e.Sc||c.j,g=[];if(e.ka)for(var k=0;k<e.ka[A];++k)g[y](e.ka[k].ja);else g[y](e.content);e.na=c.f[Ib](T(c.Dd,c,d),g,f,c.d,d+1,c.rc)}}
Q.Dd=function(a,b,c){a=this.a[a];if(this.B&&a){if(c!=200)this.b.add(T(this.N,this,this.G,l,i));else if(a.ka){var d=[];for(c=0;c<b[A]&&c<a.ka[A];++c)if(b[c]&&b[c][1]&&b[c][1]==200){var e=b[c][0],f=b[c][2]&&b[c][2]==this.d;this.b.add(T(this.Sb,this,a.ka[c],e,f));if(b[c][2]){var g=b[c][2];this.c[g]||(this.c[g]=0);this.c[g]+=e[A]}}else d[y](a.ka[c]);this.j=="auto"&&d[A]>0&&!a.qb&&this.a[y]({na:j,Sc:"en",ka:d,qb:i})}else if(b&&b[0]){a.Uc=b[0][0];f=l;if(b[0][2]){g=b[0][2];f=g==this.d;if(this.c[g])this.c[g]=
0;this.c[g]=b[0][0][A]}b=[];for(c=0;c<a.Qa[A];++c)if(typeof a.Qa[c].Uc=="string"){b[y](a.Qa[c].Uc);a.Qa[c].uc&&b[y](a.Qa[c].uc)}else break;b[A]==a.Qa[A]&&this.b.add(T(this.Sb,this,a.X,b[Tb](""),f))}else if(this.j=="auto"&&!a.qb){a.Sc="en";a.qb=i;a.na=j;this.a[y](a)}this.oa++;(b=this.oa==this.a[A])&&this.b.add(T(this.Xb,this));this.g||this.b.go();rj(this)}};
Q.Sb=function(a,b,c){b?Xg(a,b,this.l,c):Yg(a,this.l);this.Rb+=a.ja[A];a=v.min(v[Qa](this.Rb*100/this.gb),100);if(this.G!=a){this.G=a;this.N(this.G,l)}};Q.Xb=function(){this.B=l;this.N&&this.N(100,i);this.a=j;this.D=this.oa=0;this.N=j;this.G=this.Rb=this.gb=0};
function sj(a){if(a.B){for(var b=0;b<a.a[A];++b)a.f.J.L[Pa](a.a[b].na);a.Xb()}if(a.g){a.g[Pa]();a.g=j}if(a.b){a.b[Pa]();a.b=j}if(a.m){for(b=0;b<a.m[A];++b)a.m[b].p();a.m=j}if(a.k){for(b=0;b<a.k[A];++b)a.k[b].href=a.fb[b];a.k=j;a.fb=j}if(a.Ha){var c=[][Xa](a.O);for(b=0;b<c[A];++b)fe(c[b],a.Ha);a.Ha=j}}
Q.translate=function(a,b,c){if(a!=this.j||b!=this.d){sj(this);this.l={}}else if(this.B)return;this.N=c;this.G=this.Rb=this.gb=0;this.b=new vg(0,0,50);this.B=i;this.j=a;this.d=b;if(this.sc){c=this.sc;b=b;a&&(c.l=a);b&&(c.m=b)}this.a=[];this.m=[];this.D=this.oa=0;this.k=[];this.fb=[];a=860;for(var d in this.l)if(this.l[d]!==r[B][d]){a=jj(this.f);break}this.eb={W:a,Vb:a,Eb:jj(this.f),db:this.f.J.gc,ic:0,Wa:this.f.J.Wa,Vc:this.f.J.lb,Sa:j,X:j};this.Ha=kg[Ha](this.d)?"translated-rtl":"translated-ltr";
a=[][Xa](this.O);for(d=0;d<a[A];++d)ee(a[d],this.Ha);this.Qb=[][Xa](this.O);this.K[Lb](this.Qb[Ia](),this.eb.Vc);this.g=new vg(0,0,50);this.g.add(T(this.Bc,this));this.g.go()};function qj(a){var b=a.W;if(a.W<a.Eb){a.W*=6;if(a.W>a.Eb)a.W=a.Eb}var c=a.db+1024;if(a.W>c)a.W=c;return b!=a.W}xa(Q,function(){sj(this)});Q.r=function(){pj.s.r[L](this);sj(this);this.O=this.K=j};function tj(){this.b=1;this.a={}}V(tj,Oc);var uj=new tj;function vj(a,b){if(a.a[b]){a.a[b][Fb]();a.a[b].p();a.a[b]=j}}tj[B].r=function(){for(var a in this.a)if(this.a[a]!==r[B][a]){var b;b=a;var c=ga(b);b=c==0&&/^[\s\xa0]*$/[Ha](b)?NaN:c;vj(this,b)}this.b=1;this.a={}};function wj(a,b,c,d){this.g=b;this.k=c;this.f=d;this.d=l;this.a=new cj(a||l);a=new wg;b=new Ag(T(this.a.Gd,this.a,xg(a)));this.zb=Bg(b,zg(a,T(this.zb,this)));this.yb=Bg(b,zg(a,T(this.yb,this)));this.Mb=Bg(b,zg(a,T(this.Mb,this)));xa(this,Bg(b,zg(a,T(this[Fb],this))));b.pa();a.pa();this.b=uj;this.c=this.pc(t[Wb])}V(wj,Oc);Q=wj[B];va(Q,function(){return this.a[Pb]()});function xj(a){Ig(a.a[Pb]()?"te_afas":"te_afau")}Q.zb=function(a,b){if(this.a[vb]())this.a.b[qb](b?{hl:b}:{},a);else{xj(this);a(j,i)}};
Q.yb=function(a){var b=t[Wb].lang;if(b)a(b);else if(this.a[vb]()){var c=new ih(t[J],l,l,1,1);b=[];try{for(var d=0,e=this.a.La.Jc;b[A]+d<e;){var f=c.Ya();if(c.S==1&&uh(f))jh(c);else if(f[F]==3){var g=Pc(f[Vb][E](/\xa0|[ \t]+/g," "));if(g){b[y](g);d+=g[A]}}}}catch(k){if(k!=gh)h(k)}e=this.a;b=b[Tb](" ");a=e.La.jb(a);b={q:b[Cb](0,e.La.Jc)};b.sl="auto";b.tl="en";e.La.L[qb](b,a)}else{xj(this);a(j,i)}};
Q.jd=function(a){var b=j;a=a!=j?a:this.c;a!=-1&&(b=this.b.a[a]);a="";if(!b)return a;if(b.j!="auto")return b.j;var c=0;if(b.c)for(var d in b.c)if(b.c[d]!==r[B][d])if(b.c[d]>c){c=b.c[d];a=d}return a};Q.Mb=function(a,b,c,d){if(a==b&&a!="zh-CN"||!a)a="auto";if(this.a[vb]()){if(d!==m&&typeof d=="number")d=d;else{d=d||t[Wb];if(this.b.a[this.c].O!=d){this[Fb]();vj(this.b,this.c);this.c=this.pc(d)}d=this.c}if(d=this.b.a[d]){d.rc=this.d;d[Ib](a,b,c)}}else{xj(this);c(0,l,i)}};
Q.$d=function(a){a=a!=j?a:this.c;return a==-1||!this.b.a[a]?l:this.b.a[a].B};Q.Qc=Zb("d");xa(Q,function(a){if(this.a[vb]()){a=a!=j?a:this.c;a!=-1&&this.b.a[a]&&this.b.a[a][Fb]()}});Q.r=function(){wj.s.r[L](this);this.a.p();this.a=j;this.b.p();this.c=m};Q.pc=function(a){var b=this.b;b.a[b.b]=new pj(a,this.a,this.g,this.k,this.f);return a=b.b++};Q.Zd=function(a){vj(this.b,a)};function yj(a,b){if(fc(a)=="string"){b=a;a={}}if(fc(b)=="string")b=ic(n(b))?t.getElementById(n(b)):n(b);this.k=b;var c=r(a);this.c="auto";var d;if(!(d=p.parent!=p)){if(d=!p.external||!p.external.googleToolbarVersion||fa(p.external.googleToolbarVersion)<6.2){if(d=!p.gtbExternal||!p.gtbExternal.isTranslateEnabled||!p.gtbExternal.isTranslateEnabled()){d=(d=aa.appVersion&&aa.appVersion[ob](/\sChrome\/((\d+)\.(\d+)\.[\d\.]+)\s/))&&d[2]&&d[3]?ga(d[2])*1E3+ga(d[3])>=4001:l;d=!d}d=d}d=d}this.e={tb:d,Tb:j,
ub:j,ec:[],Ac:[],bd:l,Xa:l,Ob:l,Cc:l,Yb:"",Ta:0};d=p[$a][sb]=="https:";this.oa={A:Ic,Ga:d?"\u6b64\u5b89\u5168\u7f51\u9875\u7684\u5185\u5bb9\u5c06\u901a\u8fc7\u5b89\u5168\u8fde\u63a5\u53d1\u9001\u7ed9 Google \u8fdb\u884c\u7ffb\u8bd1\u3002":j};this.e.Ob=d;this.O={A:Ic,mb:j};if(c){"autoDisplay"in c&&(this.e.tb=this.e.tb&&ca(c.autoDisplay));"multilanguagePage"in c&&(this.e.Xa=ca(c.multilanguagePage));"gaTrack"in c&&(this.e.Cc=ca(c.gaTrack));"layout"in c&&(this.e.Ta=c.layout);if(c.pageLanguage)this.e.Gb=
Gg(c.pageLanguage);if("useSecureConnection"in c){this.e.Ob=!!c.useSecureConnection;this.oa.Ga=this.e.Ob?"\u6b64\u5b89\u5168\u7f51\u9875\u7684\u5185\u5bb9\u5c06\u901a\u8fc7\u5b89\u5168\u8fde\u63a5\u53d1\u9001\u7ed9 Google \u8fdb\u884c\u7ffb\u8bd1\u3002":j}if(c.includedLanguages)this.e.ec=c.includedLanguages[Va](",");if(c.excludedLanguages)this.e.Ac=c.excludedLanguages[Va](",");if(this.e.Gb)this.c=this.e.Gb;if(c.gaId)this.e.Yb=c.gaId;this.O.mb=ga(c.floatPosition)||this.O.mb}zj(this);c={Z:zc?1:0,Fa:i,
se:Nc,aa:["client","u","scid"]};this.fb=new Pg(c);c={client:Ac,u:p[$a][Bb],scid:zc};this.fb.k=c||{};this.m=new wj(this.e.Ob,this.fb);this.f=new Yf(this);this.G=l;this.Ha=!this.e.tb&&!this.O.mb&&!this.k;Y(this.f,p,"unload",this.p);this.j=new wg(T(this.xd,this));this.D=new wg(T(this.zd,this));this.K=new Ag(T(this.Jd,this));this.a=new vh(this.oa);this.m.zb(xg(this.j,T(this.wd,this)),rc);if(this.k){this.b=new zh(this.e);Y(this.f,this.b,"load",xg(this.j));Y(this.f,this.b,"chg_tgt_lang",Bg(this.K,zg(this.D,
T(this.vd,this))));this.b.ma(this.k)}else if(this.O.mb){this.g=new Bh(this.O);Y(this.f,this.g,"load",xg(this.j));Y(this.f,this.g,"clk_trans",Bg(this.K,zg(this.D,T(this.td,this))));this.g.ma()}!this.e.Gb&&this.e.bd&&this.m.yb(xg(this.j,T(this.rd,this)));this.j.pa()}V(yj,Oc);
function zj(a){function b(f,g){var k=ha(f[E](/\+/g," "))[ob]("^\\((([a-zA-Z\\-_]*)\\|)?([a-zA-Z\\-_]*)\\)|^/(([a-zA-Z\\-_]*)/)?([a-zA-Z\\-_]*)");if(k)if(k[3]){g.e.Tb=k[2];g.e.ub=k[3];return i}else if(k[6]){g.e.Tb=k[5];g.e.ub=k[6];return i}return l}for(var c=[function(){var f=p[$a][Bb][ob](/#.*googtrans(.*)/);return f&&f[1]},function(){var f=t.cookie[ob](/(^|; )googtrans=(.*?)(;|$)/);return f&&f[2]}],d=0;d<c[A];++d){var e=c[d]();if(e&&b(e,a))break}}
function Aj(a,b,c){for(a=p[$a].hostname[Va](".");a[A]>2;)a[Ia]();a=";domain="+a[Tb](".")+";path=/";if(!b&&!c){b=new Date;b.setTime(b.getTime()-1);b="googtrans=none;expires="+b.toGMTString()}else b=b?"googtrans=/"+b+"/"+c:"googtrans=/"+c;t.cookie=b;try{t.cookie=b+a}catch(d){}}Q=yj[B];
Q.wd=function(a){this.d=Gg(rc);this.B=a||{};this.l={};this.N={};a=!this.e.ec[A];var b=ug(this.e.ec),c=ug(this.e.Ac);this.l[rc]="";this.N[rc]="";for(var d in this.B.tl)if(this.B.tl[d]!==r[B][d])if((a||d in b)&&!(d in c)){this.N[d]=this.B.tl[d];if(d!=this.e.Gb||this.e.Xa)this.l[d]=this.B.tl[d]}this.l[rc]||delete this.l[rc];this.N[rc]||delete this.N[rc];var e;d=this.B.sl;a={};for(e in d)a[e]=d[e];this.eb=e=a};Q.rd=function(a){if(a)this.c=Gg(a)};
Q.xd=function(){delete this.j;if(this.B){this.c=this.c||this.e.Tb;this.d=this.e.ub||this.d;var a=this.e.tb&&this.c!=this.d&&!(this.c in uc);if(this.c=="zh-TW")this.c="zh-CN";if(!this.eb[this.c]){a=l;this.c="auto"}if(!this.l[this.d]){a=l;if(this.l.en)this.d="en";else for(var b in this.l)if(this.l[b]!==r[B][b]){this.d=b;break}}if(this.b){var c=this.l,d={"":"\u9009\u62e9\u8bed\u8a00"};for(b in c)if(c[b]!==r[B][b])d[b]=c[b];this.b.mc(d,this.N);this.b.U("")}if(!tc&&a)if(this.e.ub)Bg(this.K,zg(this.D,T(this.Jb,
this,i,i)))[L]();else{this.G=i;Bg(this.K,zg(this.D,T(this.Jb,this)))[L]();Ig("te_ap",{sl:this.c})}else{this.g&&this.g.P(i);this.b&&this.b.P(i)}p.google[Ib].TranslateService&&this.bb(l);this.K.pa()}};
Q.zd=function(){var a=this.a,b=this.eb;a.I&&a.I.ua(b);a.l=b;this.a.mc(this.l,this.N);wh(this.a,this.c);this.a.U(this.d);Y(this.f,this.a,"clk_confirm",this.pd);Y(this.f,this.a,"clk_cancel",this.od);Y(this.f,this.a,"clk_restore",this.ac);Y(this.f,this.a,"clk_close",this.$b);Y(this.f,this.a,"clk_no_ap",this.qd);Y(this.f,this.a,"chg_src_lang",this.Fc);Y(this.f,this.a,"chg_tgt_lang",this.Fc);this.b&&this.b.P(i)};Q.Jd=function(){Y(this.f,this.a,"load",xg(this.D));this.a.ma();this.D.pa()};
Q.r=function(){this.m[Fb]();yj.s.r[L](this);this.m.p();this.f.p();this.f=j;this.a&&this.a.p();this.a=j;this.g&&this.g.p();this.g=j;this.b&&this.b.p();this.k=this.b=j};Q.pd=function(){if(!(!this.a.fa()||!this.e.Xa&&this.c==this.a.ba())){this.G&&Ig("te_apt",{sl:this.c});Bj(this,l);this.b&&this.b.U(this.a.ba())}};Q.od=function(){if(this.a.fa()){Cj(this);xh(this.a,0);this.b&&this.b.U("")}};Q.ac=function(){if(this.a.fa()){Cj(this);xh(this.a,0)}this.b&&this.b.U("")};
Q.$b=function(){if(this.a.fa()){if(this.G){this.G=l;Ig("te_apc",{sl:this.c})}Cj(this);this.a.P(l);this.b&&this.b.U("");this.g&&this.g.P(i)}};Q.qd=function(){if(this.a.fa()){Ig("te_apr",{sl:this.c});this.G=l;this.$b();if(this.Ha){var a=this.onTurnOffLanguageClick;try{fc(a)=="function"&&a[Hb](this,[])}catch(b){}}}};
Q.Fc=function(){if(this.a.fa())if(!this.e.Xa&&this.c==this.a.ba())this.ac();else{this.c=(this.a.I?this.a.I.Ab():"")||this.c;this.d=this.a.ba();if(this.a.kb==2){this.b&&this.b.U(this.a.ba());Bj(this)}}};Q.Jb=function(a,b){if(!this.a.fa()){this.g&&this.g.P(l);a?Bj(this,b):xh(this.a,0,i,this.G||this.Ha)}};Q.Xd=function(a,b){Bg(this.K,zg(this.D,T(this.Jb,this,a,b)))[L]()};Q.td=function(){this.Jb(this.a.kb==2)};
Q.vd=function(){if(this.b.ba())if(!this.e.Xa&&this.c==this.b.ba())this.ac();else{this.d=this.b.ba();this.a.U(this.d);Bj(this)}else this.b.U(this.d)};
function Bj(a,b){if(p.google[Ib].TranslateService)try{var c=p.google[Ib].TranslateService.getInstance();c[Fb]()}catch(d){}a.G=l;!b&&a.c in uc&&Ig("te_ape",{sl:a.c});yh(a.a,0);xh(a.a,1,i);a.m.Qc(!!b);p[Ta](T(a.m.Mb,a.m,a.e.Xa?"auto":a.c,a.d,T(a.Cd,a),j),0);if(a.e.Cc&&p._gaq&&p._gat)try{a.e.Yb?p._gat._getTracker(a.e.Yb)._trackEvent("Google Website Translator","Translate",a.d):p._gat._getTrackerByName()._trackEvent("Google Website Translator","Translate",a.d)}catch(e){}}
Q.Cd=function(a,b,c){fc(this.gb)=="function"&&this.gb();if(!(!this.a.fa()||this.a.kb!=1))if(c){Cj(this);xh(this.a,-1,i)}else{yh(this.a,a);if(b){this.b&&this.b.U(this.d);wh(this.a,this.c);xh(this.a,2);Aj(this,this.c,this.d)}}};function Cj(a){Aj(a);p[Ta](T(a.m[Fb],a.m,j),0)}Q.bb=function(a){a||this.$b();this.b&&this.b.bb(a);this.g&&this.g.P(a)};function Dj(a){if(a){a=n(a);a=a[Va](".");if(a[A]){for(var b=p,c=0;c<a[A];++c){var d=a[c];if(!d||!(d in b))return;b=b[d]}return b}}}function Ej(){for(var a in r[B]){qd=function(d,e,f){for(var g in d)d[g]!==r[B][g]&&e[L](f,d[g],g,d)};break}var b=pc(),c=Dj(sc);if(c&&fc(c)=="function")vc==1?c():function d(){var e=t.readyState;fc(e)=="undefined"||e=="complete"||pc()-b>=2E4?c():p[Ta](d,500)}()};if(vc==1){var $=j,Fj=function(a){if(!$){var b=p[$a][sb]=="https:";if(a&&"useSecureConnection"in a)b=!!a.useSecureConnection;a={formMode:0,showLogo:i,suggestUrl:Nc,clientName:Ac,pageUrl:p[$a][Bb]};a=new Pg(a);$=new wj(b,a);$.constructor=m;va($,$[vb]);$.getSupportedLanguages=$.zb;$.getPageLanguage=$.yb;$.getDetectedLanguage=$.jd;$.createContext=$.pc;$.disposeContext=$.Zd;$.setClickThrough=$.Qc;$.translatePage=$.Mb;xa($,$[Fb]);$.isTranslating=$.$d}return $};Fj.getInstance=function(){return $};bc("google.translate.TranslateService",
Fj,void 0);Ig("te_li")}else{var Gj=j,Hj=function(a,b){if(!Gj){Gj=new yj(a,b);Gj.constructor=m}return Gj};Hj.getInstance=function(){return Gj};bc("google.translate.TranslateElement",Hj,void 0);yj[B].dispose=yj[B].p;yj[B].showBanner=yj[B].Xd;yj[B].setEnabled=yj[B].bb;bc("google.translate.TranslateElement.FloatPosition",Ch,void 0);Ch.TOP_LEFT=1;Ch.TOP_RIGHT=2;Ch.BOTTOM_RIGHT=3;Ch.BOTTOM_LEFT=4;bc("google.translate.TranslateElement.InlineLayout",Ah,void 0);Ah.VERTICAL=0;Ah.HORIZONTAL=1;Ah.SIMPLE=2}Ej();})()
