package com.jun.plugin.bizservice.pojo;

import java.util.Date;

public class BizNovel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_novel.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_novel.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_novel.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_novel.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_novel.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_novel.uptime
     *
     * @mbg.generated
     */
    private String uptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_novel.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_novel.fileid
     *
     * @mbg.generated
     */
    private Integer fileid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_novel.content_detail
     *
     * @mbg.generated
     */
    private String content_detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_novel.id
     *
     * @return the value of biz_novel.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_novel.id
     *
     * @param id the value for biz_novel.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_novel.type
     *
     * @return the value of biz_novel.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_novel.type
     *
     * @param type the value for biz_novel.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_novel.url
     *
     * @return the value of biz_novel.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_novel.url
     *
     * @param url the value for biz_novel.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_novel.title
     *
     * @return the value of biz_novel.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_novel.title
     *
     * @param title the value for biz_novel.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_novel.content
     *
     * @return the value of biz_novel.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_novel.content
     *
     * @param content the value for biz_novel.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_novel.uptime
     *
     * @return the value of biz_novel.uptime
     *
     * @mbg.generated
     */
    public String getUptime() {
        return uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_novel.uptime
     *
     * @param uptime the value for biz_novel.uptime
     *
     * @mbg.generated
     */
    public void setUptime(String uptime) {
        this.uptime = uptime == null ? null : uptime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_novel.createtime
     *
     * @return the value of biz_novel.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_novel.createtime
     *
     * @param createtime the value for biz_novel.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_novel.fileid
     *
     * @return the value of biz_novel.fileid
     *
     * @mbg.generated
     */
    public Integer getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_novel.fileid
     *
     * @param fileid the value for biz_novel.fileid
     *
     * @mbg.generated
     */
    public void setFileid(Integer fileid) {
        this.fileid = fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_novel.content_detail
     *
     * @return the value of biz_novel.content_detail
     *
     * @mbg.generated
     */
    public String getContent_detail() {
        return content_detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_novel.content_detail
     *
     * @param content_detail the value for biz_novel.content_detail
     *
     * @mbg.generated
     */
    public void setContent_detail(String content_detail) {
        this.content_detail = content_detail == null ? null : content_detail.trim();
    }
}