package com.jun.plugin.bizservice.pojo;

import java.util.Date;

public class SysLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.log_title
     *
     * @mbg.generated
     */
    private String log_title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.log_content
     *
     * @mbg.generated
     */
    private String log_content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.log_content_detail
     *
     * @mbg.generated
     */
    private String log_content_detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.id
     *
     * @return the value of sys_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.id
     *
     * @param id the value for sys_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.log_title
     *
     * @return the value of sys_log.log_title
     *
     * @mbg.generated
     */
    public String getLog_title() {
        return log_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.log_title
     *
     * @param log_title the value for sys_log.log_title
     *
     * @mbg.generated
     */
    public void setLog_title(String log_title) {
        this.log_title = log_title == null ? null : log_title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.log_content
     *
     * @return the value of sys_log.log_content
     *
     * @mbg.generated
     */
    public String getLog_content() {
        return log_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.log_content
     *
     * @param log_content the value for sys_log.log_content
     *
     * @mbg.generated
     */
    public void setLog_content(String log_content) {
        this.log_content = log_content == null ? null : log_content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.createtime
     *
     * @return the value of sys_log.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.createtime
     *
     * @param createtime the value for sys_log.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.log_content_detail
     *
     * @return the value of sys_log.log_content_detail
     *
     * @mbg.generated
     */
    public String getLog_content_detail() {
        return log_content_detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.log_content_detail
     *
     * @param log_content_detail the value for sys_log.log_content_detail
     *
     * @mbg.generated
     */
    public void setLog_content_detail(String log_content_detail) {
        this.log_content_detail = log_content_detail == null ? null : log_content_detail.trim();
    }
}