package com.jun.plugin.bizservice.pojo;

public class Testclob {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testclob.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testclob.resume
     *
     * @mbg.generated
     */
    private String resume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testclob.id
     *
     * @return the value of testclob.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testclob.id
     *
     * @param id the value for testclob.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testclob.resume
     *
     * @return the value of testclob.resume
     *
     * @mbg.generated
     */
    public String getResume() {
        return resume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testclob.resume
     *
     * @param resume the value for testclob.resume
     *
     * @mbg.generated
     */
    public void setResume(String resume) {
        this.resume = resume == null ? null : resume.trim();
    }
}