package com.hanke.hbrid.template.drools

/**
import java.util.Map;

rule "hydropenia highly"
	when 
		$map : Map(
			agroType=="SANDY_SOIL"&&moisture<80.0
			)
	then
		$map.put("s1", 444);
end

rule "hydropenia lowly"
	when 
		$map : Map(
			agroType=="CLAY_SOIL"&&moisture<50.0
		)
	then
		$map.put("s1", 666);
end
*/

import org.drools.examples.helloworld.ExpertBaseData
import org.drools.examples.helloworld.InputDataModel
import org.drools.examples.helloworld.OutputDataModel

rule "hydropenia highly"
	when 
	 	$expertBaseData : ExpertBaseData( )
    	$inputDataModel : InputDataModel( agroType=="SANDY_SOIL", moisture<80.0 )
	then
		System.out.println(111);
		$expertBaseData.getOutputDataModel.put("s1", 444);
end

rule "hydropenia lowly"
	when 
		$expertBaseData : ExpertBaseData( )
    	$inputDataModel : InputDataModel( agroType=="CLAY_SOIL", moisture<50.0 )
	then
		System.out.println(222);
		$expertBaseData.getOutputDataModel.put("s1", 666);
end