DROP TABLE IF EXISTS user;

CREATE TABLE user
(
    id BIGINT(20) NOT NULL COMMENT '主键ID',
    username VARCHAR(30) NULL DEFAULT NULL COMMENT '用户名',
    mobile VARCHAR(11) NULL DEFAULT NULL COMMENT '手机号',
    email VARCHAR(255) NULL DEFAULT NULL COMMENT '邮箱',
    PRIMARY KEY (id)
);