DROP TABLE IF EXISTS user;

CREATE TABLE user
(
    id BIGINT(20) NOT NULL COMMENT '主键ID',
    username VARCHAR(30) NULL DEFAULT NULL COMMENT '用户名',
    sex INT(2) NULL DEFAULT NULL COMMENT '性别',
    status INT(2) NULL DEFAULT NULL COMMENT '状态',
    PRIMARY KEY (id)
);