package com.jfinal.plugin.activerecord.model;

import com.jfinal.plugin.activerecord.model.base.BaseBlog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Blog extends BaseBlog<Blog> {
	
}
