package org.drools.mydemo.employee

import org.drools.mydemo.employee.Employ;

rule "Award"
        ruleflow-group "award_punish"
when
   emp: Employ(awardPunish== "award" )
then
   System.out.println( "exec rule Award ... " );
   emp.setPercent(1.10);
end

rule "Punishment"
        ruleflow-group "award_punish"
when
   emp: Employ(awardPunish== "punish" )
then
   System.out.println( "exec rule Punishment ... " );
   emp.setPercent(0.90);
end

rule "None"
       ruleflow-group "award_punish"
when
   emp: Employ(awardPunish== "none" )
then
   System.out.println( "exec rule None ... " );
   emp.setPercent(1.00);
end