package org.drools.mydemo.employee

import org.drools.mydemo.employee.Employ;

rule "Excellent"
       ruleflow-group "bonus_salary"
when
   emp: Employ(annualExam== "excellent" )
then
   System.out.println( "exec rule Excellent ... " );
   emp.setBonus(1000*1.0);
end

rule "Good"
        ruleflow-group "bonus_salary"
when
   emp: Employ(annualExam== "good" )
then
   System.out.println( "exec rule Good ... " );
   emp.setBonus(1000*0.9);
end

rule "Common"
       ruleflow-group "bonus_salary"
when
   emp: Employ(annualExam== "common" )
then
   System.out.println( "exec rule Common ... " );
   emp.setBonus(1000*0.6);
end

rule "failing"
        ruleflow-group "bonus_salary"
when
   emp: Employ(annualExam== "failing" )
then
   System.out.println( "exec rule failing ... " );
   emp.setBonus(1000*0.0);
end