package ${packageName}.model;

import net.ymate.platform.persistence.base.IEntity;

/**
 * BaseEntity generated By EntityGenerator on ${lastUpdateTime?string("yyyy/MM/dd a HH:mm:ss")}
 * 
 * @author YMP
 * @version 1.0
 */
public abstract class BaseEntity<PK> implements IEntity<PK> {

	private static final long serialVersionUID = 1L;

	public BaseEntity() {
	}
}
