INSERT INTO `module_tree` (id,name,priority,lft,rgt,parentId) VALUES (1, 'Food', 1, 1, 18, NULL);
INSERT INTO `module_tree` (id,name,priority,lft,rgt,parentId) VALUES (2, 'Fruit', 3, 2, 11, 1);
INSERT INTO `module_tree` (id,name,priority,lft,rgt,parentId) VALUES (3, 'Red', 39, 3, 6, 2);
INSERT INTO `module_tree` (id,name,priority,lft,rgt,parentId) VALUES (4, 'Cherry', 31, 4, 5, 3);
INSERT INTO `module_tree` (id,name,priority,lft,rgt,parentId) VALUES (5, 'Yellow', 7, 7, 10, 2);
INSERT INTO `module_tree` (id,name,priority,lft,rgt,parentId) VALUES (6, 'Banana', 8, 8, 9, 5);
INSERT INTO `module_tree` (id,name,priority,lft,rgt,parentId) VALUES (7, 'Meat', 12, 12, 17, 1);
INSERT INTO `module_tree` (id,name,priority,lft,rgt,parentId) VALUES (8, 'Beef', 13, 13, 14, 7);
INSERT INTO `module_tree` (id,name,priority,lft,rgt,parentId) VALUES (9, 'Pork', 15, 15, 16, 7);
