package com.jun.plugin.bizservice.mapper;

import com.jun.plugin.bizservice.pojo.BizFile;

public interface BizFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_file
     *
     * @mbg.generated
     */
    int insert(BizFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_file
     *
     * @mbg.generated
     */
    int insertSelective(BizFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_file
     *
     * @mbg.generated
     */
    BizFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BizFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(BizFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BizFile record);
}