package com.jun.plugin.bizservice.mapper;

import com.jun.plugin.bizservice.pojo.BizNovel;

public interface BizNovelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_novel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_novel
     *
     * @mbg.generated
     */
    int insert(BizNovel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_novel
     *
     * @mbg.generated
     */
    int insertSelective(BizNovel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_novel
     *
     * @mbg.generated
     */
    BizNovel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_novel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BizNovel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_novel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(BizNovel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_novel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BizNovel record);
}