package com.jun.plugin.bizservice.mapper;

import com.jun.plugin.bizservice.pojo.Testclob;

public interface TestclobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testclob
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testclob
     *
     * @mbg.generated
     */
    int insert(Testclob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testclob
     *
     * @mbg.generated
     */
    int insertSelective(Testclob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testclob
     *
     * @mbg.generated
     */
    Testclob selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testclob
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Testclob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testclob
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Testclob record);
}