DROP TABLE IF EXISTS user;

CREATE TABLE user
(
    id BIGINT(20) NOT NULL COMMENT '主键ID',
    username VARCHAR(30) NULL DEFAULT NULL COMMENT '用户名',
    mobile VARCHAR(11) NULL DEFAULT NULL COMMENT '手机号',
    email VARCHAR(255) NULL DEFAULT NULL COMMENT '邮箱',
    wallet DECIMAL(20,2) NULL DEFAULT NULL COMMENT '钱包余额',
    amount DECIMAL(20,2) NULL DEFAULT NULL COMMENT '存蓄金额',
    PRIMARY KEY (id)
);