
package org.service.query;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2018-02-02T12:59:57.698+08:00
 * Generated source version: 3.1.7
 * 
 */
public final class QueryServiceInter_QueryServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://query.service.org/", "QueryServiceService");

    private QueryServiceInter_QueryServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = QueryServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        QueryServiceService ss = new QueryServiceService(wsdlURL, SERVICE_NAME);
        QueryServiceInter port = ss.getQueryServicePort();  
        
        {
        System.out.println("Invoking queryCarInfomation...");
        java.lang.String _queryCarInfomation_carParam = "";
        java.lang.String _queryCarInfomation__return = port.queryCarInfomation(_queryCarInfomation_carParam);
        System.out.println("queryCarInfomation.result=" + _queryCarInfomation__return);


        }
        {
        System.out.println("Invoking queryPersonnelInformation...");
        java.lang.String _queryPersonnelInformation_peopleParam = "";
        java.lang.String _queryPersonnelInformation__return = port.queryPersonnelInformation(_queryPersonnelInformation_peopleParam);
        System.out.println("queryPersonnelInformation.result=" + _queryPersonnelInformation__return);


        }

        System.exit(0);
    }

}
