package org.supercall.models;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysDictExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dict
     *
     * @mbggenerated Mon Jul 25 21:37:06 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dict
     *
     * @mbggenerated Mon Jul 25 21:37:06 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dict
     *
     * @mbggenerated Mon Jul 25 21:37:06 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Mon Jul 25 21:37:06 CST 2016
     */
    public SysDictExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Mon Jul 25 21:37:06 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Mon Jul 25 21:37:06 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Mon Jul 25 21:37:06 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Mon Jul 25 21:37:06 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Mon Jul 25 21:37:06 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Mon Jul 25 21:37:06 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Mon Jul 25 21:37:06 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Mon Jul 25 21:37:06 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Mon Jul 25 21:37:06 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Mon Jul 25 21:37:06 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_dict
     *
     * @mbggenerated Mon Jul 25 21:37:06 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDictkeyIsNull() {
            addCriterion("dictkey is null");
            return (Criteria) this;
        }

        public Criteria andDictkeyIsNotNull() {
            addCriterion("dictkey is not null");
            return (Criteria) this;
        }

        public Criteria andDictkeyEqualTo(String value) {
            addCriterion("dictkey =", value, "dictkey");
            return (Criteria) this;
        }

        public Criteria andDictkeyNotEqualTo(String value) {
            addCriterion("dictkey <>", value, "dictkey");
            return (Criteria) this;
        }

        public Criteria andDictkeyGreaterThan(String value) {
            addCriterion("dictkey >", value, "dictkey");
            return (Criteria) this;
        }

        public Criteria andDictkeyGreaterThanOrEqualTo(String value) {
            addCriterion("dictkey >=", value, "dictkey");
            return (Criteria) this;
        }

        public Criteria andDictkeyLessThan(String value) {
            addCriterion("dictkey <", value, "dictkey");
            return (Criteria) this;
        }

        public Criteria andDictkeyLessThanOrEqualTo(String value) {
            addCriterion("dictkey <=", value, "dictkey");
            return (Criteria) this;
        }

        public Criteria andDictkeyLike(String value) {
            addCriterion("dictkey like", value, "dictkey");
            return (Criteria) this;
        }

        public Criteria andDictkeyNotLike(String value) {
            addCriterion("dictkey not like", value, "dictkey");
            return (Criteria) this;
        }

        public Criteria andDictkeyIn(List<String> values) {
            addCriterion("dictkey in", values, "dictkey");
            return (Criteria) this;
        }

        public Criteria andDictkeyNotIn(List<String> values) {
            addCriterion("dictkey not in", values, "dictkey");
            return (Criteria) this;
        }

        public Criteria andDictkeyBetween(String value1, String value2) {
            addCriterion("dictkey between", value1, value2, "dictkey");
            return (Criteria) this;
        }

        public Criteria andDictkeyNotBetween(String value1, String value2) {
            addCriterion("dictkey not between", value1, value2, "dictkey");
            return (Criteria) this;
        }

        public Criteria andDictvaluesIsNull() {
            addCriterion("dictvalues is null");
            return (Criteria) this;
        }

        public Criteria andDictvaluesIsNotNull() {
            addCriterion("dictvalues is not null");
            return (Criteria) this;
        }

        public Criteria andDictvaluesEqualTo(String value) {
            addCriterion("dictvalues =", value, "dictvalues");
            return (Criteria) this;
        }

        public Criteria andDictvaluesNotEqualTo(String value) {
            addCriterion("dictvalues <>", value, "dictvalues");
            return (Criteria) this;
        }

        public Criteria andDictvaluesGreaterThan(String value) {
            addCriterion("dictvalues >", value, "dictvalues");
            return (Criteria) this;
        }

        public Criteria andDictvaluesGreaterThanOrEqualTo(String value) {
            addCriterion("dictvalues >=", value, "dictvalues");
            return (Criteria) this;
        }

        public Criteria andDictvaluesLessThan(String value) {
            addCriterion("dictvalues <", value, "dictvalues");
            return (Criteria) this;
        }

        public Criteria andDictvaluesLessThanOrEqualTo(String value) {
            addCriterion("dictvalues <=", value, "dictvalues");
            return (Criteria) this;
        }

        public Criteria andDictvaluesLike(String value) {
            addCriterion("dictvalues like", value, "dictvalues");
            return (Criteria) this;
        }

        public Criteria andDictvaluesNotLike(String value) {
            addCriterion("dictvalues not like", value, "dictvalues");
            return (Criteria) this;
        }

        public Criteria andDictvaluesIn(List<String> values) {
            addCriterion("dictvalues in", values, "dictvalues");
            return (Criteria) this;
        }

        public Criteria andDictvaluesNotIn(List<String> values) {
            addCriterion("dictvalues not in", values, "dictvalues");
            return (Criteria) this;
        }

        public Criteria andDictvaluesBetween(String value1, String value2) {
            addCriterion("dictvalues between", value1, value2, "dictvalues");
            return (Criteria) this;
        }

        public Criteria andDictvaluesNotBetween(String value1, String value2) {
            addCriterion("dictvalues not between", value1, value2, "dictvalues");
            return (Criteria) this;
        }

        public Criteria andDictgroupIsNull() {
            addCriterion("dictgroup is null");
            return (Criteria) this;
        }

        public Criteria andDictgroupIsNotNull() {
            addCriterion("dictgroup is not null");
            return (Criteria) this;
        }

        public Criteria andDictgroupEqualTo(String value) {
            addCriterion("dictgroup =", value, "dictgroup");
            return (Criteria) this;
        }

        public Criteria andDictgroupNotEqualTo(String value) {
            addCriterion("dictgroup <>", value, "dictgroup");
            return (Criteria) this;
        }

        public Criteria andDictgroupGreaterThan(String value) {
            addCriterion("dictgroup >", value, "dictgroup");
            return (Criteria) this;
        }

        public Criteria andDictgroupGreaterThanOrEqualTo(String value) {
            addCriterion("dictgroup >=", value, "dictgroup");
            return (Criteria) this;
        }

        public Criteria andDictgroupLessThan(String value) {
            addCriterion("dictgroup <", value, "dictgroup");
            return (Criteria) this;
        }

        public Criteria andDictgroupLessThanOrEqualTo(String value) {
            addCriterion("dictgroup <=", value, "dictgroup");
            return (Criteria) this;
        }

        public Criteria andDictgroupLike(String value) {
            addCriterion("dictgroup like", value, "dictgroup");
            return (Criteria) this;
        }

        public Criteria andDictgroupNotLike(String value) {
            addCriterion("dictgroup not like", value, "dictgroup");
            return (Criteria) this;
        }

        public Criteria andDictgroupIn(List<String> values) {
            addCriterion("dictgroup in", values, "dictgroup");
            return (Criteria) this;
        }

        public Criteria andDictgroupNotIn(List<String> values) {
            addCriterion("dictgroup not in", values, "dictgroup");
            return (Criteria) this;
        }

        public Criteria andDictgroupBetween(String value1, String value2) {
            addCriterion("dictgroup between", value1, value2, "dictgroup");
            return (Criteria) this;
        }

        public Criteria andDictgroupNotBetween(String value1, String value2) {
            addCriterion("dictgroup not between", value1, value2, "dictgroup");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updatetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updatetime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updatetime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updatetime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updatetime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updatetime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updatetime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updatetime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updatetime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updatetime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updatetime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatorIsNull() {
            addCriterion("updator is null");
            return (Criteria) this;
        }

        public Criteria andUpdatorIsNotNull() {
            addCriterion("updator is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatorEqualTo(String value) {
            addCriterion("updator =", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotEqualTo(String value) {
            addCriterion("updator <>", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorGreaterThan(String value) {
            addCriterion("updator >", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorGreaterThanOrEqualTo(String value) {
            addCriterion("updator >=", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLessThan(String value) {
            addCriterion("updator <", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLessThanOrEqualTo(String value) {
            addCriterion("updator <=", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLike(String value) {
            addCriterion("updator like", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotLike(String value) {
            addCriterion("updator not like", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorIn(List<String> values) {
            addCriterion("updator in", values, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotIn(List<String> values) {
            addCriterion("updator not in", values, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorBetween(String value1, String value2) {
            addCriterion("updator between", value1, value2, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotBetween(String value1, String value2) {
            addCriterion("updator not between", value1, value2, "updator");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_dict
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 25 21:37:06 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_dict
     *
     * @mbggenerated Mon Jul 25 21:37:06 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}