package demo;
 
import demo.Machine;
import demo.Test;
import demo.TestDAO;
import java.util.Calendar;
import java.sql.Timestamp;
global TestDAO testDAO;

	
rule "Tests for type11 machine"
lock-on-active true
salience 100

when
	machine : Machine( type == "Type1" )
then	
	Test test1 = testDAO.findByKey(Test.TEST1);
	Test test2 = testDAO.findByKey(Test.TEST2);
	Test test5 = testDAO.findByKey(Test.TEST5);
	machine.getTests().add(test1);
	machine.getTests().add(test2);
	machine.getTests().add(test5);
	update( machine );
end

rule "Tests for type21, DNS server machine"
lock-on-active true
salience 100

when
	machine : Machine( type == "Type2", functions contains "DNS Server")
then	
	Test test5 = testDAO.findByKey(Test.TEST5);
	Test test4 = testDAO.findByKey(Test.TEST4);
	machine.getTests().add(test5);
	machine.getTests().add(test4);
	update( machine );
end

rule "Tests for type21, DDNS server machine"
lock-on-active true
salience 100

when
	machine : Machine( type == "Type2", functions contains "DDNS Server")
then	
	Test test2 = testDAO.findByKey(Test.TEST2);
	Test test3 = testDAO.findByKey(Test.TEST3);
	machine.getTests().add(test2);
	machine.getTests().add(test3);
	update( machine );	
end

rule "Tests for type21, Gateway machine"
lock-on-active true
salience 100

when
	machine : Machine( type == "Type2", functions contains "Gateway")
then		
	Test test3 = testDAO.findByKey(Test.TEST3);
	Test test4 = testDAO.findByKey(Test.TEST4);
	machine.getTests().add(test3);
	machine.getTests().add(test4);
	update( machine );
end

rule "Tests for type21, Router machine"
lock-on-active true
salience 100

when
	machine : Machine( type == "Type2", functions contains "Router")
then	
	Test test3 = testDAO.findByKey(Test.TEST3);
	Test test1 = testDAO.findByKey(Test.TEST1);
	machine.getTests().add(test3);
	machine.getTests().add(test1);
	update( machine );				
end

rule "Due date for Test 51"
salience 50
when
	machine : Machine(tests contains (testDAO.findByKey(Test.TEST5)))
then	
	setTestsDueTime(machine, 14);				
end

rule "Due date for Test 41"
salience 40
when
	machine : Machine(tests contains (testDAO.findByKey(Test.TEST4)))
then	
	setTestsDueTime(machine, 12);				
end

rule "Due date for Test 31"
salience 30
when
	machine : Machine(tests contains (testDAO.findByKey(Test.TEST3)))
then	
	setTestsDueTime(machine, 10);				
end

rule "Due date for Test 21"
salience 20
when
	machine : Machine(tests contains (testDAO.findByKey(Test.TEST2)))
then	
	setTestsDueTime(machine, 7);			
end

rule "Due date for Test 11"
salience 10
when
	machine : Machine(tests contains (testDAO.findByKey(Test.TEST1)))
then	
	setTestsDueTime(machine, 3);			
end

