/*
 * This file is generated by jOOQ.
*/
package com.mycompany.myproject.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Welcome implements Serializable {

    private static final long serialVersionUID = 1573146830;

    private Integer   id;
    private String    welcomeMsg;
    private String    createBy;
    private Timestamp createDate;
    private String    updateBy;
    private Timestamp updateDate;

    public Welcome() {}

    public Welcome(Welcome value) {
        this.id = value.id;
        this.welcomeMsg = value.welcomeMsg;
        this.createBy = value.createBy;
        this.createDate = value.createDate;
        this.updateBy = value.updateBy;
        this.updateDate = value.updateDate;
    }

    public Welcome(
        Integer   id,
        String    welcomeMsg,
        String    createBy,
        Timestamp createDate,
        String    updateBy,
        Timestamp updateDate
    ) {
        this.id = id;
        this.welcomeMsg = welcomeMsg;
        this.createBy = createBy;
        this.createDate = createDate;
        this.updateBy = updateBy;
        this.updateDate = updateDate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getWelcomeMsg() {
        return this.welcomeMsg;
    }

    public void setWelcomeMsg(String welcomeMsg) {
        this.welcomeMsg = welcomeMsg;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public Timestamp getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Timestamp updateDate) {
        this.updateDate = updateDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Welcome (");

        sb.append(id);
        sb.append(", ").append(welcomeMsg);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createDate);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateDate);

        sb.append(")");
        return sb.toString();
    }
}
