/*
 * This file is generated by jOOQ.
*/
package com.mycompany.myproject.jooq;


import com.mycompany.myproject.jooq.tables.Welcome;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>barry</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index WELCOME_PRIMARY = Indexes0.WELCOME_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index WELCOME_PRIMARY = Internal.createIndex("PRIMARY", Welcome.WELCOME, new OrderField[] { Welcome.WELCOME.ID }, true);
    }
}
