server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password:
    schema: classpath:db/schema-H2.sql
    name: test

mybatis-plus:
  type-aliases-package: org.snaker.engine.entity